### ISSUE TITLE
Icons Settings Not Overwriting Default Configuration

### ISSUE THREAD

**Issue by JuniorSuperTux** [ray-x/navigator.lua#100]
Here's my config following the example in README.md:
```lua
require ("lsp_signature").setup({
    default_mapping = true,
    treesitter_analysis = true,
    transparency = 10,
    icons = {
        diagnostic_err = "",
        diagnostic_warn = "",
        diagnostic_info = [[]],
        diagnostic_hint = [[ﯦ]],
        diagnostic_virtual_text = ""
    }
})
```
However, when errors and warnings showed up, neither the diagnostic error/warning icons nor the diagnostic virtual text icon were overwritten. It's still the fox and not so round error icon. Any idea on how to fix that?

**Comment by ray-x** [comment]
![image](https://user-images.githubusercontent.com/1681295/142065276-87c287ef-2e04-4242-9b88-76574b048925.png)

It works fine on my side.
Is it caused by you did not cleanup your packer cache?

**Comment by JuniorSuperTux** [comment]
Sorry for your inconvenience. It turns out to just be me not putting those in the correct setup function call. Nice plugin btw
