### ISSUE TITLE
Can't Change Clangd Calling Command

### ISSUE THREAD

**Issue by JuniorSuperTux** [ray-x/navigator.lua#101]
I'm trying to enable some clang-tidy checkers, but it doesn't seem to work after adding the required arguments to the custom config. The following is the configuration file:
```lua
require('navigator').setup({
    lsp_installer = true,
    default_mapping = false,
    treesitter_analysis = true,
    transparency = 90,
    icons = {
        diagnostic_err = "", 
        diagnostic_warn = "",
        diagnostic_info = "", 
        diagnostic_hint = "ﯦ",
        diagnostic_virtual_text = ""
    },
    lsp = {
        format_on_save = false,
        diagnostic_scroll_bar_sign = nil,
        diagnostic_update_in_insert = true,
        disply_diagnostic_qf = true,
        clangd = {
            cmd = {
                "clangd", "--background-index", "--clang-tidy", "--clang-tidy-checks=-*,llvm-*,clang-analyzer-*", "--header-insertion=iwyu", "--cross-file-rename"
            },
        }
    },
})
```
Also forgot to mention that disabling the scroll bar sign (setting it to `nil`) doesn't seem to work. I decided to disable it because it's a little bit glitching, but I still see it after having it disabled.
The arguments I added have been tested on coc.nvim for myself, and it seems to work. This is what happens with coc.nvim:
![image](https://user-images.githubusercontent.com/65844719/142764631-828bd3d0-9e0d-4037-97d0-9b7e737e2a78.png)
And when using nvim-lsp setted up with navigator with the same arguments:
![image](https://user-images.githubusercontent.com/65844719/142764680-768d344e-47ce-418d-8193-727223eb62ef.png)
Errors that are shown with the default configuration are there, though.

**Comment by ray-x** [comment]
Anyway I can check the arguments works or not from command line?
I printed out the logs from clangd lsp. Nothing related to namespace
If I run
```
clangd --clang-tidy --clang-tidy-checks='-*,llvm-*,clang-analyzer-*'
```

There is an error/warning

```
The flag `-clang-tidy-checks` is obsolete and ignored.
```

**Comment by JuniorSuperTux** [comment]
The command and the arguments works with no errors/warnings on my side, here's the output when I issue the command:
![Screenshot_20211122_194730](https://user-images.githubusercontent.com/65844719/142856589-18a2538b-4c3a-4e37-b69c-efbe63b5cdf3.png)
Also something that I didn't point out on the first comment. Through some observations, I can see that the default clangd settings aren't applied. For example, the default configuration has a flag `--header-insertion=iwyu` which makes automatic header insertion only apply on non recursively or directly included headers. Every suggestions that I apply from the nvim-cmp choices triggers the header insertion. I'm not sure about other language servers, but that's what happened on me.

**Comment by ray-x** [comment]
It seems I am using clangd 13.0 for testing, as version 13 had been release for about 1 year, could you update your clang version as well?

**Comment by JuniorSuperTux** [comment]
![image](https://user-images.githubusercontent.com/65844719/143026545-549d057a-c5a4-4aff-b73b-b0ddd554d369.png)
I just updated to clangd 13.0, and also removed the ignored parameters. Above is the result when I typed `:LspLog`, and it seems like that `clangd` is called without the arguments

**Comment by ray-x** [comment]
I think the issue is `lsp_installer = true,`
That means `lsp_installer` will be fully responsive for lsp setup and config. Please set it to false and put metals to PATH and it should work.

**Comment by JuniorSuperTux** [comment]
Yes, this does seem to fix the issue. Can you also merge the lsp_installer server setup to the navigator setup when `lsp_installer = true` is set?

**Comment by ray-x** [comment]
Sorry, I can't. There was a time I track their changes but I find it takes me too much time.
I would suggest either: 
1) setup up your options to clangd in lsp_installer.
2) set lsp_installer=false and pass lsp_navigator the path of clangd in setup lsp_navigator.

**Comment by ray-x** [comment]
The behavior is as designed
