### ISSUE TITLE
Issue reference to commands as gi connected with lsp

### ISSUE THREAD

**Issue by mkubasz** [ray-x/navigator.lua#104]
After installation I found issue, I don't find any solution for is. Maybe this is appearing for some one else.
![2021-11-25_00-38_1](https://user-images.githubusercontent.com/1952619/143326122-6b2cd55a-db24-421e-9522-cecb1aa4523a.png)
![2021-11-25_00-39](https://user-images.githubusercontent.com/1952619/143326126-33c72ba9-b1cc-4b20-9722-ffdaf177b93b.png)

This shows in all languages.
My lsp settings
https://gist.github.com/mkubasz/108e78010607d18d5072f1e362347d78

Logs:
[gh.log](https://github.com/ray-x/navigator.lua/files/7599218/gh.log)

**Comment by ray-x** [comment]
The setup is not correct
should be
```
require'navigator'.setup({
    lsp={
        disable_lsp = {'tsserver','pyright'},
    }
    debug = false
})
```

You can double check that you have multiple LSP enabled by run `LspInfo`

**Comment by mkubasz** [comment]
@ray-x Thanks!!! And this mean that navigator will be disabled for this two lsps? Or there is a possibility to use navigator with own settings? Like with `vim.cmd("autocmd FileType guihua tsserver require('cmp').setup.buffer { enabled = false }") ?
`

**Comment by ray-x** [comment]
```
{lsp={ disable_lsp = {'tsserver','pyright'}} }
```
This will disable tsserver and pyright
You can have your own settings, e.g
```
{
lsp = {
  gopls = {
    on_attach = function(client)
      print("gopls attached")
      client.resolved_capabilities.document_formatting = false -- efm
    end,
   cmd = {
     "gopls", -- share the gopls instance if there is one already
     "-remote=auto",
     "-logfile=auto",
     "-rpc.trace",
   },

   settings = {
     gopls = {gofumpt = true} -- enable gofumpt etc,
   }
  },
}
}
```

**Comment by mkubasz** [comment]
Thanks :)
