### ISSUE TITLE
[Bug] Keys are not valid.

### ISSUE THREAD

**Issue by chriztheanvill** [ray-x/navigator.lua#105]
Hi. With the new update I have problems with mapping:

![image](https://user-images.githubusercontent.com/37992958/143402592-e779d2dd-ac2b-4e1c-84d5-907369fa1f2b.png)
![image](https://user-images.githubusercontent.com/37992958/143402686-b81e2a29-9b77-4885-91af-b88a46dbd75e.png)

Also, with the servers like: Cmake and gdscript, shows also a message with errors.

**Comment by ray-x** [comment]
Cmake and gdscript are not support by default. You can extend the list but I have never test.

Keymap should be fixed. Thanks for reporting.

**Comment by chriztheanvill** [comment]
Thank you, the new update fix it.
