### ISSUE TITLE
How to add support for additional lsp server.

### ISSUE THREAD

**Issue by ThilinaTLM** [ray-x/navigator.lua#109]
Thanks for great work!

How to extends support for other language servers such as `cmake`, `ltex`.
I have added the configuration for `ltex` in `navigator` setup but it seems to be that code-actions and other things are not working.

[Nvim lspconfig ltex](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ltex)

Thanks!

>**My Setup**:
>OS             Manjaro Linux
>Kernel        5.14.18-1-MANJARO
>Neovim     0.6

**Comment by ray-x** [comment]
You can check this PR on how to add a new lsp:
https://github.com/ray-x/navigator.lua/pull/107

But it can be simply put the lsp name in the list here:

https://github.com/ray-x/navigator.lua/blob/9aec552ac16206f57cd25aa3b0dfaed74bb0105f/lua/navigator/lspclient/clients.lua#L275-L281

e.g. add `cmake` and `ltex` to end of the array.  When navigator startup, it will load default setup for you.

Also I just submit some code to allow you add servers. Please check readme
https://github.com/ray-x/navigator.lua#add-your-own-servers

Would be great you can run some tests and create a PR.  Thanks!

**Comment by ThilinaTLM** [comment]
Thank you!

> Would be great you can run some tests and create a PR. Thanks!

Sure, I will.
