### ISSUE TITLE
Rust lifetimes break highlighting in list view

### ISSUE THREAD

**Issue by dm19** [ray-x/navigator.lua#11]
Rust uses a single  `'` to signify lifetime names and list view highlights everything between two lifetimes as a string (the block of yellow text in the screenshot from `vim.lsp.buf.document_symbol()`).

![Screenshot_20210608_143526](https://user-images.githubusercontent.com/31514792/121239153-daeb3880-c866-11eb-9b5c-249d607d37d3.png)

**Comment by ray-x** [comment]
Should been fixed in latest version of guihua.lua. Please update your plugin

**Comment by dm19** [comment]
Looks good now; thank you!
