### ISSUE TITLE
[Bug] Stops showing the Diagnostic info (Hover).

### ISSUE THREAD

**Issue by chriztheanvill** [ray-x/navigator.lua#110]
Hi.
In C++, if you open a file, all works fine, but after a while, stops working the hover diagnostics.

The function: "require('navigator.diagnostics').show_diagnostics()" works normal.

**Comment by ray-x** [comment]
As diagnostic is slow for most lsp. It is only enabled in Normal mode and with a delay. (maybe 0.5s after normal mode)

**Comment by chriztheanvill** [comment]
Oh, in fact, when enter in "insert mode" then change to "normal mode", stops to showing diagnostics.

**Comment by ray-x** [comment]
Ctrl-C does not trigger InsertLeave so it will not trigger the autocmd to display/refresh diagnostics

**Comment by chriztheanvill** [comment]
Jajaja, sorry. My bad.
