### ISSUE TITLE
[Bug] C++ Type_definition()

### ISSUE THREAD

**Issue by chriztheanvill** [ray-x/navigator.lua#111]
Hi.
With C++, trying to use vim.lsp.buf.type_definition() shows this error:

![image](https://user-images.githubusercontent.com/37992958/143658731-d1945ceb-35d0-45f7-8011-8f1722d00b41.png)

**Comment by ray-x** [comment]
Yes. it is expected. clang does not support typeDefinition request, use definition request instead.

**Comment by chriztheanvill** [comment]
Perfect.
