### ISSUE TITLE
should backspace work on floating window?

### ISSUE THREAD

**Issue by sagarc03** [ray-x/navigator.lua#114]
![Screenshot_2021-12-04_23-43-57](https://user-images.githubusercontent.com/25496917/144734030-f34547b1-b0de-4792-94c3-f5e823da91aa.png)

the example is  trying to list "document symbol"

using backspace does nothing.

**Comment by ray-x** [comment]
Could you check what <BS> was mapped to
It should mapped to `ListViewCtrl:on_backspace()`

**Comment by sagarc03** [comment]
```
i  <BS>        *@v:lua.MPairs.autopairs_bs(15)
	Last set from anonymous :source
i  <PageDown>   @<Cmd> lua ListViewCtrl:on_pagedown()<CR>
i  <PageUp>     @<Cmd> lua ListViewCtrl:on_pageup()<CR>
i  <Down>       @<Cmd> lua ListViewCtrl:on_next()<CR>
i  <Up>         @<Cmd> lua ListViewCtrl:on_prev()<CR>
i  <C-B>        @<Cmd> lua ListViewCtrl:on_pageup()<CR>
i  <C-E>        @<Cmd> lua ListView.close() <CR>
i  <C-F>        @<Cmd> lua ListViewCtrl:on_pagedown()<CR>
i  <CR>         @<Cmd> lua ListViewCtrl:on_confirm() <CR>
i  <C-N>        @<Cmd> lua ListViewCtrl:on_next()<CR>
i  <C-O>        @<Cmd> lua ListViewCtrl:on_confirm()<CR>
i  <C-P>        @<Cmd> lua ListViewCtrl:on_prev()<CR>
i  <C-W>        @<Cmd> lua ListViewCtrl:on_backspace(true) <CR>
```
is the interaction with auto pair a problem?

**Comment by sagarc03** [comment]
Ok so i confirm that the remapping of BS by auto-pairs plugin was the problem. For people who come across the similar problem, if the any of ur plugin is causing a remap issue make sure u ignore `guihua` file type or `prompt` buftype

 @ray-x thank you for the work you have put into this.

this issue can be closed.

**Comment by ray-x** [comment]
You need disable autopair for filetype `guihua`
