### ISSUE TITLE
[Bug] vim.schedule lua challback ... attempt to get length of local line (a nil value)

### ISSUE THREAD

**Issue by chriztheanvill** [ray-x/navigator.lua#115]
Hi.
After update navigator, then start using neovim, switching between tabs, I get this message:
![image](https://user-images.githubusercontent.com/37992958/145658809-859ec122-fcc6-41e5-b2a7-fff7b16be178.png)

**Comment by ray-x** [comment]
Did not see a similar issue so far. Pushed some updates and may help.

**Comment by chriztheanvill** [comment]
> Did not see a similar issue so far. Pushed some updates and may help. If you still seeing this issue, please send the neovim version, language server and basic steps to reproduce. Thanks!

Yes still happening, I noticed it happens when switch between tabs but it is highlighted "case" from a "switch" in C++.
![image](https://user-images.githubusercontent.com/37992958/145693501-33548465-2324-481b-aa8b-85a4b00808e4.png)

![image](https://user-images.githubusercontent.com/37992958/145693507-3f9302e7-a82e-4421-88e7-1753d69b1df0.png)

Update:
I found the problem, the thing is I copy paste my lsp config to navigator. So commented some part and, looks like it works.

---- My config: ---
```lua
on_attach = function(client, bufnr)
       -- your hook

		  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
		  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

		  -- Enable completion triggered by <c-x><c-o>
		  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

		  -- Mappings.
		  local opts = { noremap=true, silent=true }
		--	This.
		if client.resolved_capabilities.document_highlight then
			  vim.api.nvim_exec([[
			  "" Just adding collor highlight.
			   :hi LspReferenceRead cterm=bold ctermbg=red guibg=#505050
			   :hi LspReferenceText cterm=bold ctermbg=red guibg=#505050
			   :hi LspReferenceWrite cterm=bold ctermbg=red guibg=#505050
			":hi default GHTextViewDark guifg=#8b8b8b guibg=#505050
			":hi default GHListDark guifg=#8b8b8b guibg=#505050
			":hi default GHListHl guifg=#8b8b8b guibg=#505050
                        " ---- Updated
			"	 augroup lsp_document_highlight
			"	  autocmd! * <buffer>
			"	  autocmd CursorHold  <buffer> lua vim.lsp.buf.document_highlight()
			"	  autocmd CursorHoldI <buffer> lua vim.lsp.buf.document_highlight()
			"	  autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
			"	  " autocmd CursorHold *.* :lua vim.lsp.diagnostic.show_line_diagnostics()
			"	  autocmd CursorHold,CursorHoldI * lua vim.lsp.diagnostic.show_line_diagnostics({focusable=false})
			"	  autocmd BufWritePre * lua vim.lsp.buf.formatting_sync(nil, 300)
			"	 augroup END
                        " ---- Updated
			  ]], false )
		--	else
		--		  vim.api.nvim_exec([[
		--			  autocmd!
		--			  autocmd BufWritePre * Neoformat
		--			  augroup END
		--		  ]], false)
		end


     end,

```

**Comment by ray-x** [comment]
In navigator, the CursorHold was mapped to `document_highlight` by default. If it mapped multiple times and the function was called multiple times. it may have side effects and fail to work.
