### ISSUE TITLE
In python gr throws an index field _viewctlobject error

### ISSUE THREAD

**Issue by cj** [ray-x/navigator.lua#124]
When using python and [gr](https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/mapping.lua#L15) I get the following error:

![c4db0c13-a503-4f5a-8699-e2d6e8cf9d82](https://user-images.githubusercontent.com/1819/147618243-c2e3b6c3-9a83-464d-b64a-1f27702f07fc.jpg)

```log
[string ":lua"]:1: in main chunk
E5108: Error executing lua ...pack/packer/start/guihua.lua/lua/guihua/listviewctrl.lua:529: attempt to index field '_viewctlobject' (a nil value)
stack traceback:
        ...pack/packer/start/guihua.lua/lua/guihua/listviewctrl.lua:529: in function 'on_close'
```

**Comment by ray-x** [comment]
Is it caused by multiple python lsp installed?

**Comment by cj** [comment]
@ray-x I think that was the issue.  Isn't `disable_lsp = {'pylsp'},` supposed to turn off `pylsp`?

**Comment by cj** [comment]
@ray-x the other thing I have noticed is some language servers are better than others on certain things.  For example, I want the diagnostics of both pyright and pylsp, but when I do `require('navigator.reference').reference()` I want that to use just pyright.  Is that currently possible?

**Comment by ray-x** [comment]
Yes, disable_lsp should disable the lsp listed.
In theory, you can have multiple lsp while only one of them sending back reference() by disabling the lsp capacities. But I never tried that.

**Comment by ray-x** [comment]
I pushed a change so it wont pop up multi listview. Hope it works for you.
