### ISSUE TITLE
"lua require('navigator.workspace').workspace_symbol()" raises errors when symbol not found

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#126]
Neovim: 0.6.1 stable.

Open any source file, execute `lua require('navigator.workspace').workspace_symbol()`, input any symbol name not exist actually, press <kbd>Enter</kbd>, the follow errors are raised:

![image](https://user-images.githubusercontent.com/33576822/147928395-c62c055e-934d-417c-ab50-a4d3c6c23d22.png)

**Comment by ray-x** [comment]
Thanks. it should be fixed. Please update to latest version.

**Comment by spindensity** [comment]
> Thanks. it should be fixed. Please update to latest version.

The bug has been fixed. Now when the symbol is not found the message printed is something like this:

![image](https://user-images.githubusercontent.com/33576822/148021288-ec52cce6-d97c-4264-be0c-a9ef14e9e4f5.png)

The function of `lua require('navigator.workspace').workspace_symbol()`  is to search a symbol in the current workspace, not just the current buffer, so could you please show a message simply like `Symbol not found in the current workspace: afdslfjd`, or just `Symbol not found in the current workspace`?

Thanks.

**Comment by ray-x** [comment]
Pushed another update for the message.

**Comment by ray-x** [comment]
@spindensity Could you verify the fix?
