### ISSUE TITLE
"lua require('navigator.codeAction').code_action()" raises errors with sumneko_lua server

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#127]
Neovim: 0.6.1.

Open a lua source file, put the cursor in any line with some code actions, execute `lua require('navigator.codeAction').code_action()`, the following errors are raised:

![image](https://user-images.githubusercontent.com/33576822/147929720-c3ce24a4-4fbf-41b9-8f1f-16e1d8fcd6a3.png)

**Comment by ray-x** [comment]
Thanks, should been fixed. Please update guihua.lua.

**Comment by spindensity** [comment]
I can confirm it has been fixed, thanks.
