### ISSUE TITLE
Other than gd, all other shortcut keys aren't working for me

### ISSUE THREAD

**Issue by tonyma** [ray-x/navigator.lua#130]
Environment detail:

> System: macOS Monterey version 12.1
> Chip Apple M1 Max
> NVIM v0.6.0 (via brew install)
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by brew@HMBRW-A-001-M1-004.local

gd worked for me but all other shortcut keys aren't working for me.

Here are my configures:
init.lua: https://github.com/tonyma/dotfiles/blob/main/nvim/.config/nvim/init.lua
plugin: https://github.com/tonyma/dotfiles/blob/main/nvim/.config/nvim/lua/plugins.lua
navigator config (mostly default configure copied from this repo): https://github.com/tonyma/dotfiles/blob/main/nvim/.config/nvim/lua/config/navigator.lua

I also tried with the minimal sample configuration in the playground folder but got the same result.
When I press gr, it triggers the native vim replace character command. Let me know if more details I can provide.

**Comment by ray-x** [comment]
I downloaded your config. One issue I saw is `require("config.impatient")` It through lots of errors even without navigator.
After I disable impatient, every thing looks fine.

If you still failed to map. Please run `LspKeymaps` and check if navigator loaded or not

**Comment by ray-x** [comment]
Also check your output of `LspInfo` and make sure your lsp is installed and loaded.
If you using sumneko_lua, make sure `lua-language-server` is install in $PATH

**Comment by tonyma** [comment]
Here is the LspInfo output, I am testing with typescript:

```
 
 Language client log: /Users/tony/.cache/nvim/lsp.log
 Detected filetype:   typescript
 
 4 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [16])
 	filetypes:       javascript, markdown, typescriptreact, html, solidity, javascriptreact, graphql, css, json, yaml, less, typescript, scss, python, lua
 	autostart:       false
 	root directory:  /Users/tony/Desktop/Development/quadpay-merchant-portal
 	cmd:             nvim
 
 Client: cssmodules_ls (id: 2, pid: 70250, bufnr: [16])
 	filetypes:       javascript, javascriptreact, typescript, typescriptreact
 	autostart:       true
 	root directory:  /Users/tony/Desktop/Development/quadpay-merchant-portal
 	cmd:             cssmodules-language-server
 
 Client: eslint (id: 3, pid: 70251, bufnr: [16])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue
 	autostart:       true
 	root directory:  /Users/tony/Desktop/Development/quadpay-merchant-portal
 	cmd:             vscode-eslint-language-server --stdio
 
 Client: tsserver (id: 4, pid: 70252, bufnr: [16])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /Users/tony/Desktop/Development/quadpay-merchant-portal
 	cmd:             typescript-language-server --stdio
 
 Configured servers list: pylsp, bashls, dockerls, eslint, gopls, flow, julials, cmake, sqlls, sqls, rust_analyzer, terraformls, texlab, volar, vuels, html, sumneko_lua, vimls, yamlls, angularls, ccls, clangd, clojure_lsp, csharp_ls, cssls, cssmodules_ls, dartls, denols, dotls, r_language_server, fsautocomplete, svelte, phpactor, jdtls, jedi_language_server, intelephense, solargraph, kotlin_language_server, nimls, jsonls, omnisharp, tsserver, graphql, pyright


```

Got this error when run LspKeymaps:
![image](https://user-images.githubusercontent.com/4219509/148840287-021ebbed-2f95-477c-a95b-136fcf885d3d.png)

**Comment by ray-x** [comment]
Please update your plugin. The issue you saw should have been fixed.

**Comment by tonyma** [comment]
After I updated the plugins, I got this screen when run LspKeymaps:
![image](https://user-images.githubusercontent.com/4219509/148840843-0c733a7c-326f-4db2-9ed2-5cc21bf52065.png)

**Comment by tonyma** [comment]
I also tested with your minimal lua configure, it also didn't work for me. should I clean the packer site folder when testing with your minimal configure?

**Comment by ray-x** [comment]
It seems the setup function did not run.
What will happen if you run `lua require'navigator`.setup{}` and re-run `LspKeymaps`

**Comment by tonyma** [comment]
Got the same result after ran:
`lua require'navigator'.setup() `
`LspKeymaps`

**Comment by tonyma** [comment]
I added print message statement in to the navigator configure file. I can confirm the configure file is loaded and executed. 
```lua
local status_ok, navigator = pcall(require, "navigator")
if not status_ok then
	print("navigator is not loaded")
	return
end
print("navigator loaded")
```

![image](https://user-images.githubusercontent.com/4219509/148846459-8e1a0ab3-ee75-4286-8358-84364bd1877e.png)

**Comment by ray-x** [comment]
I saw the deprecated messages, so setup should have been run.
LspInfo looks fine as well.
I feel it something related to the impatient.nvim could you remove the plugin and clean up cache?

**Comment by tonyma** [comment]
after removing impatient.nvim, I am still getting the same result. gd worked but not other shortcut keys.

**Comment by ray-x** [comment]
I forked your repo https://github.com/ray-x/dotfiles-1 and did some updates.
It works fine in my environment 
Are you using window? which neovim version you are using?

**Comment by tonyma** [comment]
Environment detail:
```
System: macOS Monterey version 12.1
Chip Apple M1 Max
NVIM v0.6.0 (via brew install)
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by tonyma** [comment]
I am getting a quick-fix pane for the reference list is at the bottom of the window. shouldn't be a floating window?
is this expected behaviour for gr? 

![image](https://user-images.githubusercontent.com/4219509/148853374-77c4c2aa-6d07-4cba-b42e-6aba228627fa.png)

**Comment by tonyma** [comment]
I don't think it's working for me yet. I may re-visit it later and stick with my current configure for now. Thanks for your help.

**Comment by ray-x** [comment]
I am using Mac as well, but not sure if M1 work out of box (with ffi).
`gr` is a keymap to `lua require('navigator.reference').reference()`
So you can simply run `:lua require('navigator.reference').reference()` when cursor stop on a symbol.

**Comment by ray-x** [comment]
It seems to relate to a particular setup. As I can not reproduce, close it for now.

**Comment by magichan** [comment]
@ray-x   It seems that you don't set gd map in https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/mapping.lua#L15

I add `gd` into the costom keymap to solve the problem 
![image](https://user-images.githubusercontent.com/9430353/152643254-4a40607e-2bf0-47dd-9aa7-8ffe3d4665ba.png)

**Comment by Suyashtnt** [comment]
I am also having this issue

Config: https://github.com/Suyashtnt/nvim

**Comment by ray-x** [comment]
Is the lsp running in background?

**Comment by Suyashtnt** [comment]
> Is the lsp running in background?

yes

**Comment by Suyashtnt** [comment]
After some testing it does work, but the keybinds are not being registered

**Comment by Suyashtnt** [comment]
> I added codes to map `gd` in latest version. Hope it works for you

That did not fix the issue

**Comment by ray-x** [comment]
What is the output of `LspKeymaps`
Also if you run `lua require('navigator.definition').definition()` when your cursor is parking on a symble, is it works?

**Comment by ray-x** [comment]
There is no keymap bind for navigator. Seems navigator was not setup correctly. or you disable the keymaps by `default_mapping=false`
Did you try  minium vimrc `init.lua` in playground folder? `nvim -u init.lua`
Or can you share your minium vimrc?

**Comment by Suyashtnt** [comment]
> There is no keymap bind for navigator. Seems navigator was not setup correctly. or you disable the keymaps by `default_mapping=false`
> 
> Did you try  minium vimrc `init.lua` in playground folder? `nvim -u init.lua`
> 
> Or can you share your minium vimrc?

My current vimrc has very little customization but I'll work on a minimal one mimicking most of my setup

**Comment by Suyashtnt** [comment]
```lua
-- general setup
vim.api.nvim_set_keymap("n", " ", "", {})
vim.g.neovide_transparency = 0.8
vim.g.mapleader = " "

vim.wo.number = true
vim.wo.relativenumber = true
vim.opt.termguicolors = true
vim.opt.guifont = "JetBrainsMono Nerd Font Complete:h10"
vim.opt.clipboard = "unnamedplus"

vim.g.coq_settings = {
	["auto_start"] = "shut-up",
	["keymap"] = {
		["jump_to_mark"] = "null",
	},
}

-- packer
local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
	packer_bootstrap = fn.system({
		"git",
		"clone",
		"--depth",
		"1",
		"https://github.com/wbthomason/packer.nvim",
		install_path,
	})
end

require("packer").startup(function(use)
	use("neovim/nvim-lspconfig")
	use("williamboman/nvim-lsp-installer")
	use("ray-x/navigator.lua")

	-- -- COQ (Autocompletion)
	use("ms-jpq/coq_nvim")
	use("ms-jpq/coq.artifacts")
	use("ms-jpq/coq.thirdparty")

	if packer_bootstrap then
		require("packer").sync()
	end
end)

-- null ls setup
local nullls = require("null-ls")
local builtins = nullls.builtins

local function on_attach(client)
	if client.resolved_capabilities.document_formatting then
		vim.cmd([[augroup Format]])
		vim.cmd([[autocmd! * <buffer>]])
		vim.cmd([[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting()]])
		vim.cmd([[augroup END]])
	end
end

nullls.setup({
	sources = {
		builtins.formatting.stylua,
		builtins.diagnostics.eslint,
		builtins.formatting.eslint_d.with({
			filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue" },
		}),
		builtins.completion.spell,
	},

	on_attach = on_attach,
})

-- navigator/LSP setup
require("navigator").setup({
	lsp_installer = true,
})

local lsp_installer = require("nvim-lsp-installer")
local coq = require("coq")

local enhance_server_opts = {
	["sumneko_lua"] = function(options)
		options.settings = {
			Lua = {
				diagnostics = {
					globals = { "vim" },
				},
			},
		}
	end,
	["tsserver"] = function(options)
		options.on_attach = function(client)
			client.resolved_capabilities.document_formatting = false
		end
	end,
}

lsp_installer.on_server_ready(function(server)
	local options = {}

	if enhance_server_opts[server.name] then
		enhance_server_opts[server.name](options)
	end

	server:setup(coq.lsp_ensure_capabilities(options))
end)
```

this _should_ be the minimum init.lua file

**Comment by Suyashtnt** [comment]
@ray-x

**Comment by ray-x** [comment]
Your init.lua does not work for me. It was updated:
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
vim.g.coq_settings = {
  ['auto_start'] = 'shut-up',
}


local function load_plugins()
  require('packer').startup({
  function(use)
    use('wbthomason/packer.nvim')
    use('neovim/nvim-lspconfig')
    use('williamboman/nvim-lsp-installer')
    use('ray-x/navigator.lua')
    use('ray-x/guihua.lua')
    -- -- COQ (Autocompletion)
    use('ms-jpq/coq_nvim')
    use('ms-jpq/coq.artifacts')
    use('ms-jpq/coq.thirdparty')
  end,
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
  },
  })
    -- navigator/LSP setup
  require('navigator').setup({
    lsp_installer = true,
  })

  local lsp_installer = require('nvim-lsp-installer')
  local coq = require('coq')

  local enhance_server_opts = {
    ['sumneko_lua'] = function(options)
      options.settings = {
        Lua = {
          diagnostics = {
            globals = { 'vim' },
          },
        },
      }
    end,
    ['tsserver'] = function(options)
      options.on_attach = function(client)
        client.resolved_capabilities.document_formatting = false
      end
    end,
  }

  lsp_installer.on_server_ready(function(server)
    local options = {}

    if enhance_server_opts[server.name] then
      enhance_server_opts[server.name](options)
    end

    server:setup(coq.lsp_ensure_capabilities(options))
  end)
end


if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({
    'git',
    'clone',
    'https://github.com/wbthomason/packer.nvim',
    install_path,
  })
  load_plugins()
  require('packer').sync()
else
  load_plugins()
end

```

Update to the lastest it should works.

**Comment by Suyashtnt** [comment]
@ray-x after running a packersync with my current setup it still did not work

**Comment by Suyashtnt** [comment]
check out my full config at https://github.com/Suyashtnt/nvim

**Comment by ray-x** [comment]
Sorry. I can not use your setup as it will blow up mine. How about the [init.lua](https://github.com/ray-x/navigator.lua/blob/master/playground/README.md)

**Comment by ray-x** [comment]
@Suyashtnt  looking into your setup
```
	["sumneko_lua"] = function(options)
		options.settings = {
			Lua = {
				diagnostics = {
					globals = { "vim" },
				},
			},
		}
	end,
	["tsserver"] = function(options)
		options.on_attach = function(client)
			client.resolved_capabilities.document_formatting = false
		end
	end,
```
One different between lua server and tsserver is tsserver has an on_attach.
That might be why the mapping not working.
As lspinstaller will override the navigator on_attach depending on the sequence.

It would be good to do this:

```lua
	["sumneko_lua"] = function(options)
                options.on_attach = function(client, bufnr)
                  require('navigator.lspclient.mapping').setup({
                    client = client,
                    bufnr = bufnr,
                    cap = capabilities,
                  })
		end
		options.settings = {
			Lua = {
				diagnostics = {
					globals = { "vim" },
				},
			},
		}
	end,
	["tsserver"] = function(options)
		options.on_attach = function(client, bufnr)
			client.resolved_capabilities.document_formatting = false
                        require('navigator.lspclient.mapping').setup({
                          client = client,
                          bufnr = bufnr,
                          cap = capabilities,
                        })
		end
	end,
```

**Comment by Suyashtnt** [comment]
> @Suyashtnt  looking into your setup
> 
> ```
> 
> 	["sumneko_lua"] = function(options)
> 
> 		options.settings = {
> 
> 			Lua = {
> 
> 				diagnostics = {
> 
> 					globals = { "vim" },
> 
> 				},
> 
> 			},
> 
> 		}
> 
> 	end,
> 
> 	["tsserver"] = function(options)
> 
> 		options.on_attach = function(client)
> 
> 			client.resolved_capabilities.document_formatting = false
> 
> 		end
> 
> 	end,
> 
> ```
> 
> One different between lua server and tsserver is tsserver has an on_attach.
> 
> That might be why the mapping not working.
> 
> As lspinstaller will override the navigator on_attach depending on the sequence.
> 
> 
> 
> It would be good to do this:
> 
> 
> 
> ```lua
> 
> 	["sumneko_lua"] = function(options)
> 
>                 options.on_attach = function(client, bufnr)
> 
>                   require('navigator.lspclient.mapping').setup({
> 
>                     client = client,
> 
>                     bufnr = bufnr,
> 
>                     cap = capabilities,
> 
>                   })
> 
> 		end
> 
> 		options.settings = {
> 
> 			Lua = {
> 
> 				diagnostics = {
> 
> 					globals = { "vim" },
> 
> 				},
> 
> 			},
> 
> 		}
> 
> 	end,
> 
> 	["tsserver"] = function(options)
> 
> 		options.on_attach = function(client, bufnr)
> 
> 			client.resolved_capabilities.document_formatting = false
> 
>                         require('navigator.lspclient.mapping').setup({
> 
>                           client = client,
> 
>                           bufnr = bufnr,
> 
>                           cap = capabilities,
> 
>                         })
> 
> 		end
> 
> 	end,
> 
> ```
> 
> 
> 
> 

I'll try this when I get home

**Comment by Suyashtnt** [comment]
@ray-x i forgot to say but it did indeed fix the issues. @tonyma check if this might be your issue
