### ISSUE TITLE
Wrong docs on move cursor to preview/list

### ISSUE THREAD

**Issue by fky2015** [ray-x/navigator.lua#132]
Code in `guihua.lua`:

https://github.com/ray-x/guihua.lua/blob/a6e6655b60f303dffc85fa70da02a23963f9b3b8/lua/guihua/listviewctrl.lua#L89

https://github.com/ray-x/guihua.lua/blob/a6e6655b60f303dffc85fa70da02a23963f9b3b8/lua/guihua/textviewctrl.lua#L37

Key mappings are contrary to the docs in the readme.

**Comment by fky2015** [comment]
My suggestion is to exchange the key mapping in `guihua.lua`

**Comment by ray-x** [comment]
Thanks, you are right. Updated
