### ISSUE TITLE
[Enhancement] Default mappings should be modified to not conflict with stock Neovim mappings

### ISSUE THREAD

**Issue by rnevius** [ray-x/navigator.lua#133]
It is my opinion that most mappings should be modified as to (1) not conflict with default Neovim mappings and (2) be more consistent.

For example, `gT` is a commonly-used command for navigating to a the previous tab page, or less importantly things like `<Ctrl-w>k` are often remapped by users to make moving between splits a bit faster. Regarding consistency, it's odd that some of the keypairs don't include the `<Leader>` and some include `<Space>` (which is often used as a leader).

I know these things can be remapped in our own configuration, but it would be great if the defaults of the plugin worked better out of the box. One solution would be to the [available, unused keypairs in normal mode](https://gist.github.com/romainl/1f93db9dc976ba851bbb), or (even better) prefix all of them with `<Leader>`. 

Last – but not least – I want to say THANK YOU for your work on the plugin.

**Comment by ray-x** [comment]
Thanks for the suggestions
I have changed the gT map to \<Leader>gt

As for <C-w>k/j that is on purpose so the behavior is consistent in list/detail view and vim split view.  Also those key only mapped to list/detail view buffers(guihua buffers) and will not prevent you navigate through splits in other buffers.

All the key maps with \<space> are from https://github.com/neovim/nvim-lspconfig keymap sections and I keep those maps so users can adapt the plugin more easily.

**Comment by rnevius** [comment]
Thanks! And interesting about `<C-k>`. After installing this plugin, with a horizontal split, I'm currently unable to jump from a bottom split to the top split with `<C-k>`. Instead, I get "no signature help available". Here's my mapping:

    nnoremap <C-k> <C-w>k

I'll keep looking into my own config to see if there's a problem elsewhere.

**Comment by ray-x** [comment]
https://github.com/neovim/nvim-lspconfig#keybindings-and-completion
The \<C-k> is mapped to signature help

**Comment by ray-x** [comment]
BTW, You can run `LspKeymaps` to show all lsp/navigator related keymaps.

**Comment by renkam** [comment]
Mapping with `<space>` mess up all my flow with easy motion which I use a lot.
Is there a way to change those without the need to repeat all from `navigator.lua/lua/navigator/lspclient/mapping.lua` with also setting `default_mapping` to `true`?

**Comment by ray-x** [comment]
Yes, 
You can override a specific function with this:
```lua
require'navigator'.setup({
  keymaps = {{key = "gK", func = "declaration()"}}, -- a list of key maps
}
```

Check `lua/navigator/lspclient/mapping.lua` for more details.

**Comment by renkam** [comment]
Looks like I didn't see the comment in example configuration. Wish it was more visible in the readme that using `keymaps` will override the defaults.

**Comment by rnevius** [comment]
The following mapping also conflicts with `G` for jumping to the bottom of the buffer (there's a pause as Neovim waits for another key to be pressed):

    { key = 'Gr', func = "require('navigator.reference').async_ref()" },

**Comment by ray-x** [comment]
Gr will deprecate and async_ref will be the default reference search
