### ISSUE TITLE
icon = diagnostic_virtual_text not working 

### ISSUE THREAD

**Issue by shendypratamaa** [ray-x/navigator.lua#134]
![Screenshot 2022-01-13 at 02 24 47](https://user-images.githubusercontent.com/76093597/149208123-5e45784c-434e-4e4b-90cf-5cbc90c37768.png)

macos: 12.1
neovim: 0.6

another custom icon not working properly for me, as i mention for diagnostic_virtual_text when showing error on right side

**Comment by ray-x** [comment]
I think it is expected behaviour from null-ls
Here is an example, we do have both diag messages from null-ls and navigator.
![image](https://user-images.githubusercontent.com/1681295/149241514-ba680da0-ab1e-4b0c-b8bd-9844fcb6d820.png)

Null-ls plugin has its own way put to put virtual text. Could you check with the `init.lua` from playground dir to see if you still see this issue?

**Comment by shendypratamaa** [comment]
playground/init.lua
<img width="695" alt="Screenshot 2022-01-13 at 07 15 28" src="https://user-images.githubusercontent.com/76093597/149243693-bb231d78-01ee-4027-9811-737839199eec.png">

I try disable to from my init.lua
<img width="793" alt="Screenshot 2022-01-13 at 07 16 14" src="https://user-images.githubusercontent.com/76093597/149243717-bd662328-dea4-4bae-9452-c7b4c39336d6.png">

not at all actually, i change diagnostic_err working properly
<img width="597" alt="Screenshot 2022-01-13 at 07 26 26" src="https://user-images.githubusercontent.com/76093597/149244202-1a05c271-e40d-4e01-84d1-864932278f4f.png">
e

**Comment by shendypratamaa** [comment]
woops, sorry 😅
![Screenshot 2022-01-13 at 07 56 01](https://user-images.githubusercontent.com/76093597/149246700-ba322348-2bff-4433-9ebb-d7ddbed08457.png)

**Comment by ray-x** [comment]
That is expected. When you launch the nvim for the first time,  press `Enter` to install all plugins. When packer finished, relaunch nvim with `nvim -u playground/init.lua your_sourc_code`. That will enable all plugins.

**Comment by shendypratamaa** [comment]
result after press enter to continue

![Screenshot 2022-01-13 at 09 51 34](https://user-images.githubusercontent.com/76093597/149257259-52339fa9-f1c8-4987-a683-370701bc5999.png)

i dont have packer actually, but maybe after running this `nvim -u playground/init.lua my_source_code` missing plugin can installed ? sorry i'm newbie 😅

**Comment by ray-x** [comment]
`init.lua` will install packer and all the plugins in `init.lua` 
You can check the codes in playground `go`, `js`, `py` path, assuming you install corespondent LSP.
If you want to try with lua source code, make sure you install sumneko and check the setup for sumneko in `init.lua`
