### ISSUE TITLE
Clang lsp keybindings broken, error on startup

### ISSUE THREAD

**Issue by BeauSLM** [ray-x/navigator.lua#136]
Plugin doesn't map lsp bindings when using clang (i.e. on c/c++ files). As far as I can tell, this only happens with clang. I tested other languages, and ccls, but clang was the only one with this issue.

I'm using neovim on the latest master at the time of this issue's posting.

Steps to reproduce:
1. use minimal init.vim (the one from this project's readme aka the one below for example)
2. Ensure clang is installed
3. Open any c/c++ file

An error comes up on startup, and it appears that no keybinds are set by the plugin.

![image](https://user-images.githubusercontent.com/63375392/149708190-7177a140-6fbf-4c80-b334-3687a484ed48.png)

 
```vim
call plug#begin('~/.vim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'ray-x/guihua.lua', {'do': 'cd lua/fzy && make' }
Plug 'ray-x/navigator.lua'

" Plug 'hrsh7th/nvim-cmp' and other plugins you commenly use...

" optional, if you need treesitter symbol support
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

call plug#end()

" No need for require('lspconfig'), navigator will configure it for you
lua <<EOF
require'navigator'.setup()
EOF```

**Comment by ray-x** [comment]
It seems that clangd failed to send the current buffer number.
This is an upstream issue. I can add a workaround, but the bufnr is used in on_attach for tracking diagnostic. It will affect the plugin with workaround.

**Comment by BeauSLM** [comment]
Much thanks, hopefully everything gets sorted out.

**Comment by sbmueller** [comment]
@ray-x I'm getting a `no bufnr provided by LSP` every time I open a file now, is this related and an issue? I'm using clangd-12.
