### ISSUE TITLE
broken after update

### ISSUE THREAD

**Issue by shendypratamaa** [ray-x/navigator.lua#138]
<img width="1207" alt="Screenshot 2022-01-19 at 11 22 05" src="https://user-images.githubusercontent.com/76093597/150063661-3718ed86-3b41-448f-aaf4-1e5ae84f7050.png">

i misunderstod about this err, but after update navigator, and treesitter, i got error like this

**Comment by ray-x** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/2295
Seems to be an upstream issue.

**Comment by shendypratamaa** [comment]
great, thanks @ray-x for helping me
