### ISSUE TITLE
can i overrides key gh_jump_to_(preview/list) from guihua ?

### ISSUE THREAD

**Issue by shendypratamaa** [ray-x/navigator.lua#139]
hi @ray-x can i overrides keymap from guihua, default `<c-j> gh_jump_to_preview() <c-w>k gh_jump_to_list()`, for jump floating window list to preview, sometimes when im press default keymap, im going jump to outside floating window, and i must click the floating window again if i want to close it, i think this is conflict with my default setting for navigate to another splitpane using `<c-w>? - hjkl`

**Comment by ray-x** [comment]
You are right. I am re-use <c-w> so the behaviour will be similar if you are using split. 
It was hard coded atm. If you want to unmap it, you have to do it in filetype event autocommand to unmap and remap to new keymaps.

**Comment by shendypratamaa** [comment]
thanks to explanation @ray-x , i will try to remap and unmap with autocommand as suggest, but for now everything work fine with `<c-w>w` i can jump back to floating preview window,
