### ISSUE TITLE
require('navigator.diagnostics').show_buf_diagnostics() error when press <cr>

### ISSUE THREAD

**Issue by shendypratamaa** [ray-x/navigator.lua#140]
*navigator latest 
*guihua latest
*neovim 0.6.1

i have some issue with show_bug diagnostics(), when i try showing all error message with floating window navigator, and i want to jump to specific error i got error like this,

```
E5108: Error executing lua ...im/site/pack/packer/start/guihua.lua/lua/guihua/util.lua:271: Vim(edit):E37: No write since last change (add ! to override)
stack traceback:
        [C]: in function 'cmd'
        ...im/site/pack/packer/start/guihua.lua/lua/guihua/util.lua:271: in function 'open_file_at'
        ...vim/site/pack/packer/start/guihua.lua/lua/guihua/gui.lua:192: in function 'on_confirm'
        ...pack/packer/start/guihua.lua/lua/guihua/listviewctrl.lua:448: in function 'on_confirm'
        [string ":lua"]:1: in main chunk
```

**Comment by ray-x** [comment]
Failed to reproduce. Did you edit listview/preview?

**Comment by shendypratamaa** [comment]
i do not edit from plugins sources listview/preview, all based on plugins installer,

**Comment by ray-x** [comment]
Do you have a quick way for me to reproduce?
You minium vimrc, sample source code, operation system
