### ISSUE TITLE
navigator is not managing LSP servers

### ISSUE THREAD

**Issue by pard68** [ray-x/navigator.lua#144]
I had navigator working perfectly on another laptop, got a new job and a new work laptop, installed my nvim config and now navigator isn't working. I have a MBP running MacOS 12.2, Intel-chip. Neovim is v0.6.1 (the default Brew version w/ LuaJIT 2.1.0-beta3 compiled with +acl, +iconv, and +tui).

Here is the relevant part of my packer setup:
```
  -- LSP
  use {
    "neovim/nvim-lspconfig", -- Language Server Protocol stuff
    config = "require'lsp-config'",
    requires = {
      -- Language Server Protocol installer
      { "williamboman/nvim-lsp-installer", opt = false },
      -- Better quickfix and diagnostic window
      { "folke/trouble.nvim", opt = false },
      -- LSP powered function signatures
      { "ray-x/lsp_signature.nvim",  opt = false },
      { "glepnir/lspsaga.nvim",  opt = false },
    },
  }

  use { -- TODO: Figure out how to make this an optional plugin
    'ray-x/guihua.lua',
    run = 'cd lua/fzy && make'
  }
  use {
    "ray-x/navigator.lua", -- We use this to manage LSP setup
    -- config = "require'navigator-config'",
    -- requires = {'ray-x/guihua.lua', run = 'cd lua/fzy && make'},
    opt = false,
  }
```

And the relevant portion of my LSP/navigator setup:
```
function M.setup()
  require('navigator').setup({
    -- default_mapping = false,
    lsp_installer = true,
  })
  require('lsp_signature').setup()
  require('lspsaga').init_lsp_saga()
  setup_trouble()
end

M.setup()
```

I am using the [lsp-installer](https://github.com/williamboman/nvim-lsp-installer/) -- however I have also attempted to get navigator to work without the lsp-installer package. Neither way works.

I expected navigator to install my LSP servers for me, instead it's done nothing. I manually have installed some servers and a _few_ do work, including gopls and clangd. Most are not working at all. When I say not working the manually installed servers (through lsp-installer) are either not being picked up, like for sumenko_lua, or are not attaching to the client.

Any advice?

**Comment by ray-x** [comment]
I think it because of the $PATH setup.
Check this part:
https://github.com/ray-x/navigator.lua#integrat-with-lsp_installer-williambomannvim-lsp-installer

**Comment by realtica** [comment]
Same issue here for neovim 0.6.1, do not working with nvim-lsp-intaller

**Comment by ray-x** [comment]
Lsp installer does not install the servers in $PATH, you have to set it up explicitly.

**Comment by pard68** [comment]
Ah that would make sense.  I have that `lsp_servers` directory in my PATH, not sure why it would be that this was working on my old computer and not on this new one though. I'll poking away at it. Thanks for the help!

**Comment by pard68** [comment]
Any idea why it doesn't work without the nvim-lsp-installer? I'd be happy to drop it if I can get "it just works" functionality out of the box. Without it I don't have any servers installed at all though.

**Comment by ray-x** [comment]
I do not use lspinstaller. So I can only try my best.
1) Check the lsp you are using is in PATH, e.g. ccls, try `:!ccls` in command mode inside vim and see if the command can be executed
2) If you do setup path, you can also check https://github.com/ray-x/navigator.lua#integrat-with-lsp_installer-williambomannvim-lsp-installer. And as it depends on installer API, please check if the following command return the correct path
```
local path = require 'nvim-lsp-installer.path'
print(path.concat{vim.fn.stdpath 'data', 'lsp_servers'})
local  install_root_dir = path.concat{vim.fn.stdpath 'data', 'lsp_servers'}
last check in your setup, e.g with ccls:
```
ccls = {
      cmd = { install_root_dir .. '/cpp/ccls' }
    }
```

Feel free to comment on the README or provide your minium vimrc.




```

**Comment by realtica** [comment]
> I do not use lspinstaller. So I can only try my best.
> 
>     1. Check the lsp you are using is in PATH, e.g. ccls, try `:!ccls` in command mode inside vim and see if the command can be executed
> 
>     2. If you do setup path, you can also check https://github.com/ray-x/navigator.lua#integrat-with-lsp_installer-williambomannvim-lsp-installer. And as it depends on installer API, please check if the following command return the correct path
> 
> 
> ```
> local path = require 'nvim-lsp-installer.path'
> print(path.concat{vim.fn.stdpath 'data', 'lsp_servers'})
> local  install_root_dir = path.concat{vim.fn.stdpath 'data', 'lsp_servers'}
> ```
> 
> last check in your setup, e.g with ccls:
> 
> ```
> ccls = {
>       cmd = { install_root_dir .. '/cpp/ccls' }
>     }
> ```
> 
> Feel free to comment on the README or provide your minium vimrc.

Hello, rust_analyzer is in the $PATH I've checked into` :!echo $PATH` or `:echo $PATH`, but when execute `:!rust_analizer` I got "command not found". For apps outside nvim example` :!python --version`, works well.. :(

**Comment by ray-x** [comment]
Would be good to enforce the setup `cmd` to the following:
```
rust_analyzer = {
  cmd={rust_analyzer_full_path, argument}
}
```
For me, I installed rust_analyzer with brew/apt/yay so it is located in /usr/local/bin
the neovim lsp need to access rust_analysizer and startup the service with `cmd` setup. So if `:!rust_analyzer` failed, I think lua may also fail to launch it as well.
