### ISSUE TITLE
UI Customization compatibility

### ISSUE THREAD

**Issue by realtica** [ray-x/navigator.lua#145]
vim.diagnostic.config({
  virtual_text = false
})

This work fine when I remove navigator.lua
https://github.com/neovim/nvim-lspconfig/wiki/UI-customization

**Comment by ray-x** [comment]
It was enabled by default.
You can toggle the virtal text later on.
I can provide an option to disable it.

**Comment by realtica** [comment]
Sorry, with       
diagnostic_virtual_text = false,
is enough.
