### ISSUE TITLE
Default keymaps

### ISSUE THREAD

**Issue by realtica** [ray-x/navigator.lua#146]
Estrange behavior
```
mode | key | function
n | gd | definition  -----> only highlight the word
n | <C-LeftMouse> | definition  ------> works fine!
```
This happens in all languages, with navigator disabled, "gd" works fine too.

**Comment by ray-x** [comment]
It looks to me the lsp was not correctly loaded. Can you run LspInfo and check if it loaded?
by default `gd` is go_defination in neovim using tags.

**Comment by realtica** [comment]
There is a missunderstood

with navigator.lua:

mode | key | function
n | gd | definition -----> only highlight the word
n |<c> CLICK | definition ------> works fine ONLY WITH CTRL+CLICK!

without navigator.lua gd works fine.

**Comment by ray-x** [comment]
I think I made a mistake in keymap setup, would you check the latest version.
Also if it not working, could you send a screenshot of the result  `:LspKeymaps`

**Comment by ray-x** [comment]
@realtica Can you check if the latest version works for you?
