### ISSUE TITLE
Using The Default Lsp Config

### ISSUE THREAD

**Issue by AbbasSrour** [ray-x/navigator.lua#150]
Now I don't understand how this plugin works completely so excuse my ignorance, but if I want to keep my Lsp config separate from the navigator config, specifying only this in my navigator config 
`require("navigator").setup({
	debug = false, -- log output, set to true and log path: ~/.cache/nvim/gh.log
	width = 0.75, -- max width ratio (number of cols for the floating window) / (window width)
	height = 0.3, -- max list window height, 0.3 by default
	preview_height = 0.35, -- max height of preview windows
	border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" }, -- border style, can be one of 'none', 'single', 'double',
	-- 'shadow', or a list of chars which defines the border
})
`
Will this alter anything in my lsp config? Also what functionality will I lose (if any)?

**Comment by ray-x** [comment]
suppose you have your own config for pylsp, you can passed in to navigator.
```lua
pylsp_cfg ={youconfig}
require'navigator'.setup({
  lsp={
   pylsd=pylsp_cfg
  }
})

```

**Comment by ray-x** [comment]
If you have your own keymaps and other setups defined in on_attach, you can hook your on_attach in navigator config.
Also, you can move your key definition blocks to the `keymaps` field and it will override default maps.
One of my earlier goal for this plugin is help remove chunky lsp-config setup. In fact, you do not need to do much and the plugin will setup everything for you.

You can take a look of 
[attach.lua](https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/attach.lua)
[client.lua](https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/clients.lua)
And other files in lspclient folder.

**Comment by AbbasSrour** [comment]
Sorry forgot to close this, took a look and everything worked out thanks.
