### ISSUE TITLE
Not compatible with lsp-installer

### ISSUE THREAD

**Issue by xuliefeng** [ray-x/navigator.lua#151]
hi，i find navigator Not compatible with lsp-installer, still use navigator's default configuration. lsp_installer_servers only sees the allocation operation, but does not use it. Can you support, the information previously configured by lsp-installer cannot take effect

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/11550443/156614482-2920fe71-d09a-422b-aaad-bba94bb1f586.png">

**Comment by ray-x** [comment]
Do you have minium vimconfig?
You can start with the init.lua here https://github.com/ray-x/navigator.lua/blob/master/playground/init.lua

**Comment by xuliefeng** [comment]
Sorry, I didn't see the use of nvim-lsp-installer in your configuration. Maybe my understanding is wrong, please help me

**Comment by ray-x** [comment]
Your config looks fine. It will use navigator's default setup with lua server pointing to lsp_installer path.
If you want load lsp_installer's lsp setup
You have to do the setup in lsp_installer
something like this:

```lua
require("navigator").setup({
  lsp_installer = true,
})

local lsp_installer = require("nvim-lsp-installer")

local enhance_server_opts = {
  ["sumneko_lua"] = function(options)
    options.settings = {
      Lua = {
        diagnostics = {
          globals = { "vim" },
        },
      },
    }
  end,
  ["tsserver"] = function(options)
    options.on_attach = function(client)
      client.resolved_capabilities.document_formatting = false
    end
  end,
}

lsp_installer.on_server_ready(function(server)
  local options = {}

  if enhance_server_opts[server.name] then
    enhance_server_opts[server.name](options)
  end

end)
```

**Comment by xuliefeng** [comment]
Yes, I have set it. I found through the breakpoint that the navigator's config was loaded last, but the navigator only loaded the cmd settings of lsp-instanller without merging other configuration information.

this is my setting lsp-install

```lua
local lsp_installer = require("nvim-lsp-installer")

  lsp_installer.on_server_ready(
    function(server)
      local opts = make_config()

      -- (optional) Customize the options passed to the server
      -- if server.name == "tsserver" then
      --     opts.root_dir = function() ... end
      -- end

      local server_settings = settings[server.name]

      if server_settings ~= nil then
        if (opts.settings == nil) then
          opts.settings = server_settings
        else
          vim.tbl_extend("force", opts.settings, server_settings)
        end
      end

      -- This setup() function is exactly the same as lspconfig's setup function.
      -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
      server:setup(opts)
    end
  )
```

navigator load code

clients.lua  
```lua
    log("loading", lspclient, "name", lspconfig[lspclient].name, "has lspinst", has_lspinst)
    -- start up lsp
    if has_lspinst and _NgConfigValues.lsp_installer then
      local installed, installer_cfg = require("nvim-lsp-installer.servers").get_server(lspconfig[lspclient].name)

      log("lsp installer server config" .. lspconfig[lspclient].name, installer_cfg)
      if installed and installer_cfg then
        log("options", installer_cfg:get_default_options())
        -- if cfg.cmd / {lsp_server_name, arg} not present or lsp_server_name is not in PATH
        if vim.fn.empty(cfg.cmd) == 1 or vim.fn.executable(cfg.cmd[1] or "") == 0 then
          cfg.cmd = {installer_cfg.root_dir .. path_sep .. installer_cfg.name}
          log("update cmd", cfg.cmd)
        end
      end
    end
```

**Comment by ray-x** [comment]
The lsp config can take both a list or a function that return a config list. E.g for gopls

```lua
   cfg={lsp={}}
   cfg['lsp'].gopls = function()
      local go = pcall(require, "go")
      if go then
        local cfg = require("go.lsp").config()
        cfg.on_attach = function(client)
          client.resolved_capabilities.document_formatting = false -- efm/null-ls
        end
        return cfg
      else
        return {}
      end
    end

   require('navigator').setup(cfg)
```


If you want to merge the lsp_installer setup. You need to provide the config to navigator.
You can also use lsp_installer setup. Like this:
https://github.com/ray-x/navigator.lua/blob/master/playground/init_lsp_installer.lua

BTW, I do not think lsp_installer provides more config setup options other than the lspconfig default one.

**Comment by xuliefeng** [comment]
Okay, I see, lsp-installer is mainly to facilitate installation and execution of commands and the like. I add a method to read the lsp-installer configuration and assign it to the lsp configuration module of the navigator

Thanks for you answer
