### ISSUE TITLE
Keymaps not working. LspKeymaps shows empty list

### ISSUE THREAD

**Issue by lynndylanhurley** [ray-x/navigator.lua#154]
I'm trying to use the following keymap config:

```lua
keymaps = {
  { key = "gr", func = "require('navigator.reference').reference()" },
  { key = "gD", func = "declaration({ border = 'rounded', max_width = 80 })" },
  { key = 'gd', func = "require('navigator.definition').definition()" },
  { key = "ga", func = "code_action()" },
  { key = 'K', func = "hover({ popup_opts = { border = single, max_width = 80 }})" },
  { key = "gi", func = "implementation()" },
  { key = "<leader>d", func = "type_definition()" },
  { key = "gL", func = "require('navigator.diagnostics').show_diagnostics()" },
  { key = "gG", func = "require('navigator.diagnostics').show_buf_diagnostics()" },
  { key = "]d", func = "diagnostic.goto_next({ border = 'rounded', max_width = 80})" },
  { key = "[d", func = "diagnostic.goto_prev({ border = 'rounded', max_width = 80})" },
  { key = "]r", func = "require('navigator.treesitter').goto_next_usage()" },
  { key = "[r", func = "require('navigator.treesitter').goto_previous_usage()" },
  { key = '<leader>f', func = 'formatting()', mode='n' },
},
```

This used to work, but since I ran `PackerSync` the other day none of my `navigator` keymaps seem to be working anymore.

This is what I get when I run `LspKeymaps`:

<img width="1052" alt="Screen Shot 2022-03-09 at 10 46 01 AM" src="https://user-images.githubusercontent.com/468037/157489262-00dda124-a0bf-4b73-8d33-dff231518907.png">

When I run `LspInfo`:

<img width="1305" alt="Screen Shot 2022-03-09 at 10 46 27 AM" src="https://user-images.githubusercontent.com/468037/157489351-f9bb4f94-7d05-4d55-95ae-088af5b6871e.png">

From the 'which key' interface when I get `g`:

<img width="1501" alt="Screen Shot 2022-03-09 at 10 47 16 AM" src="https://user-images.githubusercontent.com/468037/157489497-d2b83a43-d233-4455-a319-0f7e5dc995f2.png">

^ in this case it's not showing entries for several maps. For example `gL`, `gG` are not there at all, and `gi` is still set to the default vim mapping.

Full neovim config here:
https://github.com/lynndylanhurley/nvim/blob/d02211f5bb4bda2d8d2a92718e4338105c2bf44c/lua/plugins/navigator.lua

**Comment by lynndylanhurley** [comment]
I have this working now. I think the lsp_installer example linked to from the readme may not be completely working. This code seems to need to be called by every server's `on_attach` callback:

```lua
require('navigator.lspclient.mapping').setup({
  client = client,
  bufnr = bufnr,
  cap = capabilities,
})
```

My full working config with lsp_installer integration is up here:
https://github.com/lynndylanhurley/nvim/blob/51d4372e13a38e2847654c45e9ea09a7c5afa405/lua/plugins/navigator.lua

**Comment by ray-x** [comment]
I am not sure if call map.setup() is the best way.
But I updated my sample vimrc for lsp_installer you can also take a look. https://github.com/ray-x/navigator.lua/blob/master/playground/init_lsp_installer.lua
