### ISSUE TITLE
New version of navigator will broke treesiter syntax.

### ISSUE THREAD

**Issue by mkubasz** [ray-x/navigator.lua#155]
After updating the navigator to the new version can't see syntax colors. When I don't use LSP.

NVIM v0.6.1

**Comment by ray-x** [comment]
Do you have a minium virmc? Also did you install treesitter parser?

**Comment by mkubasz** [comment]
@ray-x Yes, pure config doesn't work with a navigator.

**Comment by mkubasz** [comment]
```
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}
  use 'nvim-lua/plenary.nvim'
  use 'kyazdani42/nvim-web-devicons'

  -- Treesitter --
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate'
  }
  use 'nvim-treesitter/nvim-treesitter-refactor'

    -- LSP --
  use 'neovim/nvim-lspconfig'

  use {'ray-x/navigator.lua', requires = {'ray-x/guihua.lua', run = 'cd lua/fzy && make'}}

end)
require'navigator'.setup({})
```

**Comment by ray-x** [comment]
1) I suppose you installed the TS parser
2) syntax highlight in not included in your config. So the TS highlight is not working is an expected behavior 
3) I checked listing treesitter with minium config, it works fine.

**Comment by mkubasz** [comment]
@ray-x Syntax is enabled out of the box by neovim. Only navigator.lua change behavior of treesiter badly.

**Comment by ray-x** [comment]
It is not entirely true that neovim will enable ts automatically. You need to run treesitter setup and install the parser.
Here is a minium init.lua that works fine for me:

```
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

-- IMPORTANT: update the sumneko setup if you need lua language server
-- I installed it in '/github/sumneko/lua-language-server'
local sumneko_root_path = vim.fn.expand('$HOME') .. '/github/sumneko/lua-language-server'
local sumneko_binary = vim.fn.expand('$HOME') .. '/github/sumneko/lua-language-server/bin/macOS/lua-language-server'

local lua_cfg = {
  -- cmd = { sumneko_binary, '-E', sumneko_root_path .. '/main.lua' },
  settings = {
    Lua = {
      runtime = { version = 'LuaJIT', path = vim.split(package.path, ';') },
      diagnostics = { enable = true },
    },
  },
}

if vim.fn.executable('lua-language-server') == 0 then
  lua_cfg.cmd = { sumneko_binary, '-E', sumneko_root_path .. '/main.lua' }
end

local function load_plugins()
  require('packer').startup({
    function(use)
      use({ 'wbthomason/packer.nvim' })

      -- Treesitter --
      use({
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate',
        config = function()
          require('nvim-treesitter.configs').setup({
            ensure_installed = 'lua',
            sync_install = true,
            highlight = {
              enable = true,
              additional_vim_regex_highlighting = false,
            },
          })
        end,
      })
      -- LSP --
      use('neovim/nvim-lspconfig')

      use({
        'ray-x/navigator.lua',
        requires = { 'ray-x/guihua.lua', run = 'cd lua/fzy && make' },
        config = function()
          require('navigator').setup({
            debug = true,
          })
        end,
      })
      use({ 'ray-x/aurora' })
    end,
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({
    'git',
    'clone',
    'https://github.com/wbthomason/packer.nvim',
    install_path,
  })
  load_plugins()
  require('packer').sync()
  vim.cmd('colorscheme aurora')
else
  load_plugins()
  vim.cmd('colorscheme aurora')
end

```


Run neovim with `nvim -u init.lua init.lua` . The setup will help you install everything and restart neovim with `nvim -u init.lua init.lua`,  TS highlight should work.

**Comment by ray-x** [comment]
Is it happened randomly or each time a new file opened?

**Comment by mcginleyr1** [comment]
For me each file. It looks like the lsp setup isn't working

**Comment by mcginleyr1** [comment]
I commented out my own LSPconfig to leverage just navigators and it looks like none are being setup. LspInfo has 0 clients attached to buffer with no configured servers.

**Comment by ray-x** [comment]
Do you have a minimum setup I can reproduce?

**Comment by JuniorSuperTux** [comment]
It's happening to me too. It seems like it breaks nvim-treesitter once the setup function is called

**Comment by ray-x** [comment]
Do you have a config to reproduce? thanks!

**Comment by JuniorSuperTux** [comment]
The config to reproduce the situation is as simple as
```lua
require('navigator').setup{}
```

**Comment by ray-x** [comment]
I think this issue might be related to multiple plugins/setups. As it works fine for me with the default setup.
Please check the setups in `https://github.com/ray-x/navigator.lua/blob/master/playground/init.lua` if the config can reproduce highlight issue.

Thanks!

**Comment by ray-x** [comment]
My personal dotfile is lazyloading everything. And it does have some hack. But for navigator itself, it should not. But as I does not see it does mean it does not exist. I think it may be related to specific timing.
My personal sequence is 
```
load_scheme()
load('treesitter')
load('nvim-lspconfig')
load('guihua.lua')
load('navigator.lua')
```
