### ISSUE TITLE
Can't disable virutal text in the latest update

### ISSUE THREAD

**Issue by cj** [ray-x/navigator.lua#156]
It appears this line https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/diagnostics.lua#L330 conflicts with these lines https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/diagnostics.lua#L40-L43 and gives the following error `Error running config for navigator.lua: ...packer/start/navigator.lua/lua/navigator/diagnostics.lua:41: attempt to index field 'virtual_text' (a boolean value)`.  So there is no way to currently disable diagnostic text.

**Comment by ray-x** [comment]
@cj Could you check if the new version works?

**Comment by cj** [comment]
@ray-x it's working with the latest version.  Thank you!!
