### ISSUE TITLE
[Feature] Add an option to search the workspace symbols without filtering those with the initial popup

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#162]
Actually, when searching for workspace symbols, a small popup appears asking to digit part of the symbol name:

![image](https://user-images.githubusercontent.com/13739892/161570087-25823038-441b-4057-8d5c-fcff065e1931.png)

then the `navigator.lua` search results panel is shown, asking to filter the found items.

It would be nice to add an option to skip the original popup, which is not even fuzzy, and this would be quick and useful for projects which are not extremely big.

It would be best to filter all of the workspace symbols directly in the filterable preview panel.

**Comment by ray-x** [comment]
There is a new design for workspace symbole search
6e937e901909e1641aaba6451a5e915c4b551f54
