### ISSUE TITLE
[Bug] Wrong cursor position when jumping to references

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#165]
This happens with all of my installed LSP servers.

When jumping to definition, the cursor is correctly placed:

![image](https://user-images.githubusercontent.com/13739892/161923874-2e3d14a8-fa3d-4066-a6e3-fe1d5929c87a.png)

When jumping to references, the cursor is always placed one character before the proper position:

![image](https://user-images.githubusercontent.com/13739892/161923984-bd9855b4-f429-4307-9a91-51a798d1382f.png)

Other plugins such as `Telescope` and `Trouble` do not show this issue when navigating through reference results.

**Comment by pidgeon777** [comment]
This occurs only when navigating references, not definitions or call hierarchy.

**Comment by ray-x** [comment]
Should have been fixed

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1681295/178631227-8afbcbcb-f01f-4a61-9323-6a79d41e7437.png">
