### ISSUE TITLE
[Bug] Not all symbol references are shown in the preview window

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#166]
When looking for references, the preview window doesn't show all of them.

Apparently, it is limited to $21$ entries (excluding the rows of the reported files which contain those occurrences).

Tested with multiple LSPs.

**Comment by ray-x** [comment]
Added a fix from guihua

**Comment by ray-x** [comment]
@pidgeon777  could you check if the latest works for you?

**Comment by ray-x** [comment]
Should have been fixed.
