### ISSUE TITLE
[Bug] `ccls` call hierarchy not working anymore when starting other LSP in a different buffer

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#167]
These lines:

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L16

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L55

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L72

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L88

Should be changed to:

```lua
assert(#vim.tbl_keys(vim.lsp.buf_get_clients()) > 0, 'Must have a client running to use lsp_tags') 
```

otherwise, the number of LSPs attached to the buffer will be reported as `0` when starting another LSP server on a different buffer.

My modification has been tested and it always works. Some possible explanations:

https://github.com/ojroques/nvim-hardline/pull/31

https://github.com/neovim/neovim/issues/14618#issuecomment-846501540

Thus, `#vim.lsp.buf_get_clients()` returns `0` because of missing entries due to client IDs not being continuous (i.e. when starting new LSPs on new buffers).

Note: my counting method of the currently attached LSPs to a buffer is the same implemented here, which works:

https://github.com/neovim/nvim-lspconfig/blob/f183d35725264d6184146eebcef1ba8338ddbc83/lua/lspconfig/ui/lspinfo.lua#L155

**Comment by ray-x** [comment]
But with changes of 
https://github.com/ojroques/nvim-hardline/pull/31/files
The behaviour should be correct, right?

**Comment by pidgeon777** [comment]
Yes, that should fix the correct way to count the attached LSPs to the buffer (using `pairs` instead of `ipairs`).

**Comment by ray-x** [comment]
It should be fixed a while back
