### ISSUE TITLE
[Bug] Minor problem in `cclshierarchy.lua`

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#168]
This:

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L67

should be changed to:

```lua
gui.new_list_view({ items = results, ft = ft or 'cpp', api = ' ' })
```

as done here:

https://github.com/ray-x/navigator.lua/blob/d08d78f6a429ad14fafbee7fc5abf4b3b4b36888/lua/navigator/cclshierarchy.lua#L60

**Comment by ray-x** [comment]
should be fixed in the latest version
