### ISSUE TITLE
Unable to load a local module

### ISSUE THREAD

**Issue by KyleAMathews** [ray-x/navigator.lua#17]
I tried adding this plugin to work with my Typescript project and it seems to work within the local file but not between files. So showing references works for the file but every import has an error next to it saying it can't load a local module.

<img width="1215" alt="Screen Shot 2021-06-18 at 9 38 54 AM" src="https://user-images.githubusercontent.com/71047/122592368-074a4600-d019-11eb-813d-02ca6625a8a4.png">

I'm not sure where to begin debugging this. Is this an LSP issue? Treesitter? Running `:LspInfo` says somehow denols started running alongside the default Typescript language server but that wasn't happening earlier this week afaik.

**Comment by ray-x** [comment]
What's the default typesctipt LSP?

**Comment by ray-x** [comment]
If you mean tsserver. That is not a default typescript server (the naming is confusing).
Regarding the issue. 
1) The error is from LSP. As both tsserver and denols is active. You may need to check whether errors are from denols or tsserver. 
2) Both of the LSP servers may require "package.json" or "tsconfig.json" in the root folder. For deno, it may also requires import_map.json
3) You can disable either of them by setting the `filetype = {} ` 
e.g 
```
lsp = {
    tsserver = {
      filetypes = {} -- disable tsserver,
    },
}
```
And this will give you a better idea which LSP is not setup correctly.  I am using denols and did not see similar error messages.

**Comment by ray-x** [comment]
I can confirm the error messages are from denols
in deno, you need to specify the file extension when you import. 
So instead of 
import "../my_module"
you need 
import "../my_module.ts"

So deno and node project are not compatible. 


If your daily projects do not involve denols, I suggest you disable denols by:

lsp = {
    denols = {
      filetypes = {} -- disable tsserver,
    },
}

Or specify a root file for denols, e.g 
root_dir = root_pattern("denols.yaml")

**Comment by ray-x** [comment]
I re-enable tsserver. For those who need denols, will need to specify a root_parttern for deno project. Deno and node.js are not compatible so you have to choose only one of them.
