### ISSUE TITLE
[Bug] Lua error on startup (attempt to call field 'on_filetype' (a nil value))

### ISSUE THREAD

**Issue by pingiun** [ray-x/navigator.lua#170]
I get the following error on startup:

```
loading lsp config failed LSP may not working correctly
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'on_filetype' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

I have just started using neovim and have only two files configured:

```
; cat ~/.config/nvim/init.lua
require('plugins')
require('navigator').setup({
	debug = true,
})
; cat ~/.config/nvim/lua/plugins.lua
return require('packer').startup(function()
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'
  use {'ray-x/navigator.lua', requires = {'ray-x/guihua.lua', run = 'cd lua/fzy && make'}}
end)
```

**Comment by ray-x** [comment]
Could you check the setup `https://github.com/ray-x/navigator.lua/blob/master/playground/init.lua`
the on_filetype is here `autocmd FileType * lua require'navigator.lspclient.clients'.on_filetype()`.

**Comment by ray-x** [comment]
Seems the lspconfig is missing in the config. Please refer to https://github.com/ray-x/navigator.lua/blob/master/playground/init.lua for the minimum vimrc.
