### ISSUE TITLE
Error detected while processing FileType Autocommands for "*"

### ISSUE THREAD

**Issue by cova-fe** [ray-x/navigator.lua#175]
I'm getting this issue when starting lunarvim:

![image](https://user-images.githubusercontent.com/385249/164498601-2ac2d0d5-c47d-4c55-b87c-c2149bbbbb97.png)

referenced also https://github.com/LunarVim/LunarVim/issues/2496

Can someone help me? I tried, as suggested, to clear the cache but no changes

**Comment by ray-x** [comment]
I submit a fix for that. It may be related to lazy loading

**Comment by cova-fe** [comment]
I pulled last changes and indeed the issue seems to be fixed. Thanks!
