### ISSUE TITLE
[Question] How to enable codelens ?

### ISSUE THREAD

**Issue by 0x7a7a** [ray-x/navigator.lua#177]
I found that my GoTest files does not display codelens.  

So I tried to debug it,and add `require('navigator.codelens').setup()` in my config file.
Because I found that it was not called in `navigator.lua`

--- 
I found some errors, or maybe I'm not using the right method:  
- `_NgConfigValues` can't find  in `codelens.lua`, should I change it to `config` in line 16?
https://github.com/ray-x/navigator.lua/blob/9ceeb41b6f388a742df19b1e02e52f6e27f47811/lua/navigator/codelens.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L158

- After I tried to change this error mentioned above, a new error appeared, in 'utils.lua', also `_NgConfigValues` is nil
https://github.com/ray-x/navigator.lua/blob/9ceeb41b6f388a742df19b1e02e52f6e27f47811/lua/navigator/util.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L150

---
I need your help to enable codelens,thank you.
PS: I manually called `lua require('navigator.codelens').inline()` in `TestFunc` and it works fine

**Comment by ray-x** [comment]
The codelens setup will be called in lspclient->clients.lua->setup()
Normally the function is triggered when filetype is identified.
The only requirement is

```lua
 if _NgConfigValues.lsp.code_lens then
    require('navigator.codelens').setup()
 end
```

**Comment by 0x7a7a** [comment]
Thank you for your reply.
I found that in `navigator.lua` this is a value that defaults to false and cannot be configured.
https://github.com/ray-x/navigator.lua/blob/9ceeb41b6f388a742df19b1e02e52f6e27f47811/lua/navigator.lua#L61
So it can't enable without modifying the source code of the plugin

**Comment by 0x7a7a** [comment]
I have submitted a pull-request to try to fix this issue, please check #178

**Comment by ray-x** [comment]
I found there is miss match in the config
It should be 
```
 if _NgConfigValues.lsp.code_lens_action.enable then
    require('navigator.codelens').setup()
 end
```

**Comment by 0x7a7a** [comment]
I also think this is better, thank you for your work.
I will close this issue and pull-request
