### ISSUE TITLE
[Question] ccls call hierarchy support

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#18]
Does this plugin support incoming/outgoing call hierarchies when using ccls?

If not, is there any plan to support it? This would allow displaying call hierarchy for C/C++ code, too.

**Comment by ray-x** [comment]
I pushed an update to support it. Pls check

**Comment by pidgeon777** [comment]
You've been really fast! Ok I'll test it, right now I'm encountering some difficulties with your plugin config. I'll open a ticket.

**Comment by pidgeon777** [comment]
This is the issue which is actually blocking my further testings:

https://github.com/ray-x/navigator.lua/issues/19

**Comment by ray-x** [comment]
This one should have been fixed in the latest version. Please verify windows behaviour.
