### ISSUE TITLE
[Bug] Wrong usage of `vim.notify` in `attach.lua`

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#182]
This:

https://github.com/ray-x/navigator.lua/blob/77b572dd5a6e8140bc61f119f6b4bd83afc76cf8/lua/navigator/lspclient/attach.lua#L14

should be changed to:

`vim.notify('no bufnr provided from LSP ' .. client.name)`

otherwise `client.name` would be considered as a second argument of `vim.notify` function (i.e. log level), leading to an error.

**Comment by pidgeon777** [comment]
Also, I'm not sure about the meaningfulness of this code:

https://github.com/ray-x/navigator.lua/blob/77b572dd5a6e8140bc61f119f6b4bd83afc76cf8/lua/navigator/lspclient/attach.lua#L10-L16

I thought that `0` was used as an indicator of the current buffer, so I was wondering what that check in the `if` was meant for.

It leads to a `no bufnr provided from LSP clangd` every time `clangd` is used. Possibly related to this:

https://github.com/ray-x/navigator.lua/issues/157#issuecomment-1087313552

**Comment by ray-x** [comment]
You are correct that the notify usage is incorrect.
The on_attach should provide a valid bufnr. When not, the plugin will fallback bufnr to 0 to avoid errors.
So in this case, the upstream implementation of clanged may be faulty and failed to send bufnr through.
