### ISSUE TITLE
[Bug] `on_attach` of `clangd` LSP is missing `bufnr` argument in `clients.lua`

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#183]
https://github.com/ray-x/navigator.lua/blob/77b572dd5a6e8140bc61f119f6b4bd83afc76cf8/lua/navigator/lspclient/clients.lua#L175-L191

Line `187` is probably missing the `bufnr` argument.

When `clangd` LSP is attached for a buffer, a notification appears stating:

`no bufnr provided from LSP clangd`

This could be solved with this code:

```lua
    on_attach = function(client, bufnr)
      client.resolved_capabilities.document_formatting = true
      on_attach(client, bufnr)
    end,
```

**Comment by ray-x** [comment]
Thanks, should be fixed in the latest
