### ISSUE TITLE
navigator not working with nvim-lsp-installer

### ISSUE THREAD

**Issue by Zane-** [ray-x/navigator.lua#187]
Hello, I can't seem to make navigator work with [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer).

Here's my config:

```lua
require('nvm-lsp-installer').setup()

local capabilities = require('cmp_nvm_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require('navigator').setup({
  on_attach = function(client, bufnr)
    require('illuminate').on_attach(client)
    nmap_buf(bufnr, 'ca', '<cmd>CodeActionMenu<cr>')
  end,

  lsp_installer = true,

  lsp = {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  },
})
```

I have plenty of LSP servers installed via nvim-lsp-installer, but none are loaded when I open the corresponding filetype.

I looked into the code that loads the installed servers, and there's a line here:

```lua
local has_lspint, lspinst = pcall(require, 'lsp_installer')

if has_lspinst then
-- look at installed servers, setup lspconfig
end
```

I don't have the module `lsp_installer`, I verified this by trying to run the statement with `:lua`. Should this string not be `nvim-lsp-installer`?

Not sure if I'm missing some `$PATH` setup here or something.

**Comment by Zane-** [comment]
Nevermind I'm blind, missed the rest of the steps

**Comment by ray-x** [comment]
lsp-installer re-factor its folders structures and the setup no longer works. 
It is obviously that all `lsp-installer` moved to `nvim-lsp-installer`. I also received a PR that `go.nvim` need to update for lsp-installer.
I need run some tests and get a better understanding of how the API was chagnged.

**Comment by ray-x** [comment]
Did the issue solve?

**Comment by lyndhurst** [comment]
I think I have the same issue, I am just migrating from vim, so I only tried with `lua-language-server` so far.

I tried everything I could think of, find on the internet to set the path myself in navigator's `setup` function, nothing worked. At the end, I simply created a `lua-language-server` executable in my path pointing to the `nvim-lsp-installer` actual `lua-language-server` location, and everything seems to be working fine now.

I still wonder why I could not change the `lsp.sumneko_lua.cmd` in the config file to the full path of `nvim-lsp-installer` executable.

Thank you for your time.

**Comment by lyndhurst** [comment]
> I still wonder why I could not change the lsp.sumneko_lua.cmd in the config file to the full path of nvim-lsp-installer executable.

Sorry, my mistake I used shorthand path with `~/` instead of full absolute path. Pointing to the server as suggested in the README does work.
