### ISSUE TITLE
[Help] Integration with LunarVim

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#19]
In [LunarVim](https://github.com/ChristianChiarulli/LunarVim) LSP servers are configured this way:

- `config\lua\init.lua` (main initialization file):
````lua
    ...
    require('my-navigator-lua') -- Settings for `navigator.lua` [1]
    ...
    require('lsp.clangd') -- Settings for clangd LSP server
    ...
````
- `config\lua\lsp\clangd.lua` (`clangd` settings file):
````lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

require'lspconfig'.clangd.setup {
    -- cmd = {DATA_PATH .. "/lspinstall/cpp/clangd/bin/clangd"},
    -- cmd = {"clangd", "-ferror-limit=0"},
    cmd = {"clangd", "--limit-results=0", "--enable-config", "--collect-main-file-refs=true"},
    root_dir = require('lspconfig/util').root_pattern("compile_commands.json"),
    on_attach = require'lsp'.common_on_attach,
--     handlers = {
--         ["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
--             virtual_text = O.clang.diagnostics.virtual_text,
--             signs = O.clang.diagnostics.signs,
--             underline = O.clang.diagnostics.underline,
--             update_in_insert = true
-- 
--         })
--     }

    capabilities = capabilities,
}
````
- `config\lua\my-navigator-lua\init.lua` (`navigator.lua` settings file):
````lua
require('navigator').setup({})
````

The issue is that when decommenting the line reported above as **[1]**, then `navigator.lua` default settings are loaded, overwriting all of the LSP settings specified in the `config\lua\lsp\<client>.lua` files.

My question is, how to enable `navigator.lua` but at the same time maintain all of the LSP settings described in those single configuration files?

**Comment by ray-x** [comment]
you can put the lsp config inside navigator config

e.g.
```
  require "navigator".setup({
    lsp = {
      format_on_save = true, -- set to false to disasble lsp code format on save (if you are using prettier/efm/formater etc)
      clangd = {
        on_attach = function(client)  -- your clangd on_attach
          -- print("i am a hook")
          client.resolved_capabilities.document_formatting = false
          )
        end,
        settings = {
         --- your lsp settings
        },
       cmd = {....}
      },
```

**Comment by pidgeon777** [comment]
I'll try this solution, but in my opinion, it has a big disadvantage which LUA coding is trying to defeat: redundancy. The very same code would be copied into different modules, and it would be hard to maintain once the settings or LSP files increase in size and number.

It would be perfect to directly reference that `clangd.lua` setting file in your plugin setting, or import it someway.

By doing so, every time I modify the `clangd.lua` setting file, `navigator.lua` would also automatically apply the same setting.

Also, if I disable your plugin for somewhat reason, the `clangd` would still be available.

I was wondering if there would be any way to achieve that. I'm confident that the answer is es, but I'm not a LUA expert.

**Comment by ray-x** [comment]
You can have clangd.lua in your vimrc folder

clangd.lua
```
return {
  on_attach=function(client, buffnr)
      -- clang specific attach
  end,
 settings = {
 -- clang settings
 }
}
```
And in navigator setup 

```
require "navigator".setup({
    lsp = {
      format_on_save = true, -- set to false to disasble lsp code format on save (if you are using prettier/efm/formater etc)
      clangd = require "clangd"
    }
```
