### ISSUE TITLE
[Bug] After updated navigator broke

### ISSUE THREAD

**Issue by mkubasz** [ray-x/navigator.lua#190]
After PackerSync In my settings appears an error in the navigator. While debugging gh.log is empty.

Error message:
![2022-05-20_00-31](https://user-images.githubusercontent.com/1952619/169415118-4ba429a3-a657-44a9-a869-2bdd66f7a7b1.png)

```
function config.navigator()
  local nav_cfg = {
    lsp_installer = false,

    lsp = {
      disable_lsp = {
        'tsserver', 'jedi_language_server'
      }, 
    },
  }
  require("navigator").setup(nav_cfg)
  ```

**Comment by ray-x** [comment]
Submitted a fix for the log repo (guihua.lua).
