### ISSUE TITLE
Attemp to index field 'range' (a nil valuie) in python files

### ISSUE THREAD

**Issue by matbme** [ray-x/navigator.lua#192]
I get the following error then trying to open document symbols in python files: 

![image](https://user-images.githubusercontent.com/48367298/173068066-b82cf991-2d79-4d1a-8c00-6bd383324372.png)

I'm now sure whether this is a specific issue with Python files in general or Pylsp (the language server I'm using).

Update: Replaced Pylsp with Pyright and document symbols are now working, so the issue is specific to Pylsp

**Comment by ray-x** [comment]
seems range is missing in pylsp

**Comment by ray-x** [comment]
@matbme Could you check if it works?

**Comment by matbme** [comment]
Hi, sorry for taking a while to reply. It's working as intended now.
