### ISSUE TITLE
Usage with LSP plugins such as rust-tools

### ISSUE THREAD

**Issue by Suyashtnt** [ray-x/navigator.lua#195]
rt

**Comment by ray-x** [comment]
Hi, @Suyashtnt 
Is the Readme update works for you?

**Comment by Suyashtnt** [comment]
> Hi, @Suyashtnt 
> 
> Is the Readme update works for you?

Power currently out, but I'll let you know when I test

**Comment by Suyashtnt** [comment]
> Hi, @Suyashtnt Is the Readme update works for you?

I just get an error. Says navigator.mappings doesnt exist

**Comment by ray-x** [comment]
My bad, there is a typo, could you re-check README to see if the latest works for you?

**Comment by Suyashtnt** [comment]
It works

**Comment by avently** [comment]
Just a note for future readers. For this command to work (from readme):
```
require('navigator.lspclient.mapping').setup()
```
we need to make such changes:
```
require('navigator.lspclient.mapping').setup({
                client = {
                    name = "",
                    cmd = ""
                }
             })
```

otherwise there is an error right after start related to this line: https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/mapping.lua#L128

So the line requires that config has `client` object with `name` and `cmd`.

Thanks, @ray-x , for such wonderful plugin! Impressed how it's useful and cool looking (with `aurora`)

**Comment by ray-x** [comment]
Hi, @avently 
Thanks for pointing out the missing part. On second thought, I am making the client a required field and also updated the doc. One issue for a dummy client is that mapping will fail to get the lsp capabilities and some functions might be missing.
Please take another look at the updated version and README.md, thanks!

**Comment by avently** [comment]
works, thank you again.

Can't stop enjoying both plugin and Aurora. The theme is one of the best themes I saw in my life.

**Comment by ray-x** [comment]
Glad you like it 🤓

**Comment by avently** [comment]
@ray-x, unrelated to this issue but a small thing:
https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/workspace.lua#L40

here you probably mean vim.fn instead of vinf? 

```
workspace.lua:40: attempt to index global 'vfn' (a nil value)
```
