### ISSUE TITLE
tsserver is attached twice to the buffer when enabling single_file_support

### ISSUE THREAD

**Issue by FerasMaali** [ray-x/navigator.lua#196]
When I enabled `single_file_support` for `tsserver`, I see that it is being attached twice to the `javascript` buffer I'm currently editing

Here's a minimal `init.lua` that has the issue

```lua
local fn = vim.fn

local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.api.nvim_command ('packadd packer.nvim')
end

require("packer").startup(function(use)

    use 'wbthomason/packer.nvim'

    use 'nvim-lua/plenary.nvim'

    use {
        'williamboman/nvim-lsp-installer',
        config = function ()
            local lsp_installer = require "nvim-lsp-installer"

            lsp_installer.setup{};

            -- Include the servers you want to have installed by default below
            local servers = {
                "tsserver",
            }

            for _, name in pairs(servers) do
                local server_is_found, server = lsp_installer.get_server(name)
                if server_is_found then
                    if not server:is_installed() then
                        print("Installing " .. name)
                        server:install()
                    end
                end
            end
        end
    }

    use {
        'ray-x/navigator.lua',
        requires = {
            { 'ray-x/guihua.lua', run = 'cd lua/fzy && make' },
            { 'neovim/nvim-lspconfig' },
        },
        config = function ()
            require'navigator'.setup{
                lsp_signature_help = true,
                lsp_installer = true,
                lsp = {
                    tsserver = {
                        single_file_support = true
                    },
                }
            }
        end
    }

end)
```

And here's a Dockerfile to help you reproduce the issue

```dockerfile
FROM ubuntu:20.04

# Needed packages
RUN apt-get update && \
    apt-get install -y git curl wget gcc g++ python3

# Neovim
RUN wget --progress=dot:giga https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb && \
    dpkg -i nvim-linux64.deb && \
    rm -f nvim-linux64.deb

RUN bash -c 'curl -sL https://deb.nodesource.com/setup_14.x | bash' && \
    apt-get install -y nodejs

RUN echo 'alias vi=nvim' >> /root/.bashrc

COPY init.lua /root/.config/nvim/init.lua
```

## Steps to reproduce the issue:

1. Build the docker image using the Dockerfile above
2. Open `nvim`
3. Run `:PackerSync`
4. Run `:LspInstallInfo` to wait for `tsserver` to install
5. Exit nvim and run `nvim main.js` to open a js file
6. Run `:LspInfo`, and you'll have two `tsserver` instance spawned and attached to the buffer

**Comment by ray-x** [comment]
single_file_support is a new feature from lspconfig. I did not run much test against it. Need to check its behavior

**Comment by BeauSLM** [comment]
I'm getting the same behavior with the zls (zig language server). I've registered zig navigator via ```lua
require('navigator').setup { lsp = { servers = { 'zig' } } }```. Opening a single zig file results in the same problem where two servers are attached.

![image](https://user-images.githubusercontent.com/63375392/179650204-8d4e2fcf-5b3a-4c54-8299-e2eaf9aa82bd.png)

**Comment by ray-x** [comment]
Did you saw this in the latest version?

**Comment by ray-x** [comment]
<img width="210" alt="image" src="https://user-images.githubusercontent.com/1681295/179654521-c18978f9-e90e-49a9-a162-c364788569c3.png">
works fine for me.

**Comment by ray-x** [comment]
also tsserver with single-file
```
            lsp = {
              tsserver = {
                single_file_support = true,
              },
            },
```

<img width="204" alt="image" src="https://user-images.githubusercontent.com/1681295/179654895-1686529c-5f88-4384-8bae-a2c7433cec59.png">

Could you check if the latest version works for you?

**Comment by BeauSLM** [comment]
> Did you see this in the latest version?

I have not, my apologies.

**Comment by FerasMaali** [comment]
Thanks @ray-x 
The issue seems to be solved
I'll close it now
