### ISSUE TITLE
Split the cmd table in lsp to two parts: the command to envoke and the arguments

### ISSUE THREAD

**Issue by JuniorSuperTux** [ray-x/navigator.lua#202]
Wouldn't this be better since if I use lsp-installer and update the cmd to point to the lsp-installer installed binary, the default provided settings would just be overridden?

**Comment by ray-x** [comment]
The plugin was built on top of lspconfig, not on top of lsp-installer. It provides a way for users to extend their lspconfig.

the cmd setup should comply with lspconfig. I think lsp-installer should also do that.

**Comment by ray-x** [comment]
Please refer to document to setup `lsp_installer` in navigator. If it not working for you, feel free to comment/reopen
