### ISSUE TITLE
Add "use" to lua language server globals if packer is found

### ISSUE THREAD

**Issue by JuniorSuperTux** [ray-x/navigator.lua#203]
sumneko_lua causes some unwanted noises when editing packer startup function, complaining that the identifier `use` is undefined

**Comment by ray-x** [comment]
you may want to check out https://github.com/folke/lua-dev.nvim on how to setup lua env. 
```
-- plugins = { "nvim-treesitter", "plenary.nvim", "telescope.nvim" },
```

**Comment by ray-x** [comment]
As mentioned, you can use lua-dev to extend your sumneko setup. Close it for now. Feel free to comment if it still not working.
