### ISSUE TITLE
errors for keymaps customization

### ISSUE THREAD

**Issue by iwata** [ray-x/navigator.lua#204]
I'm using this variable as `setup.keymaps`.

```lua
local key_maps = {
  {key = "gh", func = require('lspsaga.finder').lsp_finder, doc = "finder"},
  {key = "gs", func = require('lspsaga.signaturehelp').signature_help, doc = "signature_help"},
  {key = "gp", mode = "n", func = require('lspsaga.definition').preview_definition, doc = "definition"},
}
```

The following error occurs.
`Error executing vim.schedule lua callback: .../ray-x/navigator.lua/lua/navigator/lspclient/mapping.lua:216: bad argument #1 to 'find' (string expected, got nil)`

So, the error no longer occurs when I replace it with the following snippet.

```lua
local key_maps = {
  {key = "gh", func = require('lspsaga.finder').lsp_finder, desc = "finder"},
  {key = "gs", func = require('lspsaga.signaturehelp').signature_help, desc = "signature_help"},
  {key = "gp", mode = "n", func = require('lspsaga.definition').preview_definition, desc = "definition"},
}
```

Set `desc` instead of `doc`. Is it correct?

**Comment by ray-x** [comment]
Thanks for point that out. `doc` -> `desc` as vim.api is using `desc`. It would align with the neovim API. I updated the codes but there are some document that was not updated. Pushed another update through.

**Comment by iwata** [comment]
I see, thanks!
