### ISSUE TITLE
Error detected while processing BufWritePre Autocommands for "*.go"

### ISSUE THREAD

**Issue by obmutescences** [ray-x/navigator.lua#206]
hi. when save go file get this error.
![Snipaste_2022-07-14_18-02-59](https://user-images.githubusercontent.com/29330637/178957831-393b83fd-7a88-4ac9-9cf0-e3b62958dd41.png)

**Comment by obmutescences** [comment]
> I experienced this today and the I figured what was causing this error. This will happen if you have a problem/syntax error in your code however, I'm also looking for a solution to handle this better. I looked at the config and cannot find anything to make this error silent. 

thanks for reply. yea! its will happen that my code have a problem/syntax error. is it no way be fixed?

**Comment by ray-x** [comment]
Thanks for the reporting, It should be fixed now.

**Comment by obmutescences** [comment]
> Thanks for the reporting, It should be fixed now.

cool. tks
