### ISSUE TITLE
How do i map <C-c> to close listview?

### ISSUE THREAD

**Issue by AstroShen** [ray-x/navigator.lua#207]
Hello, <C-e> is the default keymap to close a listview. But since most users install telescope whose <C-c> is the keymap to close windows. So i want keymap <C-e> converg to <C-c>.

**Comment by ray-x** [comment]
The keymap was listed 
https://github.com/ray-x/guihua.lua#setup
Only applys to the navigator/guihua buffers.

**Comment by AstroShen** [comment]
THX, really helpful!
