### ISSUE TITLE
Can I unmap a default key map?

### ISSUE THREAD

**Issue by mosheavni** [ray-x/navigator.lua#208]
Hi,
Love the plugin, thanks for the hard work.
Can a default mapping can be disabled?
Or alternatively, can the full configuration including default mappings be added to the README.md or navigator.txt help file?
That way I can add all of the defaults instead of the one I don't want.
Use case:
I have a mapping for `<C-k>` to navigate between splits (mapped to `<C-w><C-k>`. I would like to preserve this mapping instead of changing the entire set of 4 mappings of navigating between splits.
Thanks.

**Comment by ray-x** [comment]
The mapping is listed in lspclient/mapping.lua file
you can override any maps by using something like this:
  `keymaps = {{key = "gK", func = vim.lsp.declaration, desc = 'declaration'}}, -- a list of key maps`

`<C-w>k` is not a navigator mapping. It is a guihua.lua mapping to jump between windows. It is config through guihua

https://github.com/ray-x/guihua.lua#setup



Also `<c-k>` is already used by navigator. , Please use`:LspKeymaps` to check default mapping. Or, use check source code lspclient/mapping.lua

**Comment by mosheavni** [comment]
I explained poorly, what I meant is that I do have this mapping:
```vimscript
nnoremap <c-k> <c-w><c-k>
```
I will take a look at the mapping file, though I still think it can be added to the documentation, and if we can "disable_default_mappings" somehow, that'd be the best option.
