### ISSUE TITLE
guihua transparent

### ISSUE THREAD

**Issue by zsantiago8712** [ray-x/navigator.lua#209]
It is posible to make transparent the guihua?? I have everything transparent but I can't make it work with guihua 
<img width="1114" alt="CleanShot 2022-07-17 at 13 31 30@2x" src="https://user-images.githubusercontent.com/59674428/179419883-464e9e25-f5e3-4bda-a731-81aa51cad77d.png">

**Comment by ray-x** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1681295/179426019-c9032a59-b1a8-4b56-9c47-84d87712ea89.png">

If you want to change, Check highlight `GuihuaListDark`.

**Comment by zsantiago8712** [comment]
thanks, I will check it out!!

**Comment by zsantiago8712** [comment]
<img width="909" alt="CleanShot 2022-07-17 at 19 10 21@2x" src="https://user-images.githubusercontent.com/59674428/179430401-34ad579f-45b8-47e7-af7f-839d8ba1bc9b.png">
THANKS!! IT WORKD
