### ISSUE TITLE
Error: neovim client has shut down after sending [lspserver] using typescript

### ISSUE THREAD

**Issue by lynndylanhurley** [ray-x/navigator.lua#211]
Since updating to the latest commit (9aad2978dc716a7908ee2c825a46c3070a7e2d25) the LSP server started going haywire. 

I'm getting hundreds of errors per minute, and it's blocking my ability to type.

Rolling back to the previous commit (49c3e5cd4d6b24067b9ca24f0b046a646fdee270) resolved the issue for me.

**Comment by ray-x** [comment]
Thanks for reporting the issue. there was a typo, my bad. Should work now.

**Comment by lynndylanhurley** [comment]
works now! thanks @ray-x !!
