### ISSUE TITLE
LSP sometimes doesn't load when using lsp_installer=true

### ISSUE THREAD

**Issue by tylerd-carta** [ray-x/navigator.lua#214]
I've noticed that sometimes my LSP doesn't load correctly, but it is non-deterministic. In the debug logs I would see
```
[INFO][Fri 22 Jul 10:02:11 2022] [3].../start/navigator.lua/lua/navigator/lspclient/clients.lua:685: loading gopls name gopls has lspinst false
```
even though I have set `lsp_installer = true` in my `require('navigator').setup()`.

I believe this is because the check if `lsp_installer` is set in the config is done at the module scope https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/clients.lua#L376 and depending on the iteration order in `navigator.extend_config` this require statement https://github.com/ray-x/navigator.lua/blob/master/lua/navigator.lua#L211 may run before the `lsp_installer` value in the config has been updated.

As a quick test I copied https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/clients.lua#L373-L389 to https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/clients.lua#L534 and I'm no longer able to reproduce.

I don't use lua much so I don't know how this should be solved more permanently otherwise I would open a PR.

**Comment by ray-x** [comment]
I pushed a change for it. I agree the sequence may need to adjust as you mentioned.

**Comment by tylerd-carta** [comment]
I seems like your change resolved this issue! I did have to apply the following patch when I pulled the latest version though:

```diff
diff --git a/lua/navigator/lspclient/clients.lua b/lua/navigator/lspclient/clients.lua
index 9ae9863..0ac93fd 100644
--- a/lua/navigator/lspclient/clients.lua
+++ b/lua/navigator/lspclient/clients.lua
@@ -1,5 +1,6 @@
 -- todo allow config passed in
 local ng_util = require('navigator.util')
+local path_sep = require('navigator.util').path_sep()
 local log = ng_util.log
 local trace = ng_util.trace
 local empty = ng_util.empty
```

**Comment by ray-x** [comment]
Thanks, patch applied to latest
