### ISSUE TITLE
[Feature] Migration from lsp-installer to mason.nvim?

### ISSUE THREAD

**Issue by cj** [ray-x/navigator.lua#215]
lsp-installer is soon to be deprecated https://github.com/williamboman/nvim-lsp-installer/discussions/876 in favor of [mason.nvim](https://github.com/williamboman/mason.nvim).

**Comment by ray-x** [comment]
I think it is good to provide a unified way to install binaries inside neovim.
But I hope they will not change API too much....

**Comment by ray-x** [comment]
@cj Could check if the latest works for you?

**Comment by cj** [comment]
@ray-x I will check it today and let you know!
