### ISSUE TITLE
Problem with predefined highlight autocmd

### ISSUE THREAD

**Issue by avently** [ray-x/navigator.lua#216]
There is autocmd with added highlight colors https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/highlight.lua#L57. These autocmds add more problems than solves. I have at least two problems:
- themes that do not override LspReferenceRead/LspReferenceText/LspReferenceWrite have styles defined by you that do not look good with other themes. Whenever I select a word, LSP highlights other similar words with non good colors unrelated to selected theme
- whenever I call command `color sometheme` I see in log panel of nvim text from selected line. I'm not sure how this can be related but when I removed your lines with autocmd the problem has gone away. So, what happens in detail:
```
1 This is first line in file
2 This is second line
3 This is another line     <---- I moved cursor on this line
```
Then I press `:color aurora`

On the log panel of nvim I see this:
```
3 This is another line
3 This is another line
3 This is another line
```
I have NO IDEA how this can happen. Do you have the same issue?

I made an investigation in order to find the cause of this two issues. It was a surprize that the cause of the first issue is the cause of the second issue too:)

So the solution to this I see a deletion of these lines from the plugin or at least making that autocmd optional (so I can choose to not enable the autocmd).

**Comment by ray-x** [comment]
LspReferenceXxxx are added long time ago before color schemes begin to supported those highlight groups. I can update the highlight override and use latest API to define those.

**Comment by ray-x** [comment]
Thanks for submitting the issue. It should be fixed now. Would you have a look of latest?

**Comment by ray-x** [comment]
It only overrides when your colorscheme does not define LspReferenceXxxx. I would say most modern color scheme designed for neovim should define those.
You can override those colorscheme as well. 

But if it is not defined. highlight reference wont work. Also here is what I saw in am minimum setup. 

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1681295/181155577-d06dffc4-4e0a-4a49-acfc-c3985b4c9872.png">

**Comment by ray-x** [comment]
Also. For me, it is much easier to track issue say `I do not like this color`, how to change that. Rather than xxx feature is not working what is causing it.

**Comment by avently** [comment]
Ok, got it. How I can clear your highlighting to empty values? This code doesn't work for some reason if I place it into Packer's `config` function:
```
vim.cmd [[
        hi clear LspReferenceRead
        hi clear LspReferenceText
        hi clear LspReferenceWrite
]]
```

**Comment by avently** [comment]
Oh, in the https://github.com/ray-x/navigator.lua/commit/89dd02c9270537de1187967f1cea14030d0bd7ad#diff-648dac2ff11c5d47dfe35a33761b6d3e80efcf85544ab268a4f21c92fdb13032R68 you made an autocmd which brokes all themes which even provides highlighting for LspReferenceRead/LspReferenceText/LspReferenceWrite but doesn't specify bold, italic and others that you specified. It happens because ColorScheme autocmd loads after the theme and all highlighting are merged. So now the only solution I see is to remove all problematic lines from `highlight.lua` using `sed` from packer's cmd function.

**Comment by ray-x** [comment]
I am not following...
do you mean your neovim failed with this nvim_set_hl option:
`{ default = true, bold = true, ctermfg = 'White', underline = true }`
Are you using neovim 0.7.2 or later?

**Comment by avently** [comment]
If you worry about this:
> which brokes all themes which even provides highlighting for LspReferenceRead/LspReferenceText/LspReferenceWrite but doesn't specify bold, italic and others that you specified

then don't. I was unable to reproduce it, looks my eye catched an element with similiar highlighting (white text with underline) but it was made like this by the theme for another group (not for `LspReference*`).

I have many themes and only a couple of them supports overriding `LspReference*`. If the theme doesn't support it, `navigator` pushes it's highlighting which is not always good. So I use `sed` to remove those highlighting and set my own. If I don't remove navigator's highlighting, I can't override with my styles.
