### ISSUE TITLE
Miss two symbols in README.md "All configure options"

### ISSUE THREAD

**Issue by marcuslannister** [ray-x/navigator.lua#217]
1. tagfile = 'tags' →
    tagfile = 'tags',

2. options = '-R --exclude=.git --exclude=node_modules --exclude=test --exclude=vendor --excmd=number'
    } → 
    options = '-R --exclude=.git --exclude=node_modules --exclude=test --exclude=vendor --excmd=number'
    },

**Comment by ray-x** [comment]
should be fixed in the latest. thanks!
