### ISSUE TITLE
J & K doesn't browse through results

### ISSUE THREAD

**Issue by JuniorSuperTux** [ray-x/navigator.lua#222]
As title

**Comment by ray-x** [comment]
do you mean navigate inside the list view of floating windows?

**Comment by JuniorSuperTux** [comment]
Indeed

**Comment by JuniorSuperTux** [comment]
Please also take renaming variables into consideration

**Comment by JuniorSuperTux** [comment]
But this is only expected to be activated in normal mode, but this is also activated in insert mode of the prompt. This makes the input of hjkl unusable.

**Comment by ray-x** [comment]
Cool, updated

**Comment by JuniorSuperTux** [comment]
Also can you make renaming variables insert mode upon entering?

**Comment by ray-x** [comment]
Not so sure change to insert mode is necessary. As both have their pros and cons.
