### ISSUE TITLE
loclist not being autoclosed when everything is fixed

### ISSUE THREAD

**Issue by brenol** [ray-x/navigator.lua#224]
Hi! Just noticed a small issue with loclist not being autoclosed when all issues are fixed.

Seems to be happening because of the early-return here:
https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/diagnostics.lua#L401-L406

As it never reaches the `vim.cmd('lclose')` here:
https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/diagnostics.lua#L415-L428

Not sure if it happens with everyone but it surely does happen with me, happy to assist in anything!

Thank you for the great project!

**Comment by jiaad** [comment]
i am facing the same problem.

https://user-images.githubusercontent.com/45911781/197281137-82fffc5f-99e0-4111-9fad-974f851520bb.mov

**Comment by ray-x** [comment]
Pushed a fix for it.

**Comment by jiaad** [comment]
> Pushed a fix for it.

doesn't work for me 
my current navigator.lua config.

![Screenshot 2022-11-01 at 10 42 51](https://user-images.githubusercontent.com/45911781/199205530-48472485-833b-4bc1-ac04-c0c50564571d.png)

**Comment by jarredkenny** [comment]
Seeing the same behaviour.

**Comment by ray-x** [comment]
Pushed some changes for this. But if it still not working, please send me the language server and some sample code I can reproduce. Thanks!

**Comment by jarredkenny** [comment]
Synced your changes (the force close commit) but am now seeing this error on loclist open.

![Screenshot 2023-01-31 at 6 42 29 PM](https://user-images.githubusercontent.com/1010249/215900502-3e4345be-05d5-40f4-85bf-6da2024e42ac.png)

`:LspInfo`
![Screenshot 2023-01-31 at 6 43 11 PM](https://user-images.githubusercontent.com/1010249/215900588-436fc740-057a-452a-af0d-4a0f4c20d743.png)

**Comment by ray-x** [comment]
Sorry, my bad I am trying to deprecating old apis. It should be good now.

**Comment by jarredkenny** [comment]
Working perfectly now 🙏 

Thank you!
