### ISSUE TITLE
Codelens sign not showing, how to debug textDocument/codeLens handler ?

### ISSUE THREAD

**Issue by sp4ke** [ray-x/navigator.lua#228]
The codelens sign does not show for me, I tried logging from within the custom 'textDocument/codeLens' [handler here](https://github.com/ray-x/navigator.lua/blob/c70d032b08a6897b25611ae3fa6e1e084c1eb72f/lua/navigator/codelens.lua#L79) but no log is produced however the setup function in `codelens.setup()` is called. 

I made sure I have no other plugin that overrides textDocument/codeLens handler. 
 
**navigator version**: master
**neovim version**: 
```
NVIM v0.8.0-dev-1023-g5ac665433
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui
```

**Comment by ray-x** [comment]
I feel it just because the lsp server is slow. Some time you saw the codelens sign but you have to wait another 2~4 second before you can run those code lens actions

**Comment by sp4ke** [comment]
Sorry maybe my message was not clear.

The virtual text for the code lens appears, but not the sign on the column line.

**Comment by ray-x** [comment]
yes. Ok I saw what your mean. the sign is missing as the handler seems not been triggered. I there there are something changed upstream I did not follow up.

**Comment by sp4ke** [comment]
Looks like it's working with your latest fix thanks :)
