### ISSUE TITLE
navigator don't work correctly with `nvim-notify` ，print following "dohighlight" error constantly when typing anything in insert mode 

### ISSUE THREAD

**Issue by ancion** [ray-x/navigator.lua#234]
Error executing vim.schedule lua callback: ...k/packer/start/nvim-notify/lua/notify/render/default.lua:6: bad argument #1 to 'max' (number expected, got no value)
stack traceback:
        [C]: in function 'max'
        ...k/packer/start/nvim-notify/lua/notify/render/default.lua:6: in function 'render'
        ...ker/start/nvim-notify/lua/notify/service/buffer/init.lua:102: in function 'render'
        ...ack/packer/start/nvim-notify/lua/notify/service/init.lua:53: in function 'push'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:214: in function 'notify'
        ...acker/start/navigator.lua/lua/navigator/dochighlight.lua:247: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by ray-x** [comment]
Submitted a fix for it.

**Comment by ancion** [comment]
notify alert error 

```
failed to highlight symbol{
  code = -32801,
  message = "Request cancelled because the document was modified",
  <metatable> = {
    __tostring = <function 1>
  }
}
```

**Comment by ray-x** [comment]
sounds like a lsp error.
What Lsp/language you are using?

**Comment by ancion** [comment]
It should&nbsp; be,&nbsp; only clang alert error.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 26, 2022 13:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ray-x/navigator.lua] navigator don't work correctly with `nvim-notify` ，print following "dohighlight" error constantly when typing anything in insert mode  (Issue #234)




 
sounds like a lsp error.
 What Lsp/language you are using?

**Comment by ray-x** [comment]
What I know from the message is that the clang server was updating while the highlight request was sent.
I add an update to ignore those errors. Not sure if it will solve the issue.

**Comment by ray-x** [comment]
@ancion Could you check if the latest version fixes the issue?

**Comment by ancion** [comment]
> 

this error is not show again, but that error info is still in lsp log file. These are not really interfering with my work. Thank you very much !!
