### ISSUE TITLE
Consequences of disabling LSP within plugin

### ISSUE THREAD

**Issue by avently** [ray-x/navigator.lua#236]
Hello. Periodically I'm having problems with the navigator plugin that acts like LSP installer. Since I already have mason within LunarVim I decided to disable mason feature within navigator while having it in LunarVim. I added these lines in config:
```
lvim.lsp.on_attach_callback = function(client, bufnr)
  require('navigator.lspclient.mapping').setup({client = client, bufnr = bufnr})
  require("navigator.dochighlight").documentHighlight(bufnr)
  require('navigator.codeAction').code_action_prompt(bufnr)
  require"lsp_signature".on_attach()
end
```

What consequences these change can give me? Is it enough for using 100% of possibilities of navigator or do I need to do something else?

**Comment by ray-x** [comment]
I am not using lunarvim but those look good to me.

**Comment by avently** [comment]
Ok, cool. Thanks!
