### ISSUE TITLE
Window lag

### ISSUE THREAD

**Issue by Davincible** [ray-x/navigator.lua#245]
I'm getting this screen lag when scrolling down that only seems to happen with navigator enabled. Do you have any idea which functionality it could relate to? I'm thinking maybe some aggressive auto commands?

This happens when I scroll down all the way to the bottom. It goes away if I press `Esc` or `<C-]>`, not on `<C-c>`.

![image](https://user-images.githubusercontent.com/25869544/201364491-3b619f46-f352-4d53-b430-82e3a87862d6.png)

**Comment by ray-x** [comment]
TBH, I have never seen this before. Might be other settings, 
did you enable lazyredraw ?

**Comment by Davincible** [comment]
Hmm okay

> did you enable lazyredraw ?

nope.

I will close for now then, if I ever figure out more I might re-open
