### ISSUE TITLE
 How to modify code action ui width

### ISSUE THREAD

**Issue by gouez** [ray-x/navigator.lua#246]
The current width is full screen
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/4373882/203881793-a9e88d38-c303-41aa-bba5-d867412f364a.png">

**Comment by ray-x** [comment]
There is a setup:
```lua
require'navigator'.setup({
  width = 0.75, -- max width ratio (number of cols for the floating window) / (window width)
```
AFAIK, the default is 0.62 and it should not go to 1.00. Unless the calculation is not correct. E.g. failed to get the current windows size.

**Comment by gouez** [comment]
![cc](https://user-images.githubusercontent.com/4373882/203891049-05819d95-5dee-4108-863b-d2cff7a158e9.gif)
my current configuration
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/4373882/203891524-81e6dcb4-5fa2-4ddc-97e5-e55a2774729e.png">

seems to still have the same problem

**Comment by ray-x** [comment]
strange, works in upper half of your nvim, not bottom half

**Comment by ray-x** [comment]
Pushed a fix for this issue.

**Comment by gouez** [comment]
Thanks, the fix worked!
