### ISSUE TITLE
Backspace not working in guihua-like interfaces

### ISSUE THREAD

**Issue by DrKGD** [ray-x/navigator.lua#248]
First and foremost thanks for the great plugin, I am loving it so far!

## The problem
I am encountering a problem similiar to these ones https://github.com/ray-x/navigator.lua/issues/23#issue-929082871 https://github.com/ray-x/navigator.lua/issues/114#issue-1071371786, thus I am unable to use the `Backspace` key inside floating windows upon entering text.

I do have autopairs enabled with minimal configuration, but doesn't seem to be the culprit here, as disabling it has no effect and also `<BS>` seems to be mapped, to some degree, as suggested in the other git issues.
![image](https://user-images.githubusercontent.com/44092476/208736062-3d201c9a-b063-4d32-836c-e4ce60e1235d.png)

(output of `:imap <BS>` inside the floating window)
![image](https://user-images.githubusercontent.com/44092476/208736440-aae4f3da-bcbb-471f-a097-bf76b3d6cdaf.png)

## Setup 
My nvim configuration is quite massive (97 plugins!), and I am constantly tinkering with it, but in case nothing can be done to troubleshoot the problem right away I am willing to disable and test each one of them.

At the moment these are the LSP-related plugins
![image](https://user-images.githubusercontent.com/44092476/208737146-bcbb4b75-d09c-4a6f-a524-ebf78515fe9f.png)

These are the configuration for ray-x/navigator, lsp_signature and guihua
![image](https://user-images.githubusercontent.com/44092476/208736948-e205f832-465a-4422-8d2c-fcc939d62af3.png)

This is pretty much the on_attach method used for all of the LSP server(s) configuration
![image](https://user-images.githubusercontent.com/44092476/208739116-105902be-66da-45ba-9ecf-e2d9661b6f03.png)

## Further information
I am on the lastest, main branch, release.
Last but not least I _should_ be on the lastest nightly nvim version
```
NVIM v0.9.0-dev-525+ga7332ba9b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Thanks!

**Comment by ray-x** [comment]
I went through your setup and saw nothing really wrong/suspicious. 
Also the `imap <BS>` you run suggested the map is correct.
What the issue you saw on your end by now working. Is it when you BS but nothing happens?

One thing you can try is with guihua only, 

https://github.com/ray-x/guihua.lua/blob/1a8af45b2117d28ca56d38c275af1c211f0ffd94/lua/guihua/tests/listview_test.lua#L537

You can comment out the above line and run
`:luafile %` in nvim
Then test with `<BS>` and `<C-w>` to see if works for you or not.
![image](https://user-images.githubusercontent.com/1681295/215078856-034b57f6-c0b6-4ac3-8e9b-7a2022a19c77.png)

**Comment by DrKGD** [comment]
Thanks for your time, I understand that probably (definitely) everything is just related to my configuration and nothing else; I recorded both the behavior of `<Backspace>` and `<C-w>` to give more context

Backspace behaves like nothing happened, more specifically it is handled by the nvim instance but it does not delete any character 

https://user-images.githubusercontent.com/44092476/215154433-f5f66bbf-87ec-4e71-9cb3-77a06ec74073.mp4

`<C-w>` deletes one character at the time; not really sure this is the expected behavior either, shouldn't it delete the entire word before the cursor?

https://user-images.githubusercontent.com/44092476/215154761-18836316-e6f5-42d7-8c08-7e2090f37ec0.mp4

**Comment by ray-x** [comment]
\<c-w> suppose to delete previous word.
Can you try what I did in video below?


https://user-images.githubusercontent.com/1681295/215230226-4b2f42c3-fb73-4b13-b914-f65e4828c3eb.mp4

Thanks

**Comment by DrKGD** [comment]
Just tested it out, by calling manually the underlaying binded function you provided works just fine

**Comment by ray-x** [comment]
Ok, that means one of your plugins hijack `<BS>`
Could you do 
`lua vim.keymap.set('i', '<c-x>', 'lua ListViewCtrl:on_backspace()')`

to map `<c-x>` and check if `<c-x>` works for you? I think there might be some remap prevent `<BS>` mapping working correctly.

**Comment by DrKGD** [comment]
I suppose it has to be mapped either as expr, cmd or plug, anyway seems like it seems to be mapped just fine 🤔

https://user-images.githubusercontent.com/44092476/215233302-ecdbaad7-8872-4b22-a9ff-6c0edfba13a9.mp4

**Comment by DrKGD** [comment]
Maybe I found the culprit, I have gone through the whole configuration right now (I already wasted a lot of your time)

```lua
-- # Allow cursor to overflow by one
vim.opt.virtualedit			= 'onemore'
```

Fun fact, I disabled almost all the plugins in my configuration, turns out no plugins were at fault 😂

**Comment by ray-x** [comment]
Ok, I agree. Thanks!
I pushed a change to enforce the virtualedit to be block in `guihua` floating

**Comment by DrKGD** [comment]
Works for me, thanks again!
Guess I'll go ahead and close this issue.
