### ISSUE TITLE
Definition preview does not work

### ISSUE THREAD

**Issue by pluma9** [ray-x/navigator.lua#254]
# Reproduce
When I press `gp` to trigger definition preview, I get the following error: `No result found: textDocument/definition`

# Expectation
A preview window appears and contains the definition

# More info
I can go to the definition by pressing `gd` (go to definition) or `ctrl`+`click`.

To make sure I got the correct key mapping, this is the output when I run `:map gp`:

> n  gp          *@<Lua 164: ~\AppData\Local\nvimata\plugged\navigator.lua/lua/navigator/definition.lua:46>
                 definition_preview

this is the output when I run `:map gd`:

> n  gd          *@<Lua 175: ~\AppData\Local\nvim-data\plugged\navigator.lua/lua/navigator/definition.lua:156>
definition

# Screen recording:
Press `gp`:

https://user-images.githubusercontent.com/16544647/209473649-6dcee3d4-30b7-4141-9eda-f233643311a9.mov

`Ctrl + click`:

https://user-images.githubusercontent.com/16544647/209473662-29970407-6411-4767-8aa2-bf96153e4805.mov

Press `gd`:

https://user-images.githubusercontent.com/16544647/209473676-52ab1dfa-3d57-413f-8221-4994c1256998.mov

**Comment by ray-x** [comment]
Does it happen to other lsp servers?
Are you using tsserver?

**Comment by pluma9** [comment]
Turns out it works with tsserver. Seems like this is specific to omnisharp roslyn.

**Comment by ray-x** [comment]
close as it LSP dependent.

**Comment by pluma9** [comment]
Do you have any suggestion on  what action I should take to get this fixed? I can open C# definition on a floating window using [rmagatti/goto-preview](https://github.com/rmagatti/goto-preview), a plugin that is slightly similar  to navigator.lua.

**Comment by ray-x** [comment]
I am not familiar with C#
Could you send / upload the code snippets and lsp server setup so I can reproduce?
