### ISSUE TITLE
why can't set lsp signature help config 

### ISSUE THREAD

**Issue by Meigumikato** [ray-x/navigator.lua#255]
my config   
lsp_signature_help = true 
  signature_help_cfg = {
    debug = false,
    handler_opts = {
      border = "rounded"
    },
  },

nvim messages
WRN: [] Key signature_help_cfg handler_opts not valid

**Comment by Meigumikato** [comment]
debug log
[INFO][日  1/ 1 00:48:10 2023] [3]...m/lazy/navigator.lua/lua/navigator/lspclient/mapping.lua:383: setup signature from navigator

**Comment by ray-x** [comment]
ops, it is a bug. I submitted a fix for it.

**Comment by Meigumikato** [comment]
ok
