### ISSUE TITLE
Attempt to perform arithmetic on local 'width' (a nil value) java language server (jdtls)

### ISSUE THREAD

**Issue by JuanEL0** [ray-x/navigator.lua#257]
I opened a Java project (SpringBoot) but when I try to open the treesitter document symbol, I got this error:

```sh
E5108: Error executing lua: .../packer/start/navigator.lua/lua/navigator/treesitter.lua:779: attempt to perform arit
hmetic on local 'width' (a nil value)
stack traceback:
        .../packer/start/navigator.lua/lua/navigator/treesitter.lua:779: in function <.../packer/start/navigator.lua
/lua/navigator/treesitter.lua:768>
```

And of course I can not open the floating window but with other projects (Typescript, Angular and Go) I don`t have this problem.
Thanks.

**Comment by ray-x** [comment]
It may not releated to jdtls. It may be more related to the treesitter parser for java. Did you installed java TS parser?

I also pushed a fix to show a warning if no TS symbols are found.

**Comment by JuanEL0** [comment]
You are right, I didn't install the java TSParser, sorry I am very new in NVIM.

Once I have installed, everything works as butter in bread.

By the way this project is amazing, thank you!!
