### ISSUE TITLE
rust-tools.nvim interaction - RustRunnables missing

### ISSUE THREAD

**Issue by uvb1** [ray-x/navigator.lua#258]
Thank you for such a nice plugin!

I'm using this with [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim) and I've noticed that when I `require("navigator").setup({})`, then `RustRunnables`, `RustExpand`, etc from `rust-tools.nvim` are missing.

I'm using Neovim v0.8.2 and [packer.nvim](https://github.com/wbthomason/packer.nvim) with this relevant portion from a minimal config:
```lua
use { "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" }
use "neovim/nvim-lspconfig"
use "simrat39/rust-tools.nvim"
use({
	'ray-x/navigator.lua',
	requires = {
		{ 'ray-x/guihua.lua', run = 'cd lua/fzy && make' },
		{ 'neovim/nvim-lspconfig' },
	},
})

...

require('nvim-treesitter.configs').setup({ ensure_installed = { "rust" } })

local rt = require("rust-tools")
rt.setup({
	server = {
		on_attach = function(client, bufnr)
			require('navigator.lspclient.mapping').setup({ client = client, bufnr = bufnr })
			require("navigator.dochighlight").documentHighlight(bufnr)
			require('navigator.codeAction').code_action_prompt(bufnr)
		end
	}
})

require("navigator").setup({})
```

Is anyone else having this issue or have any suggestions?

**Comment by ray-x** [comment]
For rust you can do this to prevent rust_analyzer been initialized from navigator
```
require("navigator").setup({
  lsp = {
      disable_lsp = {  "rust_analyzer" }, --e.g {denols}
  }
})
```
Are those the only commands missing or are other commands missing as well?

![image](https://user-images.githubusercontent.com/1681295/212801780-143ed830-1a72-43a2-af07-03f0a845ebaa.png)

**Comment by liam-ngy** [comment]
Hey @ray-x  there are some other commands missing. :) Is it possible to use directly the default rust-tools but still have the lsp features from navigator like references?

**Comment by ray-x** [comment]
The plugin should not conflict with rust-tools. What are the missing commands?
