### ISSUE TITLE
When changing the default <c-k> mapping, re-running PackerCompile reports an error.

### ISSUE THREAD

**Issue by dai-oh** [ray-x/navigator.lua#259]
This is shown below:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/62934849/212800421-9dcf82e4-9aab-4dfc-8181-913ab3990b4c.png">

`packer.nvim: Error running config for navigator. lua: [string "..."] attempt to index upvalue ' (a nil value)`

The reason I wanted to change <c-k> is that tmux has conflicting navigation keys and wanted to keep <c-k> for tmux to use.

Thank you for your hard work!

**Comment by ray-x** [comment]
I am using this for testing:
```
    keymaps = { { mode = 'i', key = '<M-d>', func = vim.lsp.buf.signature_help, desc = 'signature' }} ,
```
It works fine. Do you have a full log to show which line it breaks?

**Comment by dai-oh** [comment]
> I am using this for testing:
> 
> ```
>     keymaps = { { mode = 'i', key = '<M-d>', func = vim.lsp.buf.signature_help, desc = 'signature' }} ,
> ```
> 
> It works fine. Do you have a full log to show which line it breaks?

How can I give you this detailed log, I can provide specific log information as you said.

**Comment by ray-x** [comment]
When you see errors, type
`:messages` in vim command line and screenshot the output. That will do.

**Comment by dai-oh** [comment]
> When you see errors, type `:messages` in vim command line and screenshot the output. That will do.

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/62934849/212806664-0b49bc5a-0aa9-4a7e-8a8f-46182b60f6b2.png">

**Comment by ray-x** [comment]
@dai-oh 
Could you check if you are running on the latest version? From the logs of line 118 of clients.lua. It seems to me an very old version you are using. Thanks!

**Comment by dai-oh** [comment]
> @dai-oh Could you check if you are running on the latest version? From the logs of line 118 of clients.lua. It seems to me an very old version you are using. Thanks!


If I can't locate the problem with my system and nvim for the time being, I may close this issue to avoid causing you any trouble. The corresponding nvim version is as follows:


<img width="308" alt="img" src="https://user-images.githubusercontent.com/62934849/215014381-7fc28388-8178-4f2f-b8ad-d764bc062671.png">

**Comment by ray-x** [comment]
Could you also check if you are using latest navigator.lua as well? thanks!

**Comment by dai-oh** [comment]
> Could you also check if you are using latest navigator.lua as well? thanks!

😂 It's fine on its own after reinstalling neovim today. I can't reproduce this issue for now, thank you for not helping, I'll close this issue for now.
