### ISSUE TITLE
`sumneko_lua` is deprecated in `nvim-lspconfig`, but still used in `navigator.lua`

### ISSUE THREAD

**Issue by farzadmf** [ray-x/navigator.lua#262]
Hey,

Took me a while to look into the errors I see about the [now deprecated](https://github.com/neovim/nvim-lspconfig/pull/2439) `sumneko_lua` (renamed to `lua_ls`) and see that the errors are actually happening because I have `navigator.lua` enabled

I think the reason is that `navigator.lua` is including [sumneko_lua.lua](https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/lspclient/sumneko_lua.lua)

Really appreciate if the issue is fixed 🙂

**Comment by ray-x** [comment]
thanks, it was fixed

**Comment by farzadmf** [comment]
Thank you for the quick fix @ray-x
