### ISSUE TITLE
Within none lua project , lspconfig cannot access configuration for lua_ls

### ISSUE THREAD

**Issue by leileimi** [ray-x/navigator.lua#264]
![Image_20230316110522](https://user-images.githubusercontent.com/26601097/225501571-c7e628d7-ed87-4b1e-a1c2-99da7e32e9a8.png)
using default config in navigator

**Comment by ray-x** [comment]
Do you have a init.lua I can check?
From what I saw, this is caused by an old version of lspconfig. You can update the lspconfig to see if it is solved.

**Comment by leileimi** [comment]
> 
resolved  after updating the  version of lspconfig!
Your reply is very useful. Thanks a lot.
