### ISSUE TITLE
What's the dashed line in signcolumn?

### ISSUE THREAD

**Issue by acetylen** [ray-x/navigator.lua#269]
Sometimes, navigator will draw a dashed line in the sign column for no discernible reason. I use `set signcolumn=number` to merge the sign column with the line number indicator so that the window contents don't jump around so much, and the dashed line then obscures line numbers completely:
![image](https://user-images.githubusercontent.com/42578370/229504827-14e919c9-b832-4d56-a97a-ae325c78fa7f.png)

I've not been able to figure out why this line is drawn, or why it only appears in some files, even varying in files of the same type. Since it's mostly only in my way, is there a config option to turn it off?

**Comment by ray-x** [comment]
Navigator does not change the style of signcolumn. You saw those is very likely something is defined in `DiagnosticSign[Warn|Error|Info|Hint]` in your colorscheme.
Also one of the LSP is complaining about a range of lines having diagnostic warning/info/hint

**Comment by acetylen** [comment]
You know what, it's a git plugin. I feel a fool. Sorry for bothering you.
