### ISSUE TITLE
Keybinding compatibility issues for old neovim users

### ISSUE THREAD

**Issue by lordvidex** [ray-x/navigator.lua#273]
Description
I am having trouble using the plugin that combines Treesitter with LSP functionality, along with other plugins such as ray-x/go.nvim. While this plugin is beginner-friendly, it conflicts with some of my existing keybindings, making it difficult to use. For example, <Space>ff is used for both Telescope find_files and formatting, which I had previously assigned to <Space>lf.

Details
I am aware that this plugin offers a more streamlined setup process for new users. However, I have already set up my keybindings (mostly from LunarVim), which conflicts with the keybindings from this plugin. I have attempted to resolve this issue by hooking my on_attach callback to navigator's setup function, but this overrides some of my configurations registered with which-key.

Request
Can you please provide a solution for resolving these plugin compatibility issues? Thank you.

**Comment by ray-x** [comment]
You can ignore the default key mapping by set:
```
 default_mapping = false,  -- set to false if you will remap every key or if you using old version of nvim-
```

**Comment by ray-x** [comment]
@lordvidex Does the setup option works for you?

**Comment by lordvidex** [comment]
Yess! Thanks a lot, I also did the same for your ray-x/go.nvim library which uses my keybindings now. Thanks
