### ISSUE TITLE
Next treesitter reference error `]r`

### ISSUE THREAD

**Issue by lordvidex** [ray-x/navigator.lua#274]
I got an error with the following stacktrace when I pressed `]r`:

## StackTrace
E5108: Error executing lua: .../packer/start/navigator.lua/lua/navigator/treesitter.lua:425: attempt to call field 'index_of' (a nil value)
stack traceback:
        .../packer/start/navigator.lua/lua/navigator/treesitter.lua:425: in function <.../packer/start/navigator.lua/lua/navigator/treesitter.lua:403>

## My Configs
```
...
  use {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate"
  }
  use({
    "nvim-treesitter/nvim-treesitter-textobjects",
    after = "nvim-treesitter",
    requires = "nvim-treesitter/nvim-treesitter",
  })
  use 'nvim-treesitter/nvim-treesitter-refactor' -- this provides gotodef when lsp is buggy
  -- Go
  use 'ray-x/go.nvim'
  use { 'ray-x/guihua.lua', run = 'cd lua/fzy && make' }
  use 'ray-x/navigator.lua'
...
```

**Comment by ray-x** [comment]
Thanks for the info/logs.
This should be fixed at the latest version.
