### ISSUE TITLE
Typo in code?

### ISSUE THREAD

**Issue by jonashaag** [ray-x/navigator.lua#278]
Should this be `vim.lsp.buf.signature_help`? In my debug logging, `vim.lsp.signature_help` is always `nil`.

https://github.com/ray-x/navigator.lua/blob/b9931d5c01c323a8c5dd619a6bb9aebb3aa88b56/lua/navigator/lspclient/mapping.lua#L23

**Comment by ray-x** [comment]
thanks for pointing it out. It should be fixed.
