### ISSUE TITLE
Confusing result when pressing c-n/p

### ISSUE THREAD

**Issue by jonashaag** [ray-x/navigator.lua#279]
Sorry for the dumb question, I'm pretty new to Neovim and LSP setup.

The autocomplete suggestions are pretty reasonable, Python example:

<img width="543" alt="Screenshot 2023-06-02 at 15 12 22" src="https://github.com/ray-x/navigator.lua/assets/175722/52fa41e2-a39e-46cc-adc5-91c2c9326f41">

However when I press C-n to select the first entry, the list of results changes:

<img width="289" alt="Screenshot 2023-06-02 at 15 12 30" src="https://github.com/ray-x/navigator.lua/assets/175722/2da9c97c-7c6c-4451-8ac1-05ffdedc69d0">

Also, the documentation/annotation seems to be gone.

I'd also like to have function documentation when I select an element:

<img width="303" alt="Screenshot 2023-06-02 at 15 12 46" src="https://github.com/ray-x/navigator.lua/assets/175722/d65f364e-0757-4161-9e5b-70e420a539da">

Is there anything else interacting with C-n/p?

<details>

```lua
return {
	{
		"hrsh7th/nvim-cmp",
		dependencies = { "hrsh7th/cmp-nvim-lsp", "hrsh7th/cmp-path", "hrsh7th/cmp-buffer" },
		config = function()
			local cmp = require("cmp")
			cmp.setup({
				sources = { { name = "nvim_lsp" }, { name = "path" }, { name = "buffer" } },
			})
		end,
	},
	{
		"ray-x/lsp_signature.nvim",
	},
	{
		"neovim/nvim-lspconfig",
		config = function()
			for _, lsp in ipairs({ "pyright" }) do
				require("lspconfig")[lsp].setup({
					on_attach = function()
						require("lsp_signature").on_attach()
					end,
				})
			end
		end,
	},
	{
		"ray-x/navigator.lua",
		dependencies = {
			{ "ray-x/guihua.lua", build = "cd lua/fzy && make" },
			"ray-x/lsp_signature.nvim",
			"neovim/nvim-lspconfig",
			"nvim-treesitter/nvim-treesitter",
		},
		config = function()
			require("navigator").setup({
				debug = true,
				keymaps = {
					{
						key = "<C-m>",
						func = vim.lsp.buf.signature_help,
					},
				},
			})
		end,
	},
}
```
</details>

**Comment by ray-x** [comment]
Not so sure about your setup, Are you using nvim-cmp for autocomplete ?

**Comment by jonashaag** [comment]
Yes, see the "Details" button in my post, it contains the entire LSP related setup.

**Comment by ray-x** [comment]
The provider in your case is cmp which will override `<C-n/p>` setup
You have to config cmp in this case.

e.g.
https://github.com/ray-x/nvim/blob/7e1578b5762b40df6f7e93d2b5bcb5032ab6ec83/lua/modules/completion/config.lua#L133-L136

**Comment by jonashaag** [comment]
Ah thanks!
