### ISSUE TITLE
The default keymaps override gt for switching to the next tab

### ISSUE THREAD

**Issue by Haegin** [ray-x/navigator.lua#28]
Switching to the next tab is definitely a more common use case for me than going to the type definition, and breaking default bindings that are already in people's muscle memory sounds like a bad idea. Would it be possible to change the binding for go to type definition to another key or at least add the ability to turn off certain mappings without needing to remap everything?

**Comment by rdpopov** [comment]
Would say the same for gi keymap, which overrides the action to go to last insert operation. I did notice in the source that the keymaps that are not overridden are set to what the default is and if default_mapping is disabled keybinds are never set.

**Comment by ray-x** [comment]
The plugin already has options to handle that. Maybe my README.md is not clear enough. There is a setting `keymaps` which will override default keymaps.  e.g.
```
{
keymaps = {{key = "GR", func = "references()"}}, 
}
```

This keymap will replace default `{key = "gr", func = "references()"}` in the plugin.

Hope this is what you need.

I updated the document so please take a look and give it a try. Thanks!
