### ISSUE TITLE
Autocompletion not properly working when navigator is enabled

### ISSUE THREAD

**Issue by purpleblackferret** [ray-x/navigator.lua#284]
I am using lazy.nvim 
this is my plugins.nvim file https://pastebin.com/kLG0wtaw

whenever i enable navigator.lua the autocompletion(I use nvim-cmp btw) behaves abnormally , the complete snippet doesnt get printed

when navigator is disabled , in the following scenario
![image](https://github.com/ray-x/navigator.lua/assets/133736078/a9267419-8b17-4342-96ff-5bb3a2416be1)
after pressing enter it would print the complete template 
![image](https://github.com/ray-x/navigator.lua/assets/133736078/71d28ba7-5a8d-4315-a106-dbbf8a8f9959)
like this

but when i enable navigator, pressing enter on the same scenario would print only the word 'map'
![image](https://github.com/ray-x/navigator.lua/assets/133736078/a55fb15d-56b3-400b-ba85-b783a4496802)
kinda like this

what can i do about it now

i have disabled guihua with autocmd as mentioned [here](https://github.com/ray-x/navigator.lua#work-with-nvim-cmp-and-nvim-autopairs), but that does not make any difference
Help me out please

**Comment by ray-x** [comment]
Seems something with the LSP config. 
go
![image](https://github.com/ray-x/navigator.lua/assets/1681295/d5a2968f-6042-4bb9-964b-292c98730141)
cpp
![image](https://github.com/ray-x/navigator.lua/assets/1681295/e69e5af4-9d61-4a53-863b-7b9386ae23d9)

I suspect the lsp is not running. what is result of `:LspInfo` ?
Also, you can setup lsp yourself to make sure it works in your scenario/project structure.
I do not use c++ in daily based. the default ccls setup
```lua
    ccls = {
      on_attach = on_attach,
      init_options = {
        compilationDatabaseDirectory = 'build',
        root_dir = [[ util.root_pattern("compile_commands.json", "compile_flags.txt", "CMakeLists.txt", "Makefile", ".git") or util.path.dirname ]],
        index = { threads = 2 },
        clang = { excludeArgs = { '-frounding-math' } },
      },
      flags = { allow_incremental_sync = true },
    },
```
You can override the settings.

**Comment by purpleblackferret** [comment]
@ray-x I dont think its issue with lsp
lsp seems to be running as usual
I ran :Lspinfo
when navigator is disabled
![image](https://github.com/ray-x/navigator.lua/assets/133736078/04b93bdf-4bd3-48f9-8db2-6e65b18851b6)
and when its enabled
![image](https://github.com/ray-x/navigator.lua/assets/133736078/201a55a6-6122-4099-a34d-d8dda9264ffb)

I think it might be some issue with nvim-cmp or luasnip most probably
could you check once ?

also, how can I override the settings ?

**Comment by purpleblackferret** [comment]
Is the issue happening because navigator is trying to use ccls but my lsp configuration is only done with clangd ?

**Comment by purpleblackferret** [comment]
I disabled ccls , but it still seems to be not working

**Comment by ray-x** [comment]
In readme.md check the tsserver/gopls section
You can either set lsp.enable = false to skip lsp setup and you can use your own setup (check https://github.com/ray-x/navigator.lua/#integrate-with-mason-williambomanmasonnvim), or put your own config in ccls or clangd to replace what navigator has:
```lua
  {
   lsp = {
    enable = true,  -- skip lsp setup, and only use treesitter in navigator. 
    tsserver = {
      filetypes = {'typescript'} -- disable javascript etc,
      -- set to {} to disable the lspclient for all filetypes
    },
    gopls = {   -- gopls setting
      on_attach = function(client, bufnr)  -- on_attach for gopls
        -- your special on attach here
        -- e.g. disable gopls format because a known issue https://github.com/golang/go/issues/45732
        print("i am a hook, I will disable document format")
        client.resolved_capabilities.document_formatting = false
      end,
      settings = {
        gopls = {gofumpt = false} -- disable gofumpt etc,
      }
    }
  }
}
```

**Comment by purpleblackferret** [comment]
I disabled lsp completely and its still not working
I think the issue is with luasnip
I think enabling navigator is creating some issues with luasnip actually
Could you check/do something about that ?

**Comment by ray-x** [comment]
TBH, I am using luasnip, navigator and cmp on a daily basics. 
Also there is a sample config in the playground folder and you can try those out.
playground/init_packer.lua

**Comment by purpleblackferret** [comment]
that init_packer.lua does not contain any config for c++
what should i change in it to make it work with c++

sorry to annoy , i am sorta beginner in these things

and is there any chance that using lsp with mason would make things work ?


or could you provide any config for c++ with cmp, luasnip and navigator which sorta works and doesnt have the quirk i have been facing ?

**Comment by ray-x** [comment]
I used your setup and ran tests under ubuntu with `ccls`. It works fine for me
![image](https://github.com/ray-x/navigator.lua/assets/1681295/64ac77ed-7118-415f-a363-286248cf98df)
I no longer use c++ and clangd is too heavy for me to install and test. But I do not see anything wrong with ccls.

**Comment by ray-x** [comment]
Also I pushed a update to playground/init.lua so it supports `cmp` as well
https://github.com/ray-x/navigator.lua/blob/master/playground/init.lua
```
navigator.lua/playground/cpp❯ nvim -u ../init.lua  main.cpp
```
works fine for me:
![image](https://github.com/ray-x/navigator.lua/assets/1681295/35886a79-200e-49ed-af66-93f4d79f7440)

**Comment by purpleblackferret** [comment]
The issue is not that autocompletion is not working ,  autocompletion is working.
Here is the issue.
When navigator is disabled - 
![2023-10-13 09-58-14 (online-video-cutter com)](https://github.com/ray-x/navigator.lua/assets/133736078/417c5866-10d5-4714-87ee-7c7ee9744ee7)
and when navigator is enabled - 
![22](https://github.com/ray-x/navigator.lua/assets/133736078/763b7bad-9c61-487a-9039-784083078351)
it does not write the template part
and this things keeps happening even with minimum config with nvim cmp and with both clangd and ccls

everything else works fine, just this thing keeps happening when navigator is enabled, i have tested with many other plugins , i think navigator is the reason why it might be happening


can we do anything about this ?

**Comment by purpleblackferret** [comment]
I tested with the init.lua you posted in the commit, i think it has the same issue actually

**Comment by ray-x** [comment]
Would you try latest the version? It should be fixed for cpp with ccls. I did not try clangd.

**Comment by purpleblackferret** [comment]
Yeah it is now working with latest version.
Clangd is working too.

Thanks you very much.
That was a big help.
