### ISSUE TITLE
Focusable diagnostics

### ISSUE THREAD

**Issue by kbwo** [ray-x/navigator.lua#287]
At first, thank you for great plugin.

I want to focus cursor on diagnostics window.
[This line](https://github.com/ray-x/navigator.lua/blob/3f0c3d75c336a04b546899e5cec2e8f7e2d0ab11/lua/navigator/diagnostics.lua#L324) makes the window unfocusable.

Is there any reason for this?
Do you plan to make the interface more configurable in the future?

**Comment by ray-x** [comment]
Thanks for the suggestions, It was hardcoded. I have updated it to be configurable.

**Comment by kbwo** [comment]
> Thanks for the suggestions, It was hardcoded. I have updated it to be configurable.

I appreciate your quick resolution of the issue!
