### ISSUE TITLE
Question: What are the value_changed and value_definition icons?

### ISSUE THREAD

**Issue by hjkatz** [ray-x/navigator.lua#288]
Thanks for the great plugin! I think adding some docs around how to configure the icons would be very helpful. I spent some time figuring it all out from the source code and am willing to open a PR.

But first, what are the `value_changed` and `value_definition` icons used for? I see they're used for a `ts_report` in `prepare_for_render()` called in `gui.lua`, but I cannot seem to figure out where/how to _see_ these icons. Could you help me out?

**Comment by ray-x** [comment]
<img width="505" alt="image" src="https://github.com/ray-x/navigator.lua/assets/1681295/359c1fd6-97e2-4ef6-b40b-6f432da14915">

ts stands for treesitter
value_changed: if the symbol you checking is been modified in that line by a `=` assignment
value_definitation: if the symbol defined in that line
But they require treesitter supported for the language you worked with.

**Comment by hjkatz** [comment]
hmmm, I don't see those symbols in my setup.

![image](https://github.com/ray-x/navigator.lua/assets/2234516/f781867e-729c-45f2-82dc-eac2254a6d9c)


Here's a snippet of my config:

```
 lsp = {
      diagnostic_scrollbar_sign = false, -- disable scrollbar symbols
      enable = false,
      disable_lsp = "all",
      document_highlight = true,
      tsserver = {
          single_file_support = true,
      },
      format_on_save = true,
  },
  icons = {
    icons = true, -- requires nerd fonts

    [...] -- other icon settings

    -- Values
    value_changed = '📝',
    value_definition = '🐶🍡', -- it is easier to see than 🦕
    side_panel = {
      section_separator = '󰇜',
      line_num_left = '',
      line_num_right = '',
      inner_node = '├○',
      outer_node = '╰○',
      bracket_left = '⟪',
      bracket_right = '⟫',
    },

   [...] -- other icon settings
  },
}
```

`:LspInfo`
![image](https://github.com/ray-x/navigator.lua/assets/2234516/05cfb243-fea3-472c-a37e-ab5a2db97e2e)

Of note, I'm on neovim 0.9:

```
:version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
```

So maybe this is an inline text thing?

**Comment by hjkatz** [comment]
I think I found it!

![image](https://github.com/ray-x/navigator.lua/assets/2234516/1642779e-2629-4983-a58a-e54e8782c4e0)


It's showing up here in the show references preview window, so I'll try changing the icons and then open a PR for docs/examples.
