### ISSUE TITLE
[Feature] Prevent fzy search

### ISSUE THREAD

**Issue by hjkatz** [ray-x/navigator.lua#291]
Is there a way to prevent the fzy search from happening by default when opening references (and other functions) for large lists? I notice that the behaviour seems to change when there are ~5 references found (then I can immediately start using j/k to move up/down) vs. when there are ~15 references (then I just start filtering for "jjjjjjj"... which is no fun).

What I would like is:
* Never start the fzy search by default (some config here or in guihua)
* Enter the fzy search using `/` or another mapping while in the popup panel

I wasn't able to find where/how this behaviour was being set in the code with a quick read.

**Comment by hjkatz** [comment]
This might be an insert vs. normal mode thing. Maybe the default mode is insert when the number of list items is greater than some threshold...?

**Comment by ray-x** [comment]
You are right, It is in `Insert`mode when the listed items are more than a page.
You can simplify change back to `Nomal` mode when you need to move up/down. Or use `imap` to move up/down e.g. `<C-n> and <C-p>` or `<Up>` and `<Down>`

**Comment by hjkatz** [comment]
Can I change the threshold of "when the listed items are more than a page"?

I always want to open up guihua windows in `Normal` mode.

**Comment by ray-x** [comment]
I added a new option to the config `prompt_mode = 'insert', -- 'normal' | 'insert'`

**Comment by hjkatz** [comment]
I updated locally and didn't see the changes work as expected.

So I manually changed this diff in my local plugin's code:

```
    opts.transparency = config.transparency
    if #items >= config.lines_show_prompt then
      opts.prompt = true
      opts.enter = _NgConfigValues.prompt_mode == 'insert'
    end

+   opts.prompt = true
+   opts.enter = false
+
```

and still I see the prompt mode starting in insert mode.

**Comment by ray-x** [comment]
Yes. you are right. There are another piece been missing. I updated the code and run some tests and it should work now

**Comment by hjkatz** [comment]
Great! Looks like everything is working now :)
