### ISSUE TITLE
Is an option to make disable default keymaps planned?

### ISSUE THREAD

**Issue by mtwtkman** [ray-x/navigator.lua#294]
I noticied default keymap `gt` conflicts neovim's one that works as `:tabnext`, so now  I overwrote my navigator's keymaps setting for avoiding this problem.

But it seems a bit wierd that `gt` is set for neovim's default behaviour in navigator.

I think that there are two choices against this.

1. Remove `gt` mapping from navigator's default keymaps. But this is a breaking change. 
2. Add an option to disable (or remove) navigator's keymaps on demand.

Are there any plans about this?
 
If I can do that already, I apologize for my fault.
 
Thanks for this remarkable masterpiece plugin.

**Comment by ray-x** [comment]
There are two options you can use
```lua
  default_mapping = true,  -- set to false if you will remap every key
  keymaps = {{key = "gK", func = vim.lsp.declaration, desc = 'declaration'}}, -- a list of key maps to override default 
```

**Comment by MaiLunJiye** [comment]
> There are two options you can use
> 
> ```lua
>   default_mapping = true,  -- set to false if you will remap every key
>   keymaps = {{key = "gK", func = vim.lsp.declaration, desc = 'declaration'}}, -- a list of key maps to override default 
> ```

This is my config:

```
    keymaps = {
        {key = "gt", func = nil, desc = 'goto tab'},
        {key = "g0", func = nil, desc = 'symbol outline'},
    }, -- a list of key maps
```

`gt` works as expected, but `g0` dosen't.

This is output of `map g0`

```
n  g0          *@<Lua 373: ~/.local/share/nvim/lazy/navigator.lua/lua/navigator/symbols.lua:20>
                 document_symbols
```

**Comment by ray-x** [comment]
When replacing one of the current mappings, the code check if `func` is binded in navigator keymaps, not the key.
e.g.
if you want to map `gr` to `open symbole outline` you can do it anywhere in your config. If you want to change navigator `func = require('navigator.reference').async_ref` key map to `gg` , you override it in navigator config.
