### ISSUE TITLE
Q. What happened to diagnositc_config_sign [sic]

### ISSUE THREAD

**Issue by hjkatz** [ray-x/navigator.lua#307]
In my config I previously had:
```
local lsp_attach = function(client, bufnr)
  local opts = { buffer = bufnr }
  require("navigator.dochighlight").documentHighlight(bufnr)
  require("navigator.lspclient.highlight").add_highlight()
  require("navigator.lspclient.highlight").diagnositc_config_sign() -- [sic]
...
```

But I don't see that field anymore (nvim is throwing an error). What should we update this config/field to instead?

**Comment by PerMalmberg** [comment]
It looks to have been replaced by `config_signs()` in this commit. https://github.com/ray-x/navigator.lua/commit/40c6bb3a5ecc11d14cec1308e53e9abcc34cf0b7#diff-648dac2ff11c5d47dfe35a33761b6d3e80efcf85544ab268a4f21c92fdb13032
