### ISSUE TITLE
Navigator is consuming a lot of memory

### ISSUE THREAD

**Issue by ddaniel27** [ray-x/navigator.lua#315]
Hi, I've used your plugin for a long time and I really love it. I have a problem here that I hope we can be able to solve.
I've saw that after some mins (~30 mins) neovim starts to lagging when change window/buffer/tab, go to a definition, implementation, so on. I tried to debug it turning on/off plugins. That brings me here. I notice that when I use something related with navigator, my RAM usage starts to raise. I was able to replicate the lag behavior in two machines (Mac M3, Arch linux x86), just jumping through definitions. Even jumping between two files, it took like 10 jumps to start lagging.

So basically, navigator isn't freeing memory, it's allocating more memory at a point that neovim just freezes several seconds just to switch windows.

![image](https://github.com/user-attachments/assets/94f910fb-30e0-41ac-bbba-20a408aadc17)
With 15 jumps
![image](https://github.com/user-attachments/assets/096fc320-f68d-4aff-ace7-8192b7cfd5a0)
With 20 jumps
This seems to be exponential.

This happened using go files. Files that doesn't have a lsp (or something that helps to get definitions/go to files) installed like lua is fine.
Neovim version
```
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```
Also happened with versions 0.9.X both machines.

Please forget any redaction mistakes, I'm tired debugging this all night. I hope this can help to get a fix or if you can point any potential place to do the fix, I'll be happy to help trying to fix it.

**Comment by ray-x** [comment]
Could you share more info, e.g. the sample project and the LSP you are using?

**Comment by ddaniel27** [comment]
Yeah, I can provide you with a sample project
[A backend project](https://github.com/ddaniel27/back-pensatta). There is nothing special, just a backend.
This is also happening with my company repositories (that unfortunately I can't give you a repo to see), but all are just normal go projects with small/medium/large code base.

I'm using `gopls` as my lsp
```bash
$ gopls version
golang.org/x/tools/gopls v0.15.2
```

This is my lsp config for navigator
```lua
        lsp = {
          format_on_save = false,
          code_action = {
            enable = true,
          },
          code_lens_action = {
            enable = false,
          },
          gopls = {
            settings = {
              gopls = {
                usePlaceholders = false,
              },
            },
          },
        },
```

I don't know if there is more relevant info that I can share with you, just let me know and I'll be happy to help

**Comment by ddaniel27** [comment]
Hey, I've been trying to troubleshooting this a little bit, I just want to share with you some useful info that I found.
I tracked the lag up to `definition_hdlr` function into [lua/navigator/definition.lua](https://github.com/ray-x/navigator.lua/blob/master/lua/navigator/definition.lua). I wrote some logs to debug and this is what I found:

**Function with logs added**
```lua
local definition_hdlr = function(err, locations, ctx, _)
  local start_time = vim.loop.hrtime() -- get the start time
  local start_mem = collectgarbage('count')

  if err ~= nil then
    if tostring(err):find('no type definition') or tostring(err):find('invalid range') then
      vim.notify('Definition: ' .. tostring(err), vim.log.levels.DEBUG)

      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('1 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))
      return vim.lsp.buf.hover() -- this is a primitive type
    elseif tostring(err):find('no identifier') then

      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('2 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))

      return vim.notify('Definition: ' .. tostring(err), vim.log.levels.DEBUG)
    end
    vim.notify('Defination: ' .. tostring(err) .. vim.inspect(ctx), vim.log.levels.WARN)

      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('3 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))

    return
  end
  if locations == nil or vim.tbl_isempty(locations) or type(locations) == 'number' then
    log(locations)
    log('unable to handle request')
    vim.notify('Definition not found')

      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('4 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))

    return
  end

  local oe = require('navigator.util').encoding(ctx.client_id)

  locations = util.dedup(locations)
  log(locations)
  log('found ' .. #locations .. ' locations')
  if vim.islist(locations) then
    if #locations > 1 then
      local items = locations_to_items(locations)
      gui.new_list_view({ items = items, api = 'Definition', title = 'Definition' })
    else
      local loc = vim.lsp.util.make_position_params()
      -- let check if the location is same as current
      if
        loc.textDocument.uri == locations[1].uri
        and loc.position.line == locations[1].range.start.line
        and loc.position.character == locations[1].range.start.character
      then
        vim.lsp.buf.type_definition()
      else
        vim.lsp.util.jump_to_location(locations[1], oe)
      end
    end
  else

      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('5 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))

    return
  end
      local elapsed_time = (vim.loop.hrtime() - start_time) / 1e6 -- convert to ms
      local end_mem = collectgarbage('count') - start_mem
      print(string.format('6 branch - Elapsed time: %.3fms - Memory diff: %.3fKB - Initial Memory: %.3fKB', elapsed_time, end_mem, start_mem))

  return true
end
```

**Actual logs**
```
6 branch - Elapsed time: 19.487ms - Memory diff: 839.413KB - Initial Memory: 10597.967KB                                                                                                                            
6 branch - Elapsed time: 9.103ms - Memory diff: 138.247KB - Initial Memory: 9182.038KB                                                                                                                              
6 branch - Elapsed time: 10.009ms - Memory diff: 125.786KB - Initial Memory: 14681.901KB                                                                                                                            
6 branch - Elapsed time: 13.346ms - Memory diff: 119.091KB - Initial Memory: 9999.645KB                                                                                                                             
6 branch - Elapsed time: 21.183ms - Memory diff: 121.657KB - Initial Memory: 9475.389KB                                                                                                                             
6 branch - Elapsed time: 40.083ms - Memory diff: 127.700KB - Initial Memory: 17122.500KB                                                                                                                            
6 branch - Elapsed time: 66.202ms - Memory diff: 118.622KB - Initial Memory: 8826.390KB                                                                                                                             
6 branch - Elapsed time: 119.110ms - Memory diff: 119.845KB - Initial Memory: 14993.913KB                                                                                                                           
6 branch - Elapsed time: 253.276ms - Memory diff: 125.759KB - Initial Memory: 16297.065KB                                                                                                                           
6 branch - Elapsed time: 343.913ms - Memory diff: -2070.076KB - Initial Memory: 10943.944KB                                                                                                                         
6 branch - Elapsed time: 552.294ms - Memory diff: 123.173KB - Initial Memory: 9505.059KB                                                                                                                            
6 branch - Elapsed time: 876.451ms - Memory diff: 118.388KB - Initial Memory: 11226.063KB  
```
Now, this seems to be not related with memory in this functions, but processing time is keeping rising. I waited around ~15 seconds between each call, I also called collectgarbage("collector") but time doesn't go down. I'll be trying to track the exact spot where it's lagging. I have some suspicions about `locations` logic but I need to do more research. I hope this helps a little bit.

**Comment by ray-x** [comment]
I am surprised about the memory usage. On my laptop it stay 0.1~0.5% using the sample project (16GB M3) after I jump between files for 5mins. 
The plugin will communicate with gopls in background when file updated/open and it should stop communication when things are stable.
How many files are opened? are there any large system/lib files? e.g. when I open `fmt/printer.go` the memory will jump to 0.8% and once I close it it will back to 0.2% after a few secs.

**Comment by ddaniel27** [comment]
Hi, I'm updating this. I downloaded your dotfiles for nvim (pretty neat btw) and all work fine. I've been jumping through all the project (even the echo files) and nothing lags. I think it should be something related with my config (?) so I think I can close this.

Big thanks for your help and your amazing plugin. I'm gonna try to find what in my config is lagging my nvim haha.
