### ISSUE TITLE
Run external LSP extension

### ISSUE THREAD

**Issue by adgai19** [ray-x/navigator.lua#33]
Is there any way to run external LSP extensions while disabling lsp setup calls from navigator.lua? I want to run [nvim-jdlts](https://github.com/mfussenegger/nvim-jdtls) and on the README it  is specifically mentioned not to run `require'nvim_lsp'.jdtls.setup{}`.

**Comment by ray-x** [comment]
You can disable  loading jdtls from navigator by following setup:

```lua
require'navigator'.setup({
  lsp = {
    jdlts = {
      filetypes = {} -- disable javascript etc,
    },
 }
```
