### ISSUE TITLE
Broken via guihua with 

### ISSUE THREAD

**Issue by mattbailey** [ray-x/navigator.lua#36]
Stripped down config to just the example in the README:

```vim
call plug#begin('~/.vim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'ray-x/guihua.lua', {'do': 'cd lua/fzy && make' }
Plug 'ray-x/navigator.lua'

" Plug 'hrsh7th/nvim-compe' and other plugins you commenly use...

" optional, if you need treesitter symbol support
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

call plug#end()

" No need for rquire('lspconfig'), navigator will configure it for you
lua <<EOF
require'navigator'.setup()
EOF
```

Tried with neovim-0.5.0 and the current nightly 0.6.0-... but every thing I try with navigator just throws the error:

`gp` throws:

`E5108: Error executing lua .../matt.bailey/.vim/plugged/guihua.lua/lua/guihua/rect.lua:13: attempt to index field 'rect' (a nil value) `

`gs` throws:

`Error executing vim.schedule lua callback: ...y/.vim/plugged/navigator.lua/lua/navigator/signature.lua:61: attempt to index local 'config' (a nil value)`

Can confirm with `:LspInfo` that LSP is attached and working otherwise.

**Comment by ray-x** [comment]
Hi, @mattbailey 
Thanks for bug reporting.

`gp` should have been fixed in latest version.  (I used it less often)

Could you check `gs` work for you after plugin update? I can not reproduce the error you saw. So I am not sure if my fix works or not.

**Comment by mattbailey** [comment]
yes! both are now resolved, thanks @ray-x
