### ISSUE TITLE
Only load installed lsp

### ISSUE THREAD

**Issue by phamlehuy53** [ray-x/navigator.lua#38]
I suggest using [nvim-lspinstall](github.com/kabouzeid/nvim-lspinstall) to load specified lsp not all

**Comment by ray-x** [comment]
Are you suggesting use `require"nvim-lspinstall".is_server_installed(lang)` to test and enable lsp ? 

Yes, could be an option to integrate some of its features.

**Comment by phamlehuy53** [comment]
I was just going to say that!
