### ISSUE TITLE
navigator error on nvim startup

### ISSUE THREAD

**Issue by ckoehler** [ray-x/navigator.lua#40]
Seeing this when I `nvim file.rs`:

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua .../start/navigator.lua/lua/navigator/lspclient/clients.lua:323: attempt to index a nil value
```

Used to work fine, so looks like it was introduced with [a85c3e89ae1b820ec93c0be0b32434f5d31ff82d]. 

Am I missing some config or something?

**Comment by ray-x** [comment]
Sorry for that, I need to handle rust_analyzer setup. Should have been fixed.

**Comment by ckoehler** [comment]
Thanks! It's not just Rust, that filename was an example.

**Comment by ray-x** [comment]
Yes. It affect multiple LSPs with non-default setup.
Could you check if the fix work for you?

**Comment by ckoehler** [comment]
It doesn't, same issue, both with Rust and Lua. I suspect it may be related to some other config though; when I open a file, no language server is connected. I have to `:e` to connect one. Trying to track that down...

**Comment by ray-x** [comment]
Did you passed in an custom setup?
You can enable log output by setup:
require'navigator'.setup({
  debug = true, -- log output, log path: ~/.local/share/nvim/gh.log
})

**Comment by ckoehler** [comment]
For some reason, LSP config was in an ftplugin file, which didn't get loaded, or not loaded fast enough, so no LSP was active, probably partly causing the navigator error.

**Comment by ray-x** [comment]
Hi, @ckoehler 
I find the issue and it should been fixed.
It was caused by lspconfig changed it's default setup. And that setting was disabled by default in my vimrc.

**Comment by ray-x** [comment]
@ckoehler 
Is the issue still occur ?

**Comment by ckoehler** [comment]
No, thanks!
