### ISSUE TITLE
occur error of workspace three keymaps

### ISSUE THREAD

**Issue by hituzi-no-sippo** [ray-x/navigator.lua#41]
Hi.

Thank you for making a great plugin.

I'm getting an error on the workspace three keymaps.
The error message is same on three keymaps.
I get the following error message.

`E5521: <Cmd> mapping must end with <CR> before second <Cmd>`

The three keymaps that the error occurs was configured as follows.

```
:map <space>
n  <Space>wl   * <Cmd>lua vim.lsp.buf.<Cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR><CR>
n  <Space>wr   * <Cmd>lua vim.lsp.buf.<Cmd>lua vim.lsp.buf.remove_workspace_folder()<CR><CR>
n  <Space>wa   * <Cmd>lua vim.lsp.buf.<Cmd>lua vim.lsp.buf.add_workspace_folder()<CR><CR>
```

I am using this plugin default keymaps.

I think that the following code is related to this issue.

https://github.com/ray-x/navigator.lua/blob/a85c3e89ae1b820ec93c0be0b32434f5d31ff82d/lua/navigator/lspclient/mapping.lua#L45-L47

Thank you.

**Comment by ray-x** [comment]
Thanks for bringing this up. I did not handle the workspace command correctly. A bug fix was submitted.

**Comment by hituzi-no-sippo** [comment]
Thanks for the bug fix.
LGTM 😄
