### ISSUE TITLE
Add option to disable virtual text

### ISSUE THREAD

**Issue by kdheepak** [ray-x/navigator.lua#42]
Hi. Thanks for the plugin, I’m a fan.

Currently it doesn’t appear for us to be able to disable virtual text for diagnostics. Can that be made into a configuration option?

More generally, it would be nice if the handlers were composable with my existing set up. Like I’d like to use the code actions handler from this plugin and other handlers from other plugins. Maybe this is too much of an ask though, so consider this a stretch feature request.

**Comment by ray-x** [comment]
Thanks for the suggestion,
I add two options:
```lua
lsp ={
    diagnostic_virtual_text = true,  -- show virtual for diagnostic message
    diagnostic_update_in_insert = false,
}
```
Please check if those setup works for you

**Comment by kdheepak** [comment]
Wow! Thanks for the quick response!
