### ISSUE TITLE
is not intergret with `https://github.com/akinsho/flutter-tools.nvim`

### ISSUE THREAD

**Issue by ayoubelmhamdi** [ray-x/navigator.lua#45]
`akinsho/flutter-tools.nvim` this plugin is configured `LSP` for `flutter/dart` automatically ,
so : 
 - `LSP Client` load tow time 
 - code action load item tow time 
 - everything is slow and some time not work

**Comment by ray-x** [comment]
There is an option to prevent lsp been loaded. Maybe it can prevent every received twice.


```
{
  lsp = {
    disable_lsp = {'dartls'}, 
  }
}
```
