### ISSUE TITLE
custom mapping

### ISSUE THREAD

**Issue by gaetan-puleo** [ray-x/navigator.lua#5]
Hi. 

You did a great job with this plugin!

I want to know if it's possible to create a custom mapping?

**Comment by ray-x** [comment]
One way to do that is (e.g use `gk` to find reference)
```lua
  require "navigator".setup({
        on_attach = function(client)
          -- override mapping here:
          vim.cmd([[nunmap gr]])
          local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
          buf_set_keymap('n', 'gk', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
          client.resolved_capabilities.document_formatting = false
        end,
  })
```

But, I am also open to other suggestions

**Comment by gaetan-puleo** [comment]
It could be great to be able to disable the mapping if wanted and let the user to create a custom mapping with
`nvim_set_keymap` or `nvim_buf_set_keymap`.

On my side I want to use https://github.com/folke/which-key.nvim to manage my bindings.

Maybe I miss something, I'm not into lua and I'm a beginner at neovim config and related stuff.

**Comment by ray-x** [comment]
I add a`default_mapping = true,` in settings
set it to false if you want to remap everything.  Please check if it works for you.

**Comment by gaetan-puleo** [comment]
it works great! @ray-x !

**Comment by adgai19** [comment]
Is there some way to disable specific keybindings? As most of default keybindings work well for me but I want to change only one or two.

**Comment by ray-x** [comment]
Yes. you can

```lua
    require"navigator".setup({
      keymaps = {{key = "RF", func = "references()"}},
    } 
```
In above example, you override default reference() keybind of `gr`   with `RF`

**Comment by adgai19** [comment]
So that would release `gr` to be used for other  keybindings?

**Comment by ray-x** [comment]
yes. you can bind `gr` in another plugin in this example.

**Comment by adgai19** [comment]
I tried  doing something  like that 
```
    keymaps = {
        {key = "gK", func = "declaration()"},
        {key = "<leader>ff", func = "<cmd>Telescope find_files<CR>"}
    }, -- a list of key maps
```
but I am getting wrong mapping
![Screenshot from 2021-07-22 09-30-51](https://user-images.githubusercontent.com/29275245/126588434-b25b268a-3a24-453e-bb0f-150f79e2de34.png)

**Comment by adgai19** [comment]
> ```lua
>           vim.cmd([[nunmap gr]])
> ```

I was able to do it by doing this. Thanks

**Comment by ray-x** [comment]
Okey. You got me on that.
<cmd>lua vim.lsp.buf.formatting() is the only one hardcoded and can not be overrided. I will leave it open for now.

As you mentioned, `buf_set_keymap('n', 'gk', '<cmd>lua vim.lsp.buf.references()<CR>', opts)` is also good way to override default key mapping.
