### ISSUE TITLE
Not working with LunarVim

### ISSUE THREAD

**Issue by jmauriciosalasmoreno** [ray-x/navigator.lua#52]
The plugin does not work with LunarVim. 

LunarVim `gd` stopped working for going to the definition
Navigator `gD` also does not work

I'm using LunarVim https://github.com/LunarVim/LunarVim. And the following lines to setup Navigator

{"ray-x/guihua.lua", run = "cd lua/fzy && make"},
{"ray-x/navigator.lua",
    config = function()
      require'navigator'.setup({
        lspinstall = false
      })
    end
},

lspinstall = true has the same behavior

**Comment by ray-x** [comment]
Seems works fine for me
```lua
 {"ray-x/guihua.lua", run = "cd lua/fzy && make"}, 
 {
    "ray-x/navigator.lua",
    config = function()
      require'navigator'.setup({lspinstall = true})
    end
  },
```

![image](https://user-images.githubusercontent.com/1681295/131238245-44cb722b-caf9-4c02-9310-86f2c7f80154.png)

Please make sure
1) Install LSP with LSPInstall and  lspinstall=true; or manually install LSP server to $PATH and set lspinstall=false
2) PackerCompile
3) As lunarvim key mapping for `g` is mapped to which key, so `gr`mapping may failed to work. You will have to redo mapping

**Comment by ray-x** [comment]
Does it work for you now?

**Comment by jmauriciosalasmoreno** [comment]
It's working now. Even `gr` key bind.  But I'm not sure what changed from the previous attempt
Thanks a lot for your quick response!
