### ISSUE TITLE
Backspace skips a character when at the end of the line in navigator.rename float window

### ISSUE THREAD

**Issue by BehzadE** [ray-x/navigator.lua#53]
Pressing backspace at the end of the word in the rename floating window deletes a character and then moves an extra character to the left.

This issue is caused by the mapping of backspace to `<ESC>xi` in line 27 of rename.lua. 

A possible fix is mapping it to `<ESC>"_cl` but you might have a better alternative.

**Comment by ray-x** [comment]
Thanks, great suggestion! I update the map to `<BS>` to `"_cl`

**Comment by BehzadE** [comment]
Thanks for adding it.
