### ISSUE TITLE
Add the possiblity to disable <space>ff  binding to vim.lsp.buf.formatting()

### ISSUE THREAD

**Issue by BehzadE** [ray-x/navigator.lua#57]
Currently this keymapping overrides my own and I can't find a way to disable it. It seems to be hard coded in the mapping.lua.

**Comment by ray-x** [comment]
Please use   e.g. `<space>kk`
```lua
keymaps = {{key = "<space>kk", func = "formatting()}}
```

**Comment by BehzadE** [comment]
Thanks that seems to have fixed the overriding keymap but currently the formatting doesn't work at all. Neither the new key set nor the autoformatting when saving files.

**Comment by BehzadE** [comment]
Thanks. It's fixed now.
