### ISSUE TITLE
no ui showing

### ISSUE THREAD

**Issue by dominikhaid** [ray-x/navigator.lua#59]
The Plugin is not working for me. 
Could it be related to the following ?

[issue](https://github.com/glepnir/lspsaga.nvim/issues/241)

**Comment by ray-x** [comment]
The master branch already supported neovim0.6+
Would you share your minimum vimrc and neovim version?

**Comment by dominikhaid** [comment]
Thanks Ray-X after you confirmed me that the issue can not be related to upgrade of nvim, I checked my configs again.
Something was wrong with my servers, we can close this here.
