### ISSUE TITLE
Any plan support other language client implementation

### ISSUE THREAD

**Issue by QiBaobin** [ray-x/navigator.lua#6]
Good project. 

I think a lot of people might use other implementation instead of lsp-config, like LanguageClient-neovim. Do you have a plan to remove the dependency?

**Comment by ray-x** [comment]
Not really, I think lspconfig will be the default LSP client in a few months when nvim 5.0 release. 
Most of my code does not really depend on lspconfig. But as I am not sure about the effort(I do not use other LSP config ATM), I do not have a plan for that.
