### ISSUE TITLE
java with jdtls

### ISSUE THREAD

**Issue by dominikhaid** [ray-x/navigator.lua#62]
I have nvim-jdtls installed.
I also have use lspinstall.

When i try to run a command like signature_help() navigator shows me something like "man.vim: no manual entry".
Sometimes the plugin even shows me man entrys that are not related to java. The native LSP is working like expected.
Diagnostics are even working. LspSaga also shows right results.

I think navigator just not registers the server, or is maybe conflicting with nvim-jdtls.

My config fo navigator is :

```
require "navigator".setup(
  {
    debug = false,
    code_action_icon = " ",
    width = 0.75,
    height = 0.3,
    preview_height = 0.35,
    lspinstall = true,
    border = {"╭", "─", "╮", "│", "╯", "─", "╰", "│"},
    on_attach = function(client, bufnr)
    end,
    default_mapping = true,
    keymaps = {{key = "gs", func = "signature_help()"}},
    treesitter_analysis = true,
    code_action_prompt = {enable = true, sign = true, sign_priority = 40, virtual_text = true},
    icons = {
      code_action_icon = " ",
      diagnostic_head = "🐛",
      diagnostic_head_severity_1 = "🈲"
    },
    lsp = {
      jdlts = {
        filetypes = {} -- disable javascript etc,
      },
      format_on_save = true
    }
  }
)
```
i also tried it before without the part below, it did not work too

```
    lsp = {
      jdlts = {
        filetypes = {} -- disable javascript etc,
      },
      format_on_save = true
    }
```

**Comment by ray-x** [comment]
It works with my minium vimrc

![image](https://user-images.githubusercontent.com/1681295/133173790-703b707d-aea6-4d71-a0f7-b4ee99580321.png)

Also. For signature help, you can check my signature help plugin. 
https://github.com/ray-x/lsp_signature.nvim


Also please share your java code when the plugin failed to work. Thanks!

**Comment by dominikhaid** [comment]
Ok, thanks for your replay, I could not get it to work, but I will investigate it further as soon as I have time. 
If I'm not able to solve it I will check back, for now I close the issue.

**Comment by rishabh3** [comment]
Hey @ray-x ,
I have also tried and was not able to get it to work with jdtls (navigator plugin), but it works with lsp installed by lsp installer. Can you please link your minimal vimrc or nvim config which can help me here?

**Comment by ray-x** [comment]
Please make sure you have following setups
# .bashrc
export JDTLS_HOME=/path/to/jdtls_root # Directory with the plugin and configs directories

# Optional:
export JAVA_HOME=/path/to/java_home # In case you don't have java in path or want to use a version in particular
export WORKSPACE=/path/to/workspace # Defaults to $HOME/workspace

You can refer to my minium setup:

https://github.com/ray-x/nvim/blob/master/min/init_paq.lua
