### ISSUE TITLE
Diagnostics lingering after they are fixed. 

### ISSUE THREAD

**Issue by BehzadE** [ray-x/navigator.lua#64]
Hi. I've started to notice this problem that diagnostic floating texts don't get removed after I've fixed the problem. 
![image](https://user-images.githubusercontent.com/16238750/133980620-8aa6d811-5919-4076-80f1-00ca1fc1aef9.png)
![image](https://user-images.githubusercontent.com/16238750/133980679-39574fac-3655-4c78-b29d-5380e2a300dd.png)

The workaround I'm currently using is running LspRestart to get rid of the extra texts.

**Comment by ray-x** [comment]
Is it from latest version. I have a fix submitted early today.

**Comment by BehzadE** [comment]
It is I think.
![image](https://user-images.githubusercontent.com/16238750/133982469-40b320c2-1057-4972-8363-aad159734000.png)

**Comment by ray-x** [comment]
My bad, I fixed it earlier but this fix was not pushed. Should updated now.

**Comment by BehzadE** [comment]
Thank you.
