### ISSUE TITLE
How to configure/debug formatting?

### ISSUE THREAD

**Issue by dusty-phillips** [ray-x/navigator.lua#65]
I've set up navigator and it seems to be working for most features, but I'm not getting format on save functionality in Python or Typescript projects. When I was using coc, I had to set `python.formatting.provider` to `black`, and `eslint.autoFixOnSave`. I'm not sure how to configure these for lsp/navigator. From the docs it sounds like this should work out of the box, but my files are stubbornly refusing to format! My navigator config:

```lua
require('navigator').setup {
  lsp = {
    format_on_save = true,
    disable_lsp = {'denols'}
  }
}
```

I know it's not much to go on, but any advice on how to debug the problem would be most welcome.

**Comment by ray-x** [comment]
That is depends on the LSP. If lsp has document_formatting supported, The config will work.
If your lsp does not support formatting(e.g pyright), you may use efm-language-server. 

Add 
```
local   pythonBlack ={
    formatCommand = [[black --quiet -]],
    formatStdin = true
  }
```
To your efm config.

Sample efm config can refer to this thread: https://github.com/ray-x/navigator.lua/issues/31
