### ISSUE TITLE
Q: how to change the highlight foreground color of selected item in list view

### ISSUE THREAD

**Issue by bryceyang** [ray-x/navigator.lua#66]
<img width="814" alt="Screen Shot 2021-09-21 at 12 57 58 AM" src="https://user-images.githubusercontent.com/9302617/134043287-f87ecbc9-934d-4d38-9903-2d39541dff93.png">

the corlorscheme i use is https://github.com/Dualspc/spaceodyssey.nvim

the selected color is too white to see the text when using `spaceodyssey.nvim` with `navigator.lua`. I have tried modify `GHListDark` and `GHTextViewDark`,  but nothing changed.

BTW aurora is a good corlorscheme, but it's too purple for me. (my problem)

**Comment by ray-x** [comment]
It is GHListHl and was calculated from GHListDark and PmenuSel. What is the value of those values?

**Comment by bryceyang** [comment]
> It is GHListHl and was calculated from GHListDark and PmenuSel. What is the value of those values?
> I think you may have an inverted PmenuSel

The `spaceodyssey.nvim` does have custom PmenuSel hightlight.

Thanks for your quick reply! Setting GHListHl works. 
<img width="851" alt="Screen Shot 2021-09-21 at 9 44 26 AM" src="https://user-images.githubusercontent.com/9302617/134099850-56ce9a47-3829-4d20-b28c-49a5c2c8e65a.png">
