### ISSUE TITLE
disable_lsp = 'all' causes errors

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#67]
If I set `disable_lsp = 'all'` according to the `README.md` to use my own lsp setup, `navigator.lua` raises error:
![Snipaste_2021-09-21_21-44-25](https://user-images.githubusercontent.com/33576822/134182223-77403499-4f69-441a-be6d-45a1ffe91b80.png)

The configuration is:
```lua
require("navigator").setup({
    default_mapping = true,
    lsp = {
        disable_lsp = "all",
    },
})
```

**Comment by ray-x** [comment]
commited a fix for this.

**Comment by spindensity** [comment]
Thanks!

I can confirm the bug has been fixed.
