### ISSUE TITLE
:bn causes error

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#68]
# Steps to reproduce

1. Open one source code file, make sure it's the only listed buffer;
2. Press <kbd>g</kbd><kbd>p</kbd> to preview a symbol's definition;
3.  In the definition window, press <kbd>Ctrl</kbd> + <kbd>e</kbd> to exit it;
4. Execute `:bn` command.

# Excepted behavior

No error occurs.

# Actual behavior

An error is raised:

![Snipaste_2021-09-22_01-29-39](https://user-images.githubusercontent.com/33576822/134218988-c94aa650-e1bd-4011-8a79-ad18fdb5329e.png)

**Comment by spindensity** [comment]
This bug makes https://github.com/akinsho/bufferline.nvim unusable.

**Comment by ray-x** [comment]
It should have been fixed. Please pull the updates.
