### ISSUE TITLE
Pressing number in the search prompt causes error

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#69]
# Steps to reproduce

1. Press <kbd>g</kbd><kbd>T</kbd> to open searching window;
2.  In the searching window, press any number.

# Excepted behavior

No error occurs.

# Actual behavior

An error is raised:

![Snipaste_2021-09-22_13-32-31](https://user-images.githubusercontent.com/33576822/134288453-d87cf6a5-33c6-4155-8b0c-10200d1f0437.png)

**Comment by ray-x** [comment]
Thanks for the reporting.
This is a bug.
But there is something slightly different than what you expected,  number 1~9 was mapped to select line 1~9 in the list.

**Comment by spindensity** [comment]
Thanks for the clarity and the quick fix!
