### ISSUE TITLE
navigator.lua can't distinguish multiple LSP servers

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#70]
I use [pyright](https://github.com/microsoft/pyright) and [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) for editing python code, my python buffer always connects to the two LSP servers, I use `null-ls.nvim` for code formating and `pyright` for everything else, the configuration is something like:

```lua
local pyright_on_attach = function(client, bufnr)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
end
require("lspconfig")["pyright"].setup({
    on_attach = pyright_on_attach,
})

local null_ls_on_attach = function(client, bufnr)
    client.resolved_capabilities.document_formatting = true
    vim.cmd([[
    augroup null_ls_on_attach_group
    autocmd! * <buffer>
    autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
    augroup END
    ]])
end
require("lspconfig")["null-ls"].setup({
    on_attach = null_ls_on_attach,
})
```

And this works fine.

But the option `format_on_save` in `navigator.nvim` settings seems to disable or enable all LSP servers the current buffer connected, this makes different servers do different things impossible.

**Comment by spindensity** [comment]
Maybe we could add some checks. If `format_on_save` equals to `nil`, we should skip touching `client.resolved_capabilities.document_formatting`, and let the users deal with it.

**Comment by ray-x** [comment]
There are two way to disable a lsp for formating:
1 with on_attach
```lua
lsp{
    gopls = {   -- gopls setting
      on_attach = function(client, bufnr)  -- on_attach for gopls
        -- your special on attach here
        -- e.g. disable gopls format because a known issue https://github.com/golang/go/issues/45732
        print("i am a hook, I will disable document format")
        client.resolved_capabilities.document_formatting = false
      end,
      settings = {
        gopls = {gofumpt = false} -- disable gofumpt etc,
      }
    },
}
```


2 Also, you can use:

```
disable_format_cap = { "pyright", "gopls"},
```

**Comment by spindensity** [comment]
Thanks, but there's still a problem.

I found `format_on_save` option was not the culprit, I set the option to `false`, the formating did not work, then I set it to 
 `true`, it still did not work. The code never got formatted.

After reading a part of the plugin's source code, I realized the option had no effect since I'd set `disable_lsp` to `"all".`

I commented out the line:

https://github.com/ray-x/navigator.lua/blob/5e500bef98002961ed4f5cb1f9a7dbb39b01144e/lua/navigator/lspclient/mapping.lua#L263

Then everything's OK.

**Comment by ray-x** [comment]
Ok, that is expected. if you disable all lsp then formatting setup would not work. The reason is the plugin will need to check capacity to make sure the lsp can format the document. If you init lsp with other plugins, navigator.lua has no idea when the LSP will startup/attach to buffer.

**Comment by spindensity** [comment]
The problem is when I disable all lsp in `navigator.nvim`, my settings outside the `navigator.nvim` stop working, the following `autocmd` does not work unless I comment out the line mentioned above.

```lua
local null_ls_on_attach = function(client, bufnr)
    client.resolved_capabilities.document_formatting = true
    vim.cmd([[
    augroup null_ls_on_attach_group
    autocmd! * <buffer>
    autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()
    augroup END
    ]])
end
require("lspconfig")["null-ls"].setup({
    on_attach = null_ls_on_attach,
})
```

**Comment by spindensity** [comment]
I think I have found the root cause, `format_hdl` checks whether the buffer has been modified, see the following code, but when some LSP servers call external tools to do formating directly, the check will fail, then the formating would never happen. One solution would be allowing users to customize the handler. 

https://github.com/ray-x/navigator.lua/blob/5e500bef98002961ed4f5cb1f9a7dbb39b01144e/lua/navigator/formatting.lua#L3-L25

If I comment out the lines 12 and 23, everything is OK.

**Comment by spindensity** [comment]
The following configurations work well, if someone encounter the same problem, that would be a workaround:

```lua
local mk_handler = require("navigator.util").mk_handler

local function set_format_handler()
    vim.lsp.handlers["textDocument/formatting"] = mk_handler(function(err, result, ctx, _) -- FIXME: bufnr is nil
        if err ~= nil or result == nil then
            return
        end

        -- If the buffer hasn't been modified before the formatting has finished,
        -- update the buffer
        local view = vim.fn.winsaveview()
        vim.lsp.util.apply_text_edits(result, ctx.bufnr)
        vim.fn.winrestview(view)
        -- FIXME: commented out as a workaround
        -- if bufnr == vim.api.nvim_get_current_buf() then
        vim.api.nvim_command("noautocmd :update")

        -- Trigger post-formatting autocommand which can be used to refresh gitgutter
        -- vim.api.nvim_command('silent doautocmd <nomodeline> User FormatterPost')
        -- end
    end)
end

function navigator_on_attach(client, bufnr)
    require("navigator.lspclient.attach").on_attach(client, bufnr)
    set_format_handler()
end
```

Then use `navigator_on_attach` when setting the LSP `on_attach` key.

**Comment by ray-x** [comment]
Thanks for sharing.

Both key mapping and code formatter are initialize inside on_attach.  If you do not enable lsp, On_attach will be called and so it is the mapping setup.

If you are using null_ls, which does not supported by navigator, you may need to provide on_attach function so key mapping and formatting setup can be hookup.

I am surprised to see need to comment out `if not vim.api.nvim_buf_get_option(ctx.bufnr, 'modified') `. Maybe I only use efm and the behavior is different compared to yours.

**Comment by spindensity** [comment]
I had provided the `on_attach` function and hooked it successfully before. But I think the key point is the following check would fail with some LSP servers, there's nothing to do with `format_on_save` or `disable_format_cap` or similar options. I am sorry for my misinterpretation before. The problem is the following handler simply can't deal with some special LSP servers.

https://github.com/ray-x/navigator.lua/commit/a2ddb1ff4bbee5abce72ca7abb4171b5f1baf685 gives users a chance to customize the formating handler to bypass the problem, that's OK.

https://github.com/ray-x/navigator.lua/blob/5e500bef98002961ed4f5cb1f9a7dbb39b01144e/lua/navigator/formatting.lua#L12

**Comment by spindensity** [comment]
I think https://github.com/ray-x/navigator.lua/commit/a2ddb1ff4bbee5abce72ca7abb4171b5f1baf685 is a reasonable fix to this problem, I would like to close the issue.

Thanks very much for your great work and patience.
