### ISSUE TITLE
lsp attaching multiple times to the same buffer

### ISSUE THREAD

**Issue by sagarc03** [ray-x/navigator.lua#71]
![Screen Shot 2021-09-22 at 2 27 02 PM](https://user-images.githubusercontent.com/25496917/134400734-2b880eef-52a0-4491-a035-43166ebe0714.png)

I tried it vanilla i.e. without using navigator it seemed to work fine.

**Comment by sagarc03** [comment]
`LspRestart `seems to fix this for now.

@ray-x can you point me to where would be the best place to start. I am a bit lost.

**Comment by ray-x** [comment]
It should be fine to attach the lsp clients multiple times.
The bug was introduced when I trying to enable lsp releated plugins in a lazyloading setup.

**Comment by ray-x** [comment]
I think this issue will be no-fixed. 
1) attach the buffer multiple times to LSP does not impact the functionality, nor the performance/memory usage.
2) It is more a balance between lazyloading vs preload.  lspconfig and lspinstall plugin only support pre-load. It means before you load source code, the plugin need to preconfigured. And it hook to `FileType` event so correspondent lsp can be loaded.  This plugin, on the other hand, is lazy-loaded.  It can be loadrd either before or after FileType event. To handle that, the plugin is triggering a re-load workflow when startup. However, then   re-load workflow is not perfect, a buffer may be attached multiple times.
3) preload vs lazyload. For project contains multiple filetypes. e.g. `go`, `yaml`, `html`, `sql`, `js`.  You can setup all lsp before file is loaded, and use FileType event to activate LSP.   But you will never know what lsp to pre-load if you jump from repo to repo. Unless you load them all.   While for this plugin, after the file is open, the plugin will check if LSP loaded or not, if not, will load the LSP.   It can be flaky if some of LSP take too long to startup.
4) As lots of plugin does not designed to be lazyloaded, it would be very had to make it exact same behaviour.

**Comment by sagarc03** [comment]
For case where,

Can the lazy loading be optional? I am not sure if there are any particular advantage of that though.

Also in the case of `lspinstall=True` preloading should not be an issue right?

PS: thanks for the detailed explanation.

**Comment by ray-x** [comment]
If you set lspinstall=True. You need run
```
  require'lspinstall'.setup()
  local servers = require'lspinstall'.installed_servers()
  for _, server in pairs(servers) do
    require'lspconfig'[server].setup{}
  end
```

As I said. this need to run preloaded before FileType event.

**Comment by shendypratamaa** [comment]
![Screenshot 2022-01-14 at 18 53 23](https://user-images.githubusercontent.com/76093597/149511455-47990f1e-5739-4fed-a149-ca49f5c0c518.png)

the problem same when using williamboman/nvim-lsp-installer ?, when first open e.g .lua, buffer detected properly, and i'm open another file like in this screenshoot, buffer detected but not attach for another file ?,

**Comment by shendypratamaa** [comment]
this is the same if using nvim-lsp-installer ?, when open e.g first file .lua, everything work properly, but when open another file in the same session eg open .vim .js .ts , buffer detected but not attach only first file have attach
