### ISSUE TITLE
Defaults aren't used with Sumneko Lua

### ISSUE THREAD

**Issue by Corey-Keller** [ray-x/navigator.lua#72]
I installed sumneko using `kabouzeid/nvim-lspinstall` and navigator has only this in the `config` key in packer: `require('navigator').setup({lspinstall = true}) `

So logically It should apply all of the [settings for sumneko](https://github.com/ray-x/navigator.lua/blob/a2ddb1ff4bbee5abce72ca7abb4171b5f1baf685/lua/navigator/lspclient/clients.lua#L174-L208) right?

Yet when I run neovim I get notes about `Undefined global 'vim'` so obviously this line isn't being applied: `globals = {"vim", "describe", "it", "before_each", "after_each", "teardown", "pending"}`

**Comment by ray-x** [comment]
That is because `lspinstall = true` setup will make navigator skip the sumneko config. I assume you will use Lspinstall to config the sumneko.
If you would like to config the sumneko with navigator. You can setup with

```lua
-- if you have lua-dev
 local luadev = {}
 local ok, l = pcall(require, "lua-dev")
 if ok and l then
   luadev = l.setup(cfg)
 end
-- end lua-dev
luadev.sumneko_root_path = sumneko_root_path
luadev.sumneko_binary = sumneko_binary

require('navigator').setup({lsp = {sumneko_lua=luadev}})
```

**Comment by Corey-Keller** [comment]
Ok. I think I've figured it out. To use the defaults from navigator, and use the lua ls from lspinstall, I just set:
```
local sumneko_dir = vim.fn.stdpath('data') .. '/lspinstall/lua/sumneko-lua/extension/server'
require('navigator').setup({lsp = { sumneko_lua = {
	sumneko_binary = sumneko_dir .. '/bin/Linux/lua-language-server',
	sumneko_root_path = sumneko_dir,
}}})
```
So now my main remaining confusion is why the server (when started by `lspinstall`) gives warnings for unused variables (`🦊 Unused local 'poo'`), but navigator doesn't when running the above.

**Comment by ray-x** [comment]
You should also see `Unused local`

![image](https://user-images.githubusercontent.com/1681295/134594843-50231987-b57c-420b-b0a8-f2f848f97ecf.png)



What if you enabled `lua-dev` as well?

**Comment by bryceyang** [comment]
> You should also see `Unused local`
> 
> ![image](https://user-images.githubusercontent.com/1681295/134594843-50231987-b57c-420b-b0a8-f2f848f97ecf.png)
> 
> What if you enabled `lua-dev` as well?
> 
> Also here is my minium virmrc:
> 
> https://github.com/ray-x/nvim/blob/4c70f277304a574c9fe48b4aa8adc711cb7cc707/min/vimrc.min#L176-L195

using lua-dev makes no difference. Even global vim is not working.
<img width="1002" alt="Screen Shot 2021-09-24 at 8 15 13 PM" src="https://user-images.githubusercontent.com/9302617/134672605-06f9c412-278a-4a4b-aac2-ee022a21f265.png">

my navigator.lua: 
```lua
local api = vim.api

local test

local sumneko_dir = vim.fn.stdpath('data') .. '/lspinstall/lua/sumneko-lua/extension/server'
local luadev = {}
local ok, l = pcall(require, "lua-dev")
if ok and l then
  print("luadev setup")
  luadev = l.setup({
      library = {
          vimruntime = true,
          types = true,
  }})
end
luadev.sumneko_root_path = sumneko_dir
luadev.sumneko_binary = sumneko_dir .. '/bin/macOS/lua-language-server'

require'navigator'.setup({
    default_mapping = true, -- set to false if you will remap every key
    keymaps = {
        {key = "gK", func = "declaration()"},
        {key = "gr", func = "references()"},
        {key = "ga", func = "code_action()"},
        {key = "gi", func = "implementation"},
        {key = "gd", func = "definition()"},
        {key = "gf", func = "formatting()"},
        {key = "gL", func = "require('navigator.diagnostics').show_line_diagnostics()"},
        {key = "gG", func = "require('navigator.diagnostics').show_diagnostic()"},
        {key = "]d", func = "diagnostic.goto_next({ border = 'rounded', max_width = 80})"},
        {key = "[d", func = "diagnostic.goto_prev({ border = 'rounded', max_width = 80})"},
        {key = "]r", func = "require('navigator.treesitter').goto_next_usage()"},
        {key = "[r", func = "require('navigator.treesitter').goto_previous_usage()"},
    },
    lspinstall = true,
    lsp = {
        format_on_save = false,
        sumneko_lua=luadev
    }
})

api.nvim_command("hi default LspReferenceRead cterm=bold gui=Bold ctermbg=yellow guifg=none guibg=Black")
api.nvim_command("hi default LspReferenceText cterm=bold gui=Bold ctermbg=yellow guifg=none guibg=Black")
api.nvim_command("hi default LspReferenceWrite cterm=bold gui=Bold ctermbg=yellow guifg=none guibg=Black")
api.nvim_command(
    "hi default GHListHl guifg=#eceff4 ctermfg=189 guibg=#2d3439 ctermbg=238 gui=bold,italic cterm=bold,italic")
```

**Comment by ray-x** [comment]
As you still using `lspinstall = true,` I think you will need to set` lspinstall = false,` so lua sumneko will be loaded through navigator.

**Comment by bryceyang** [comment]
so set `lspinstall = true` or`disable_lsp=all` will both  disable navigator for loading its default lsp config?  

I thought `lspinstall = true` will just tell navigator to use the lsp binary in lspinstall dir. my bad.

**Comment by ray-x** [comment]
lspinstall = true will load lsp using lspinstall.setup().
I did not fully support lspinstall yet. One reason is the lsp client naming from `lspinstall` is different. e.g. `sumneko` was named as `lua`

**Comment by Corey-Keller** [comment]
@ray-x I have changed my navigator config to exactly match the lines from your minimum provided example:
```
local lspinstall_dir = vim.fn.stdpath('data') .. '/lspinstall'

local efm_cfg = {
	flags = {debounce_text_changes = 2000},
	cmd = {lspinstall_dir .. '/efm/efm-langserver', '-loglevel', '1', '-logfile', vim.fn.expand("$HOME") .. '/tmp/efm.log'}, -- 1~10
	init_options = {documentFormatting = true, codeAction = false, document_formatting = true},
	root_dir = require'lspconfig'.util.root_pattern({'.git/', 'package.json', '.'}),
	on_attach = function(client)
		client.resolved_capabilities.document_formatting = true
		client.resolved_capabilities.goto_definition = false
		local log = require("guihua.log").new({level = "info"}, true)
		vim.cmd([=[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting()]=])
	end,
	filetypes = {
		 'go', 'lua','sql',
	},

	settings = {
		rootMarkers = {".git/", 'package.json', 'Makefile', 'go.mod'},
		lintDebounce = "1s",
		formatDebounce = "1000ms",
		languages = {
			go = {
				{
					formatCommand = "golines --max-len=120	--base-formatter=gofumpt",
					formatStdin = true,
					lintCommand = "golangci-lint run",
					LintSeverity = 3
				}
			},
			lua = {
				{
					formatCommand = "lua-format --indent-width 2 --tab-width 2 --no-use-tab --column-limit 120 --column-table-limit 100 --no-keep-simple-function-one-line --no-chop-down-table --chop-down-kv-table --no-keep-simple-control-block-one-line --no-keep-simple-function-one-line --no-break-after-functioncall-lp --no-break-after-operator",
					formatStdin = true
				}
			},
		}
	}
}


local sumneko_dir = lspinstall_dir .. '/lua/sumneko-lua/extension/server'
require('navigator').setup({
	debug = true,
	width = 0.7,
	border = {"╭", "─", "╮", "│", "╯", "─", "╰", "│"},
	lsp = { sumneko_lua = {
		sumneko_binary = sumneko_dir .. '/bin/Linux/lua-language-server',
		sumneko_root_path = sumneko_dir,
	},
	efm=efm_cfg,
},
})
local poo = 'but'
```

I even included the `efm_cfg` part in case it mattered (which it doesn't seem to as efm isn't attached, but listed under `Other clients that match the filetype: lua`) but I still get no warnings (at all. Not for unused variables, trailing  whitespace... no matter what I type or do there are zero warnings or errors from the LSP).

**Comment by ray-x** [comment]
Is the latest version works for you?

**Comment by Corey-Keller** [comment]
@ray-x Nope.

1. If lua-dev is absent I still get the following error:
```
Error: attempted to load lua-dev.nvim which is not present in plugins table!                                                                                                                                    
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:13: Error: attempted to load lua-dev.nvim which is not present in plugins table!                                          
Please check your config for correctness 
```
2. When lua-dev is there, it "loads" fine. The quotes are because even though it starts without error and sumneko_lua gets attached to the buffer nothing happens (I have intentional 'issues' in spots of my code (like unused variables) that don't produce any warnings or anything)

**Comment by ray-x** [comment]
Ok, it should be fixed in the latest version.
