### ISSUE TITLE
Can't close floating window in some case

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#77]
If the language server is slow, after pressing <kbd>g</kbd><kbd>r</kbd>(find references), there would be some time to wait for the floating window to pop up. Before the floating window pops up, press <kbd>g</kbd><kbd>r</kbd> again, then wait until the window appears.

Now, press<kbd>Ctrl</kbd>+<kbd>e</kbd>, nothing happens, the window is not closed.
 
Execute `:q`, an error occurs:
![Snipaste_2021-09-23_15-59-10](https://user-images.githubusercontent.com/33576822/134473161-0d9c6e45-a393-4bfb-84ee-f828d33a374f.png)

Execute `:q!`, the window is closed, but the background of neovim turns gray:
![Snipaste_2021-09-23_16-05-10](https://user-images.githubusercontent.com/33576822/134473500-e69e1dca-f3d5-41c9-866f-4b8a59050afc.png)

**Comment by ray-x** [comment]
Partially solved autoclose the mask floating win
Regarding the reference windows failed to close. It is most likely because there are multiple floating windows instances created and override the global variables. That will not be a quick fix.

**Comment by spindensity** [comment]
> Partially solved autoclose the mask floating win
> Regarding the reference windows failed to close. It is most likely because there are multiple floating windows instances created and override the global variables. That will not be a quick fix.

After the fix, the preview window is broken. In any floating window, press <kbd>Ctrl</kbd>+<kbd>n</kbd> to preview the next item, the floating window would be closed automatically.

**Comment by ray-x** [comment]
Would you check if you have guihua.lua latest 403c2e07e774d8e1bba4d9ac8e1694e161386576 ?

**Comment by spindensity** [comment]
After https://github.com/ray-x/guihua.lua/commit/403c2e07e774d8e1bba4d9ac8e1694e161386576, the floating window is not closed automatically when pressing <kbd>Ctrl</kbd>+<kbd>n</kbd>.
