### ISSUE TITLE
incoming_calls and outgoing_calls cause errors when results from LSP server have multiple lines

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#78]
Sometimes LSP server would return results which have multiple lines when calling `vim.lsp.buf.incoming_calls` or `vim.lsp.buf.outgoing_calls`, and an error will be raised:

![Snipaste_2021-09-24_13-06-19](https://user-images.githubusercontent.com/33576822/134621250-6f587e86-01cf-48cb-87d3-bbbb5cdba73f.png)

For example, see the following code:
https://github.com/ray-x/navigator.lua/blob/633c7da38f2479d23f11a93ef70609d902fc30c7/lua/navigator/hierarchy.lua#L29-L41

With [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) `call_hierarchy_item.detail` could be something like this which would definitely cause errors since `vim.api.nvim_buf_set_lines` used by `guihua.lua` does not allow multiple-line text:
```rust
pub fn gen_range<T, R>(&mut self, range: R) -> T
where
     T: SampleUniform,
     R: SampleRange<T>
```

**Comment by spindensity** [comment]
Some possible solutions would be:
1. Discard `call_hierarchy_item.detail`, only use `display_filename`;
2. Use the first line of `call_hierarchy_item.detail`, but there may be corner cases to deal with;
3. Replace all `\n` to ` ` or `⏎` or something else, but that could reduce readability in some cases;
4. Handle the multiple lines in the UI components, that would be hard and unnecessary.

**Comment by ray-x** [comment]
@spindensity 
Still see this issue?

**Comment by spindensity** [comment]
Thanks, the bug has been fixed.
