### ISSUE TITLE
The floating window for symbols not work functionally

### ISSUE THREAD

**Issue by QiBaobin** [ray-x/navigator.lua#8]
When I use document_symbol or workspace_symbol, a very nice floating window pops, but either the navigation or search doesn't work, searching always highlight the first item, and backspace in insert mode doesn't work either. Navigation or enter/<c-o> don't navigation to a correct place.

**Comment by ray-x** [comment]
![Screen Shot 2021-06-01 at 11 24 48 am](https://user-images.githubusercontent.com/1681295/120253931-051f8200-c2cc-11eb-8ab9-648a503631a6.png)


Seems works in my end.
Can you send more info, e.g your lsp, and your neovim version.  I am using LATEST pulled yesterday.

Does treesitter document symbol work for you?

**Comment by ray-x** [comment]
Double-checked the code. I think there is a corner case not covered. I update guihua.lua. Would you please check if that fixed issue you saw?

**Comment by QiBaobin** [comment]
<img width="1615" alt="Screen Shot 2021-06-01 at 5 16 26 PM" src="https://user-images.githubusercontent.com/7072/120299155-55630800-c2fd-11eb-9e3e-b3c8cdb54e0a.png">
<img width="1070" alt="Screen Shot 2021-06-01 at 5 14 33 PM" src="https://user-images.githubusercontent.com/7072/120299170-598f2580-c2fd-11eb-9f9c-b56b8b051fbe.png">
<img width="1013" alt="Screen Shot 2021-06-01 at 5 09 32 PM" src="https://user-images.githubusercontent.com/7072/120299178-5bf17f80-c2fd-11eb-9fcc-43c4873a8827.png">

My neovim and all the plugins are updated to the latest, when I disable my init script, I got above error. Below are my plugin list:

```
return require('packer').startup({
function()

  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use 'tpope/vim-sensible'
  use 'tpope/vim-sleuth'
  use { 'tpope/vim-fugitive', config = function() 
    vim.api.nvim_set_keymap('', '<Leader>g',  ':Git<CR>gg<c-n>', { noremap = true })
    vim.api.nvim_set_keymap('n', '<Leader>d',  ':Gdiffsplit<CR>', { noremap = true })
  end }
  use { 'tpope/vim-commentary', config = function()
    vim.api.nvim_set_keymap('', '<Leader>c',  '<Plug>Commentary', { noremap = true })
    vim.api.nvim_set_keymap('n', '<Leader>cc',  '<Plug>CommentaryLine', { noremap = true })
  end }
  use 'tpope/vim-unimpaired'
  use 'tpope/vim-surround'

  use 'QiBaobin/vim-gradle'
  use 'sheerun/vim-polyglot'

  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
  use { 'neovim/nvim-lspconfig' }
  use {'ray-x/navigator.lua', requires = {'ray-x/guihua.lua', run = 'cd lua/fzy && make'}, config = function() require'navigator'.setup() end }

  use 'AndrewRadev/splitjoin.vim'
  use 'wellle/targets.vim'
  use 'airblade/vim-gitgutter'

  use { 'vim-airline/vim-airline', config = 'vim.cmd([[let g:airline#extensions#tabline#enabled = 0]])' }
  use { 'akinsho/nvim-bufferline.lua', requires = 'kyazdani42/nvim-web-devicons', config = function()
    vim.api.nvim_set_keymap('n', '<Leader>b',  ':BufferLinePick<CR>', { noremap = true })
    require("bufferline").setup{
      options = {
        numbers = "both",
        number_style = "superscript",
        diagnostics = "nvim_lsp",
      }
    }
  end }
  use { 'morhetz/gruvbox', config = 'vim.cmd([[colorscheme gruvbox]])' }
  use { 'scrooloose/nerdtree', opt = ture, cmd = { 'NERDTree' } }

  use "tversteeg/registers.nvim"
end,
config = {
  git = {
    depth = 1, -- Git clone depth
    clone_timeout = 300, -- Timeout, in seconds, for git clones
  }}
})

```

**Comment by ray-x** [comment]
@QiBaobin 
Thanks for the info.
You are using rust-analysizer. 

The first screenshot you sent contains error info. Is it when you using grubox?  Do you have any special color setup?
You saw the error is because navigator failed to calculate the default background.  I tried with grubox but did not see the error message you saw.

Also it seems reference and treesitter works.  That is strange.... both of them need to generate the color.


I did update the plugin and will capture more logs.
Would you help to update the packer plugins and see what happens?

**Comment by QiBaobin** [comment]
I commented all other plugins (including grubox), but it doesn't help.

It just doesn't work once I use the input textfield, otherwise it's good.

**Comment by QiBaobin** [comment]
I just ran the listview_test.lua file in the guihua repo, similar behavior with this. How could I provide more details?

**Comment by QiBaobin** [comment]
Sorry, @ray-x , it turned out to be my mistake, I forgot to run `cd fzy && make`. 

The search functionality works well now, but the navigation after searching seems not correct, you could tell from below screenshot, it always point to the first one, same in the preview panel.

<img width="1279" alt="Screen Shot 2021-06-01 at 8 25 18 PM" src="https://user-images.githubusercontent.com/7072/120323071-ad0e6d00-c317-11eb-9268-5a4e6f9b813b.png">

**Comment by ray-x** [comment]
Hi, QiBaoBin
I think the issue you saw regarding fzy is fixed. Please run PackerUpdate and check if it is fixed on your side.
Thanks!

**Comment by QiBaobin** [comment]
Thanks, I confirmed most of cases are fixed. The preview panel shows correct, `gT` works well, but while I use `g0` after searching, and choose, the cursor didn't move.

**Comment by ray-x** [comment]
That sounds wiered. 


https://user-images.githubusercontent.com/1681295/120420320-80099b00-c3a7-11eb-9050-6a5286dd905b.mov



Can you screenshot what is happing?

Also, a heads-up, you can not use \<CR\> to confirm select as you are in search mode, need to use \<C-o\> to open the file in preview.

**Comment by QiBaobin** [comment]
As you can see, `g0` doesn't work while `gT` works.

https://user-images.githubusercontent.com/7072/120424840-b8a57680-c39f-11eb-882a-f7e4e317078e.mov

**Comment by ray-x** [comment]
Should be fixed in latest version

**Comment by QiBaobin** [comment]
Confirmed, thanks!
