### ISSUE TITLE
Pressing number in the document symbol window causes error

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#80]
# Steps to reproduce

1. Press <kbd>g</kbd><kbd>0</kbd> to open document symbol window;
2. Press any number to jump to the corresponding line.

# Excepted behavior

No error occurs.

# Actual behavior

An error is raised:

![Snipaste_2021-09-26_21-21-50](https://user-images.githubusercontent.com/33576822/134809866-30d719ec-e92b-46ff-9c68-67d4f519894d.png)

**Comment by ray-x** [comment]
Fix pushed.

**Comment by spindensity** [comment]
Unbelievable speed!

It works, thanks!
