### ISSUE TITLE
error when both clangd and ccls are installed

### ISSUE THREAD

**Issue by bryceyang** [ray-x/navigator.lua#84]
when finding references of a func in c file, I got this error:
```
Error executing vim.schedule lua callback: ...k/packer/start/navigator.lua/lua/navigator/reference.lua:93: handle 0x5618da355850 is already closing
```
and after this, the preview file will be opened in reference list window if I press enter like below.
![image](https://user-images.githubusercontent.com/9302617/136505317-ccd5bd3b-d1b5-4296-8aa2-08e6868bbc22.png)

I found this was caused by I both installed clangd and ccls. After I set `disable_lsp = { "ccls"}` , problem sovled.

This could potentially be a bug. Or at least, I think there should be a notice in doc, cause ccls and clangd both are default configured by navigator.

**Comment by ray-x** [comment]
What issue did you see when ccls disabled?

**Comment by chriztheanvill** [comment]
> What issue did you see when ccls disabled?

Sorry, no. Its when its enabled. If is enabled. Creates .ccls-cache folder, then navigator complains and if I try to build, have errors because the ccls folder.
If sets:
```lua
disable_lsp = { 'ccls' }
```
Everything works fine.

**Comment by ray-x** [comment]
If you have multiple lsp installed and all provide same function
e.g.  ccls & clangd;   pyright&python-lsp
Navigator will start all available lsp installed. And that is causing issue when neovim send buffer request to lsp. The request will be broadcast too all clients and the plugin will get multiple responses.
To avoid that, please config the plugin in a way that only one will be effective for each buffer. You can disable the lsp, disable the filetype etc.
Why do I enable multiple lsp. As I may want to use ccls for cxx file and clangd for `c`. Also, in some cases different lsp for `js` and `ts`.
