### ISSUE TITLE
The filetype of the prompt buffer is not "guihua" but "guihua_<language>"

### ISSUE THREAD

**Issue by spindensity** [ray-x/navigator.lua#85]
Execute `:lua vim.lsp.buf.outgoing_calls()` or `:lua vim.lsp.buf.incoming_calls()`, the filetype of the prompt buffer of the popup window is `guihua_<language>`, if you work with `rust_analyzer`, the filetype would be `guihua_rust`.

Could you remove the `<language>` suffix, so users could do some customizations easily such as disabling `nvim-autopairs` in the prompt buffer of `navigator.lua`.

BTW, execute`:lua vim.lsp.buf.references()`, the filetype of the prompt buffer of the popup window is `guihua`, not `guihua_<language>`.

**Comment by ray-x** [comment]
There are only two types `guihua` and `guihua_rust`. The reason is there are special highlight setups for rust.

**Comment by spindensity** [comment]
OK, thanks.
