### ISSUE TITLE
WinScrolled autocommand throwing error

### ISSUE THREAD

**Issue by mattleong** [ray-x/navigator.lua#86]
## Set up:
```
require'navigator'.setup({
  code_action = {enable = true, sign = true, sign_priority = 40, virtual_text = false},
  code_lens_action = {enable = true, sign = true, sign_priority = 40, virtual_text = false},
  border = "single",
  lsp = {
    diagnostic_scrollbar_sign = nil, -- experimental:  diagnostic status in scroll bar area; set to nil to disable the diagnostic sign,
    format_on_save = false, -- set to false to disasble lsp code format on save (if you are using prettier/efm/formater etc)
  },
  treesitter_analysis = true, -- treesitter variable context
  keymaps = {
    {key = "gd", func = "definition()"}
  }, -- a list of key maps
  lspinstall = true, -- set to true if you would like use the lsp installed by lspinstall
})
```

## Issue

<img width="944" alt="Screen Shot 2021-10-10 at 9 35 54 AM" src="https://user-images.githubusercontent.com/3721204/136705140-9058b683-ac2a-4e3f-aa1e-87419f6ffc07.png">

Curiously, it does not occur in Lua files but will error like above when opening (or scrolling through) a TS file. 

The only mention of `WinScrolled` within the plugin is [here](https://github.com/ray-x/navigator.lua/blob/93c7eae2caac683f1c5800448331d95b4a93118e/lua/navigator/diagnostics.lua#L370). However, as you can see, I have `lsp.diagnostic_scrollbar_sign = nil` in my config, yet the autocommand still seems to be firing.

**Comment by ray-x** [comment]
Pleas check if latest version fixed this issue

**Comment by mattleong** [comment]
@ray-x Yup, seems to be working now. Thank you so much!
