### ISSUE TITLE
What is the best way to integrate with nvim-cmp?

### ISSUE THREAD

**Issue by lynndylanhurley** [ray-x/navigator.lua#87]
There is a step in the cmp setup where we're supposed to extend the lsp server `capabilities` param with the wrapper provided by cmp:

```lua
  -- Setup lspconfig.
  require('lspconfig')[%YOUR_LSP_SERVER%].setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  }
```

But I don't see any way to do that using the navigator setup process.

Consequently my cmp config doesn't seem to be working as should.

Does there need to be an additional hook into the `capabilities` config, similar to the one that exists for `on_attach`?

**Comment by ray-x** [comment]
The cmp/coq setup should be covered by the following codes:

https://github.com/ray-x/navigator.lua/blob/36683e3646cf83bea9040527bf9746058d4210bf/lua/navigator/lspclient/clients.lua#L357-L367
