### ISSUE TITLE
Q: how can i change the text color of list item in listview

### ISSUE THREAD

**Issue by isvicy** [ray-x/navigator.lua#89]
i switched to a light theme recently.  everything works fine with navigator.lua except the text color of list item in listview is too light to see. here is a screenshot
<img width="1042" alt="Screen Shot 2021-10-15 at 12 04 14 AM" src="https://user-images.githubusercontent.com/9302617/137355780-a5276a2b-e9c4-4879-8935-410e5a886efe.png">
. 
I tried to change `GHListHl` and `GHListDark`, but seems only fg and bg color is changed.  I don't have a glue how to change the text color. Please help.

**Comment by ray-x** [comment]
You may need this

e.g.
```
hi GHListDark guifg=#333333
hi GHListHl guibg=#DEDEDE
```
