### ISSUE TITLE
Separate treesitter setup from lsp setup

### ISSUE THREAD

**Issue by QiBaobin** [ray-x/navigator.lua#9]
I have installed a  lot of treesitter language supports, but only installed one language server, for those file types that don't have setup a language server, I would lost the treesitter features in this plugin. I know I could copy some of mapping to my init script, but I don't think this is only case from me. So could we separate the setup into two parts? Like use something like  `:TSInstallInfo` to detect and setup treesitter features, use lsp `onattach` like now to setup lsp features.

**Comment by ray-x** [comment]
Hi, QiBaobin
I am not sure I understand your suggestion/concern. 

This plugin does not depend on treesitter install and does not have treesitter setup file. For example, here is my treesitter setup:
https://github.com/ray-x/nvim/blob/master/lua/modules/lang/treesitter.lua


If you do not need treesitter for the plugin, 
set `treesitter_analysis = false` The plugin will not use treesitter and fallback.


I also install nvim-treesitter-textobjects and nvim-treesitter-refactor, both works fine with navigator.

**Comment by QiBaobin** [comment]
@ray-x , Sorry, I didn't get it clear. I think the plugin only add those key mappings when there is a language sever exists, but there are cases that treesitter mappings also help a lot while there is no language server for that file type, for example I have installed c, lua python etc treesitter but there is none of language server for them on my system.

**Comment by ray-x** [comment]
If the problem related to key mapping.
Even if you do not have LSP enable, plugin will have mapping setup for you. Reson is some of the LSP is slow and takes a few seconds to startup, the plugin will not wait until LSP is ready.

you can set `default_mapping=false` so NO default key mapping will be mapped when plugin startup.

Also you can use `keymaps = {{key = "gK", func = "declaration()"}}, `  to override specific function keymapping.

Do you want to add an option so even you only have treesitter, you still want the functions treesitter symbol been mapped (e.g. gT to show document symbol)?

**Comment by QiBaobin** [comment]
> Do you want to add an option so even you only have treesitter, you still want the functions treesitter symbol been mapped and the plugin works as if LSP been enable (e.g. gT to show treesitter document symbol)?
> I can check if is possible..... I had never think of that user case before.

Yes, that is! Please implement it if that's not a big change, that helps a lot!

**Comment by ray-x** [comment]
Add codes and allow treesitter part work in a minimum vimrc (without LSP)

**Comment by QiBaobin** [comment]
Confirmed, thanks!
