### ISSUE TITLE
[Bugs] Open windows.

### ISSUE THREAD

**Issue by chriztheanvill** [ray-x/navigator.lua#93]
Hi.
After open windows: You can write, but not erase, and if you erase moving the cursor and press 'Delete', you can erase, but the search does not refresh.

Also, you need to :q! to quit the window.

Men, I love your plugin :D

**Comment by ray-x** [comment]
Do you mean fzy search input?
You can use `<BS>` to delete char before current cursor and `<Del>` the char after cursor.
I did not see the refresh problem, did you run `cd lua/fzy && make` when install guihua.lua?

**Comment by chriztheanvill** [comment]
> Do you mean fzy search input? You can use `<BS>` to delete char before current cursor and `<Del>` the char after cursor. I did not see the refresh problem, did you run `cd lua/fzy && make` when install guihua.lua?

Hi. This issue happens with you? Because I still having it. This is my config.
https://github.com/chriztheanvill/My_Neovim

Would like to help, because I like this plugin.

**Comment by ray-x** [comment]
I did not see this issue so far.
Can you check if this issue happens if you using a minium vimrc?

**Comment by ray-x** [comment]
are you trying to search in the workspace symbol in a cpp project? What is lsp server you are using?

**Comment by chriztheanvill** [comment]
Yes, I am in a cpp project, and using clangd:
```lua
disply_diagnostic_qf = true,

        clangd = {
	on_attach = function(client, bufnr) end,
	cmd = {
		"clangd",
		"--background-index",
		"--pch-storage=memory",
		"--clang-tidy",
		"--suggest-missing-includes",
		"--all-scopes-completion",
		"--log=verbose",
		"--pretty",
		"--header-insertion=never"
	},
		filetypes = {"c", "cpp", "objc", "objcpp"},
		-- root_dir = utils.root_pattern("compile_commands.json", "compile_flags.txt", ".git")
		init_option = { fallbackFlags = {  "-std=c++2a"  } }
	},  -- clang
		cmake = {
			filetypes = {'cmake'},
			init_options = { buildDirectory = "build"}
		}, -- CMAKE
		gdscript = {}, -- Godot
		sumneko_lua = { -- LUA
	    	sumneko_root_path = "/home/cris/.LuaLSP/lua-language-server",
			sumneko_binary = "/home/cris/.LuaLSP/lua-language-server/bin/Linux/lua-language-server",
	    }, -- sumneko_lua 

```

**Comment by ray-x** [comment]
yes. there is a bug in fzy search. Pushed a fix and hope it works.

**Comment by chriztheanvill** [comment]
I found what makes that you can not erase:
With the plugin nvim-autopairs:
```lua
require('nvim-autopairs').setup{
disable_filetype = { "TelescopePrompt" , "guihua" },
...
}
```

**Comment by ray-x** [comment]
Thanks. that helps!
