### ISSUE TITLE
How to integrate with your go.nvim

### ISSUE THREAD

**Issue by xobtoor** [ray-x/navigator.lua#95]
I used to your go.nvim plugin because it works slightly better for me.

Is there a way to use it together with navigator?

**Comment by mattbailey** [comment]
handy for using the gopls installed with nvim-lsp-installer: 

```lua
local path = require 'nvim-lsp-installer.path'
local install_root_dir = path.concat {vim.fn.stdpath 'data', 'lsp_servers'}

require('go').setup({
  gopls_cmd = {install_root_dir .. '/go/gopls'},
  filstruct = 'gopls',
  lsp_codelens = false, -- use navigator
  dap_debug = true,
  dap_debug_gui = true
})
```

**Comment by sp4ke** [comment]
Hi, thanks for all the plugins,

I am using navigator, and I would like to use the extra lsp config for go from go.nvim but keep navigator for LSP related keymap/UI etc. 

Is this param `lsp_codelens = false, -- use navigator` still relevant to do in go.nvim ?

**Comment by ray-x** [comment]
Check this setup:
https://github.com/ray-x/nvim/blob/6dcf5a7abc1f0489299252bcb20e56a71fa4fa5f/lua/modules/lang/config.lua#L223-L236

And disable startup gopls/lsp in go.nvim by setting lsp_cfg = false (default)
lsp_codelens = false (as navigator also supports codelens)

**Comment by sp4ke** [comment]
Thanks, I already tried to to disable lsp_cfg and I made sure go.nvim is loaded after navigator. Is there a clean way to still use the inlay hints from go.nvim  ?
