### ISSUE TITLE
Error when trying to use a code action

### ISSUE THREAD

**Issue by tom-on-the-internet** [ray-x/navigator.lua#97]
Hello!

This project is awesome. Thank you.

I'm running into an issue when I try to use a code action.

In a TypeScript project, when I see the code action icon, I can type `<space>ca` to see a list of code actions. But when I try to run one I get the following error:

```
E5108: Error executing lua .../packer/start/navigator.lua/lua/navigator/lspwrapper.lua:441: attempt to index field 'commands' (a nil value) 
```

Is there a way for me to debug why command would be `nil`?

Thank you again

**Comment by ray-x** [comment]
I am glad you enjoy the plugin
A fix was pushed. But as I did not trying to reproduce this issue so I am not sure if it fixed or not.
I also add how to debug in README.md hope it helps.

**Comment by tom-on-the-internet** [comment]
Thank you so much!!
This worked.
You made my day.
