### ISSUE TITLE
Weird issue shows suddenly modal with error

### ISSUE THREAD

**Issue by mkubasz** [ray-x/navigator.lua#98]
When I open the rust file after writing some random words and exiting insert mode suddenly opened modal with text
`[ ]main fn()`
with error message
`Error executing vim.schedule lua callback: ...ack/packer/start/navigator.lua/lua/navigator/symbols.lua:107: at
tempt to index field 'range' (a nil value)`
[gh.log](https://github.com/ray-x/navigator.lua/files/7489084/gh.log)

And my [dotfile](https://github.com/mkubasz/dotfiles/blob/master/.config/nvim/lua/plugins/lsp.lua#L295)

**Comment by ray-x** [comment]
looks strange
you have
```
{
  containerName = "",
  kind = 12,
  location = {
    range = {
      end = {
        character = 7,
        line = 0
      },
      start = {
        character = 3,
        line = 0
      }
    },
    uri = "file:///home/tumnus/Projects/tempora/src/main.rs"
  },
  name = "main"
}

```
and

```
{
  deprecated = false,
  detail = "fn()",
  kind = 12,
  name = "main",
  range = {
    end = {
      character = 1,
      line = 3
    },
    start = {
      character = 0,
      line = 0
    }
  },
  selectionRange = {
    end = {
      character = 7,
      line = 0
    },
    start = {
      character = 3,
      line = 0
    }
  },
  tags = {}
}

```

It seems you have two LSP run at background. One is feeding incorrect value.

Also the floating is showing because a document_symbol was triggered. Is there a key combination mapped to that?

Looking into you dotfile, it may related to rust-tool
Can you check if you setup navigator like this?

```
--- require('rust-tools').setup({})
require'navigator'.setup({
  disable_lsp = {'rls'},
})

```

**Comment by mkubasz** [comment]
@ray-x This doesn't disable rls. I need to disable by comment rls config. https://www.reddit.com/r/rust/comments/lur37d/why_is_rls_still_so_bad/ :D So I think that will fix this issue :)
