### ISSUE TITLE
Support TeX (like texlab)

### ISSUE THREAD

**Issue by sbmueller** [ray-x/navigator.lua#99]
Hi there,
I think LaTeX is not yet supported by `navigator.lua`. Any plans to support that would be highly appreciated. I found this in `nvim-lspconfig` but I'm unfortunately unfamiliar with neovim/lua development: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/texlab.lua

Any chance this feature might be available in the near future?

**Comment by tani** [comment]
Basically, we just need to add the server names to the list. 
What would you like to do?

https://github.com/ray-x/navigator.lua/blob/db09db7ef39966b9c1403ac0d439fadb4b1422e0/lua/navigator/lspclient/clients.lua#L264-L270

**Comment by ray-x** [comment]
If you already have texlab installed. Add `texlab` in `servers` would auto-config the texlab. 
But I have never used tex before. Also, I am not sure if the reference/definition/signature works the same way for tex compared to other lsp servers.

**Comment by tani** [comment]
It works fine, at least for me. You might be able to close this issue.

**Comment by sbmueller** [comment]
Great, didn't know it was **that** easy 😃 thanks for the quick responses.
